### ISSUE TITLE
General discussion and miscellaneous ideas

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#1]
Feel free to add more: 

Rum
Vodka
Tequila
Pulque
Absinthe
Various new forms of wine and beer (Being worked on)
New strains of hops and grapes
A distillery
Bamboo ladders
Bamboo rope ladders
Giant barrels
Wormwood
Blue Agave
Maguey Agave
Gristmills
Revive the kitchen module
Bottling machine
Brandy
Cognac
Apple jack
Apple cider
Grape juice (technically already in though)
Whiskey
More ore dictionary support
Upland Rice
Better bees (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286298-growthcraft-jul-15-2014-proper-1-7-10-release?comment=2198 and http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286298-growthcraft-jul-15-2014-proper-1-7-10-release?comment=2200)
Deepwater rice
Ingame documentation
Villagers smashing grapes with their feet
Bamboo tiki torch
Villages made of bamboo
Minetweaker support
Wild Rice
Meat hooks
Chayote Squash
Various forms of squash that grow along the ground, possibly maybe watermelon and pumpkins could be made to grow like this too.
Fruit cocktails (alcoholic and non-alcoholic)
Moonshine
Agave Syrup (Sugar Alternative)
Desert module
Prickly pears
Cherry module
Nectar (golden apples in fruit press)
Cordial
Whiskey
Colonche
Bees spread flowers from other mods
Corn
Ayahuasca
Magic vines
Marine module
Wax, Honey, Grub (?) and Honeycomb blocks
Sushi
Brewing Keg (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10?page=4#c67)
Bamboo fences connect to blocks (Done)
Grape Soda (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10?comment=153)
Upgradable Fish Traps

**Comment by Sunconure11** [comment]
Decimal colors for fluids (the color appears to be determined by the code rather than any image, via decimal colors, hopefully these work, I am using this site to get decimal codes: http://www.colorhexa.com/), since I have not taught myself java yet (I will create some textures and models in the mean time):

Absinthe: 6393643

Rum: 10579213

Pulque: 16777200

Tequila: 16764309

Vodka: 14474460

Cognac: 10700827

Applejack: 14451517

Whiskey: 14003567

Moonshine: 12632256

Submit more decimal colors for fluids as needed.

**Comment by Ar97x** [comment]
Will it be with flowing textures or just simple, pure colored bottles?
Em 21/07/2015 01:03, "Joseph Caleb Jones" notifications@github.com
escreveu:

**Comment by Sunconure11** [comment]
Most likely they will be the same as those from growthcraft in terms of appearance.

**Comment by Ar97x** [comment]
That's nice. The main colors you chosr are pretty much ideal for me.
Em 21/07/2015 02:21, "Joseph Caleb Jones" notifications@github.com
escreveu:

**Comment by Sunconure11** [comment]
Fluids in this mod are colored via the code, not via static images. So most likely creating textures for the new drinks are not needed yet.

**Comment by Sunconure11** [comment]
I'll send an example of the fluid code.

**Comment by Ar97x** [comment]
I haven't worked with textures in minecraft yet, only public mod
translations and modpack config for my own use
Em 21/07/2015 02:29, "Joseph Caleb Jones" notifications@github.com
escreveu:

**Comment by Sunconure11** [comment]
https://github.com/Sunconure11/Growthcraft-1.7/blob/master/src/java/growthcraft/grapes/GrowthCraftGrapes.java

**Comment by Ar97x** [comment]
BTW, the contribution I can make to the mod is translating it to
portuguese, besides creative ideas.
Em 21/07/2015 02:31, "Victor Diehl" vdiehl97@gmail.com escreveu:

**Comment by Sunconure11** [comment]
That can work. Once Groth appears here, I will transfer ownership of this repo to him.

**Comment by Ar97x** [comment]
And I'll keep the translations updated, when new things come out.

**Comment by Ar97x** [comment]
As soon as he gets it, I'll make the same offer to him

2015-07-21 2:38 GMT-04:00 Victor Diehl vdiehl97@gmail.com:

> And I'll keep the translations updated, when new things come out.

**Comment by Alatyami** [comment]
Very cool, these are some great ideas for continuing a great mod.

Alatyami

Aka GrothHammerPick

**Comment by Sunconure11** [comment]
I will now transfer the repository to Groth. However, I will still update this thread.

**Comment by Sunconure11** [comment]
While I wait for him to accept it, I will create a texture for Agave Syrup, since that will be separate from the forms of alcohol the agave addon might add, assuming it takes hold.

**Comment by Sunconure11** [comment]
Hm, it seems I cannot transfer the repository to him.

**Comment by Sunconure11** [comment]
I created one texture for Growthcraft Agave. The idea for this module came from Azumarill on the forum, who suggested Agave crops.

**Comment by Sunconure11** [comment]
Agave Syrup textures are based on booze textures, but, it is not a fluid, so, its color is determined by the texture. I'm going to create a still model later.

**Comment by Sunconure11** [comment]
My idea for the still will likely look something like this: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Liquor_Still_Frankfort_489226997.jpg/800px-Liquor_Still_Frankfort_489226997.jpg

**Comment by Alatyami** [comment]
I have it forked here: https://github.com/alatyami/Growthcraft-1.7 

If you want to transfer it we can sync the two and then start using either mine or still use yours, up to you.

**Comment by Alatyami** [comment]
> Hm, it seems I cannot transfer the repository to him.

My Git account is "alatyami"

~Groth

**Comment by Alatyami** [comment]
> My idea for the still will likely look something like this: https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Liquor_Still_Frankfort_489226997.jpg/800px-Liquor_Still_Frankfort_489226997.jpg

Then we can have a pipe go to a tank for the resulting fluid.

**Comment by Sunconure11** [comment]
I know, but, it says I cannot transfer it because of the fact that you have a growthcraft repo as well.

**Comment by Alatyami** [comment]
Ah ... I removed mine it was named the same.

**Comment by Sunconure11** [comment]
Transfer requested.

**Comment by Ar97x** [comment]
If you can make a texture for a still like that, it would be awesome. And
Groth, do you want me to work on the portuguese translations now or do you
prefer to do some work before I start it? Remember to notify me as soon as
you get something new, this way I keep the translation updated
Em 21/07/2015 13:09, "Joseph Caleb Jones" notifications@github.com
escreveu:

**Comment by Alatyami** [comment]
That would be great. Please do so.

**Comment by Alatyami** [comment]
@Ar97x  I created another issue for you to use for the transition.

**Comment by Sunconure11** [comment]
I contemplated adding a domestic animals module to the list, but, before I do any modelling for this mod, including the still, I need to finish Deinocheirus for It's About Time. My sleep schedule is out of whack again so this could be a bit.

**Comment by Sunconure11** [comment]
However, atleast the start of the still should be done soon. I only have the head, the claws (and some minor details), plus creating a texture map and texturing it left.

**Comment by Sunconure11** [comment]
If the possibility of the still having its own pipes is implemented, I got this response on creating pipes.

https://www.reddit.com/r/feedthebeast/comments/3e42t3/i_have_a_question_regarding_models_for/

**Comment by Sunconure11** [comment]
However, I think it would be better to not implement our own pipes, but allow support for other pipes from other mods.

**Comment by Ar97x** [comment]
Agreed. Ender IO, Thermal Dynamics and Mekanism on top priority, since they
are the most popular mods that have fluiducts

**Comment by Alatyami** [comment]
Added fluiducts as Issue https://github.com/alatyami/Growthcraft-1.7/issues/3

**Comment by IceDragon200** [comment]
Can I add seaweed to the list of ideas?
:( I don't get to see much seaweed in mods, and the ocean is mostly barren anyway

**Comment by Ar97x** [comment]
No trouble for me. Do you have further ideas or will it be just miscellaneous?

**Comment by IceDragon200** [comment]
@Ar97x: Well we could add some more fishes/marine food stuff:
Lobster, Crab, Shrimp, their shells could be used as decorative blocks
...
Electric Eels; Which could double as a battery in certain tech mods.

Scenario:

```
Place a fish trap, 
Find an electric eel
Use said eel as a battery for your jet-pack
Once the eel has been depleted, ya fry him up for dinner.
...
PROFIT!?
```

**Comment by Ar97x** [comment]
Cool, I think that, as we already have rice from GC and Salmon from Vanilla, we can add seaweed and make sushi haha
As you had the idea, maybe a sea module could be added to our To Do List?

**Comment by Alatyami** [comment]
Very interesting ...

**Comment by Sunconure11** [comment]
The still will be worked on soon, my sleep schedule has been fixed. I need to finish the model I am making for another mod first, but, I'll likely push out some textures in the next few days.

**Comment by Sunconure11** [comment]
They will be block textures for the grape cultivars.

**Comment by IceDragon200** [comment]
I just realized, villages don't have rice! (as far as I saw)

Man shall not live by bread alone (and potatoes and carrots... and liqour)

**Comment by Ar97x** [comment]
I know, I want it too. It's tiring to break 1617272828 grass to get 10 rice to start a farm. If you want, I can make a schematic for it so you can base on it to implement rice farms at villages.

**Comment by IceDragon200** [comment]
@Ar97x :O That would be awesome, do eeeet!

**Comment by Ar97x** [comment]
Finished. As an excuse for my lateness, I did something for Bamboo and Apple modules too. I want you to have a look and give me a feedback, so if it is bad I can remake it. I put the schematics and the world I used to make them on the zip: https://www.dropbox.com/sh/44vgzc9che5x040/AABQVFuZEEWyJp-aIMRfRTcJa?dl=0

**Comment by IceDragon200** [comment]
@Ar97x I think you forgot to mention all the mods I need to play this world, it crashes with an Invalid Biome ID error, in addition, I tried loading the schematics using schematica, but some of the blocks are missing :(

You could provide some screenshots, I should be able to create the village components from those :3

**Comment by Ar97x** [comment]
Damn, that's right. I thought the other mods wouldn't interfere. I will do
it again just with GC

**Comment by Ar97x** [comment]
https://www.dropbox.com/s/9y4j6vmf8udkt75/Builds.zip?dl=0
I forgot to take screenshots, but the schematics and the world are there.

**Comment by Ar97x** [comment]
@Sunconure11 are you following and noting the suggestions for our list? If you are too busy or can't do it right now, I can take this function for some time.

**Comment by Sunconure11** [comment]
I'll go ahead and look for more suggestions.

**Comment by Sunconure11** [comment]
Added sushi and various block suggestions.

**Comment by Sunconure11** [comment]
I also added a bit more to the tubers concept page.

**Comment by dandudek7** [comment]
How about a revival of the Flowers module?

**Comment by Ar97x** [comment]
@IceDragon200 I think we'll need to change some things on the structures, people reported that they aren't spawning with support (foundation) and I've made some improvements to the Apiary. @alatyami could these improvements be on the next public release?

**Comment by Ar97x** [comment]
@EnderCreeper15 I haven't played with it, when I started to use GC the flowers module was already outdated.

**Comment by IceDragon200** [comment]
@Ar97x: What exactly is this support foundation you speak of, I think can allocate some time to fix it.

**Comment by Ar97x** [comment]
Structures generated on unlevelled locations get totally screwed, what we need is to make it spawn on top of a base, out of cobble or grass. If you want to know better, the report is on the comments of the CE thread http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10

**Comment by Ar97x** [comment]
I think 10 or 15 blocks of height are enough

-------- Mensagem Original --------
De:Corey Powell notifications@github.com
Enviado em:Fri, 28 Aug 2015 17:16:29 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Cc:Ar97x vdiehl97@gmail.com
Assunto:Re: [Growthcraft-1.7] Ideas suggested so far (#1)

**Comment by IceDragon200** [comment]
@Ar97x I saw the screenshot with the Bamboo Yard, I'm thinking of clearing the entire block/box with air first, placing a layer of dirt below the structure and then placing the structure on that, that way, nothing is in the building's bounding box. WDYT?

**Comment by Ar97x** [comment]
Do you think it'll work, even on uneven terrain? Maybe you can add some
condition to it spawn on surface level, or just on plain terrain, that the
schematic fits?
Em 29/08/2015 09:49, "Corey Powell" notifications@github.com escreveu:

**Comment by Ar97x** [comment]
Btw, don't mind working with the Apiary, I'll change that schematic soon,
I'm working on a new model, since most people didn't like it.

**Comment by IceDragon200** [comment]
@Ar97x Only extensive testing will say otherwise, I could look how vanilla does it (though I've seen houses tower over villages with 20 blocks of gravel in height as padding)

As for the Apiary, make it more vanilla village like I guess?

**Comment by Ar97x** [comment]
Yeah, me and people on forum have several ideas to improve it. I forgot to
suggest you to look on the villages behaviour on irregular terrains, the
structure made by Gwafu works just like the regular village buildings.

**Comment by Sunconure11** [comment]
The still will be created soon. However, I will be getting a new motherboard and cpu soon, so, I am holding off doing anything like that for now. Deinocheirus is put on hold until the maker of that mod finishes his port to 1.8.

**Comment by Sunconure11** [comment]
Computer is back. I will make the distillery over the weekend, due to the fact I have some stuff to do, such as schoolwork, and I have to continue updating my modpack.

**Comment by Sunconure11** [comment]
Added the brewing keg suggestion.

**Comment by IceDragon200** [comment]
Desert module idea: I just realized, we don't have cactus juice!
![Cactus Juice](http://i.imgur.com/GWOoa.gif)

Silly Avatar references aside, yes we could have cactus juice, this also gives me a reason to mess with the fruit press API, to allow different byproducts, currently EVERYTHING PRODUCES BONEMEAL (I can't even...), would be nice to get other byproducts from pressing...

In short, putting some `Cactus` in a `Fruit Press` should produce `Cactus Juice` and possibly `cactus green` instead of `bonemeal`.
This could open the door for other byproducts as well (`rose red` from `apples`, `magenta/purple` from `grapes`)

Also @Sunconure11 could you organize the suggested ideas into (Blocks/Machine, Liquids/Liquor, Modules so forth)

**Comment by Sunconure11** [comment]
I'll see to it within the next few days. This list is long though.

**Comment by Ar97x** [comment]
Just to add, a guy from the forum is keeping a Wikia page of the mod, any thoughts of what should we do?

**Comment by Sunconure11** [comment]
I don't know yet. Possibly redirect him to fill out the wiki here?

**Comment by Alatyami** [comment]
His wiki will allow us to fill it out like the FTB wiki, which since only the old 1.5 version is included in a FTB Modpack I'm thinking we could go with the one he has, just have to make sure that it is for long term.

**Comment by spannerman79** [comment]
@Ar97x what is the link to this third party wiki?  As some may or may not know a wiki can be created here in this project.

Many mod dev's use their own domain and hosting or use the location they store their code (github, gitlab etc) for wiki and so forth

**Comment by Ar97x** [comment]
We already have a wiki here on github, check alatyami's fork. The link for
the new wiki: http://growthcraft.wikia.com/wiki/Growthcraft_Wiki

**Comment by Ar97x** [comment]
Request from forum: "hey can i make a request can u make bamboo walls connet to blocks and glass planes b/c i dont like the the whole holes in my walls". You decide about it. Also, what will be the major feature for 2.4.x? The Still, Nether Module or Yeast?

**Comment by IceDragon200** [comment]
@Ar97x Well, Yeast is already in development, so that's a 2.4.x feature, the nether module is on hold, and the Still doesn't exist (no pun intended)

**Comment by Sunconure11** [comment]
I need to deal with some crap going on with a friend, so, I don't think I can do much (let's just say she needs... serious mental help). I'll make the texture for the ghost whenever possible. I'll try and just generate colors for fluids for now.

**Comment by IceDragon200** [comment]
@Ar97x https://github.com/Alatyami/Growthcraft-1.7/commit/aa99fd7739151b9615c6d2463065a8b76593b3e1

**Comment by Sunconure11** [comment]
Updated the page to include that.

**Comment by Sunconure11** [comment]
Does anyone have any ideas for growthcraft tundra, for when/if that is dealt with? I cannot think of many crops for that, if any at all.

**Comment by IceDragon200** [comment]
@Sunconure11 Fur Clothing?

I'd like to wear one of those big fluffy fur caps

**Comment by Sunconure11** [comment]
Fur items of some kind were thought of, but, I cannot think of many unique uses for it. Though fur would be nice.

**Comment by Sunconure11** [comment]
While neither the isopod or boar (well, the boar might) fit in any current concepts for modules, I was wondering if it might be possible to make these in the mod:

https://www.reddit.com/r/Minecraft/comments/3w0yqm/found_this_in_my_sketch_folder_kind_of_wish_i/

Look in the comments for the isopod.

**Comment by Sunconure11** [comment]
Since me and pitch had a brief discussion on how we might all be overwhelming the coders, why not some smaller, simple ideas? Watermelon wine? (fermented from watermelons)

**Comment by Sunconure11** [comment]
http://winemaking.jackkeller.net/watermel.asp

**Comment by Sunconure11** [comment]
http://www.wikihow.com/Make-Watermelon-Wine

**Comment by Sunconure11** [comment]
Still working with dairy a bit, but, I need a better list of materials for future tools.

Anyone got anything? This is my current list:

Vanilla materials, plus thaumium, voidsteel, manasteel, steel, silver, copper, bronze, electrum, ivory (if that makes it into snow), certus quartz, ender amethyst, ruby, sapphire, peridot, (list other mod materials here)

This is for mod support mainly

**Comment by Ar97x** [comment]
Shiny (Platinum)
Ferrous (Nickel)
Lead
Tin
Invar
Dark Steel
Unstable Ingot
Osmium

Those are all that I can remember

**Comment by Ar97x** [comment]
"Hey, could you possibly make Fishtraps upgradable with a magic fishing rod? Even if they consume the rods' durability when they catch things, it'd still make the traps a lot more fun and interactive." -Quote from Lord Eric.

**Comment by HanatakeYurii** [comment]
Hi,

I hope I will not throw a rock in a pool but I would have suggested lambics for the "Various new forms" of beers.
Lambics are produced by spontaneous fermentation (no yeasts are added in, they're exposed to wild yeasts and bacterias). They can be found in various kinds including for the most-known kriek lambic (refermented with sour cherries) and gueuze (blending young (1-year-old) and old (2- to 3-year-old) lambics, which is then bottled for a second fermentation).
They're common beers in Belgium and are of a really different taste than conventionnal beers.

I think it would not be so hard to add them since major fermenting mechanics already exist, and would add some variety with the use of other fruits like cherries.

Thanks for considering this ... and for your great work as well ^^

(PS: my second idea was to add fruit alcohols like sirups, and possibly make cocktails of them, but it's way more hazy in my mind)

**Comment by Sunconure11** [comment]
I think we can probably handle fruit alcohol in a future module. Maybe a small cherry tree module for what you are describing? What do you say, @IceDragon200 @PitchBright @Alatyami @Ar97x 

Plus we could finally do the cultivar system to an extent with a cherry tree module.

**Comment by Ar97x** [comment]
I don't know half of you guys do about booze, but I like the fruit alcohol
idea, giving the fruit presser more uses. And I got an idea for what
Hanatake suggested. As he said that lambics are fermented by nature course,
I think it could be out of the fermentation barrel step, and be fermented
by placing the liquid into a 2x2 hole, requiring 4 buckets to get it
started. The stages could be monitored by the colour of the drink (and
Waila), or something else we can figure out together.

**Comment by PitchBright** [comment]
What exactly does "Community Edition" mean anyway?

**Comment by Sunconure11** [comment]
Community Edition refers to the fact that this is a continuation done by several people, who have continued Gwafu's work in his or her absence.

**Comment by PitchBright** [comment]
Would be great if we had more people helping. I think we should make a new rule:

1) Each member of the community is allowed to submit one idea
2) Each member of the community is not allowed to submit a second idea, until they have either executed their first idea, or found somebody to execute it the code/art.

I feel like you guys spend more time day-dreaming and spit-balling ideas, rather than actually contributing to the "community edition". It makes for extra noise and headache for the two or three people who are actually actively working on stuff. I honestly don't think we need to "chef by committee" this puppy. What makes it worse is that 90% of the stuff being thrown out as "cool ideas" are total departures from Gwafu was creating. I don't know how many times/ways I have to say that.

I think another good rule would be… if you refer to it by its Latin name… then it shouldn't be in GrowthCraft.

Look at that first post? Who the fock is gonna make all that stuff? Let's get real here. All we're doing is making a giant list of stuff that makes this mod (and the work to be done on it by the few who are doing it) feel like a Mountain.

**Comment by Sunconure11** [comment]
This thread was created with the sole purpose of collecting as many ideas mentioned by players as possible. This is one of the oldest pages on here, and there is indeed a good chance little of this would be executed. I added all of this based on ideas from the thread and such at the time.

Also, your idea for how players should commit stuff sounds like a bad idea, though we do need more coders.

I did try to get some minor legwork done for these ideas though.

**Comment by PitchBright** [comment]
@Sunconure11 , please make a Wiki list of all the boozes that were submitted in this whole convo (not the stuff that you can't put in your mouth and swallow like Bamboo Ladders. Booze only.)

Then close this up. 

The Brew Kettle is fully configurable, it's extremely powerful and if anybody wants to make some obscure booze… they're more than welcome to. All they need to do is code it up and supply the art.

**Comment by PitchBright** [comment]
Then change the title to "General Discussion and Random Ideas"

**Comment by Sunconure11** [comment]
I'll try the stuff that won't require a distillery. I have not made the model for that as I cannot find a suitable design, some are shoddy, some are too big or too industrial, I need a design to fit in with Growthcraft.

**Comment by Sunconure11** [comment]
Im going to toss out a script here tomorrow with as much of the booze this has mentioned. It will be a modified config file, but, think of it as these ideas being executed without the dev needing to code it.

After that, I'll close this. These scripts might require a few mods though. Witchery (absinthe), and at least something with most major fruits come to mind.
