### ISSUE TITLE
Pipes, do you want?

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#103]
See #106 for details

**Comment by Ar97x** [comment]
Cool, I think it is really welcome, we don't need to be dependent to other
mods this way. Do you think about another functions for pipes? And will the
machines work with other tools, like TE and Ender IO ones?
Em 09/10/2015 18:46, "Corey Powell" notifications@github.com escreveu:

**Comment by Sunconure11** [comment]
Would it be possible to add an option to turn off pipes? That would be good for modpack devs.

**Comment by IceDragon200** [comment]
@Ar97x Currently I only check for IToolWrench (the buildcraft wrench interface) items, so if they use that interface then it will work, otherwise KABOOM, nothing :P

@Sunconure11 The entire module, or pipe pipes (as in their flow?), I working on adding redstone handling to the vacuum pipe, I had plans for a valve pipe, but completely forgot about it, thanks for the reminder :O

**Comment by spannerman79** [comment]
To keep the independence may I suggest that yes if Build Craft (or any mod that has a wrench) is detected a user can use a wrench but by default all that is needed is a stick to serve the function of a wrench

**Comment by Sunconure11** [comment]
Well, if its a module, then allow an option to turn them off until we are able to split them into modules again.

**Comment by IceDragon200** [comment]
@Sunconure11 Sure thing, I'll add a config option

@spannerman79 A stick, can it be an amazing stick? 

> adds a config option `Enable Amazing Stick - so, I heard you didn't have a wrench`

**Comment by spannerman79** [comment]
lol @ Amazing Stick. Yeah that can work. I was only thinking of a stick to;

1) Keep item ID's down and use vanilla items. Highly unlikely that a stick would change minecraft wise

2) Most other mods I've come across will auto fallback to a vanilla item when item X from mod/s Y cannot be found

If all your doing is adding lore NBT data on use of stick then ignore this entire comment :P

**Comment by IceDragon200** [comment]
@Sunconure11 https://github.com/alatyami/Growthcraft-1.7/commit/a334ca35e8f05205cba4904bfd625ed6bb7d7601 Config option

@spannerman79 https://github.com/alatyami/Growthcraft-1.7/commit/67e35283c9d52d3f8e112b3e7e708b6e4671435b The Amazing Stick, nuff said

Thus begins the pinnacle of awesome

**Comment by tehFoxx0rz** [comment]
It'd be great if they could look a little more historical/"simple" to fit in with the aesthetics of the rest of the mod (maybe terracotta coloured and a little weathered?), but that's mostly a texturing thing, and they don't look vastly out of place as they are, just a little "abstract techy" aesthetic-wise, like EnderIO or Factorization things.  Seems like a good idea though, and would be great for smaller or more magic-based modpacks which lack simple fluid transport!

**Comment by Alatyami** [comment]
I agree ... in most brewing you have copper based pipes. But maybe we could
use clay to make a terracotta pipe?

**Comment by IceDragon200** [comment]
Will split this module into its own project later down the road.

**Comment by Alatyami** [comment]
Might as well focus it to 1.8. As there are more and more mods finally
moving to 1.8.

Alatyami
