### ISSUE TITLE
Right-Click Apple Block that is green makes it disappear

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#111]
Version: 2.3.0

Quote from vincentvan >>
There is a bug with apple block. When right click on it disappears (if it isn't red). And i can use bone meal on it.

**Comment by IceDragon200** [comment]
I'll add this to ~~#110~~ scratch that, the fix has been pushed to development, lets find a few more bugs to fix for a later release

I fixed the right clicking breaking non-red apples, however to you must sneak and right click to use bonemeal

**Comment by IceDragon200** [comment]
Should be resolved by https://github.com/Alatyami/Growthcraft-1.7/commit/dbba33e9c062cc14fd31cee637f7f44f045d2a76
