### ISSUE TITLE
Fix for Travis-CI Deployment for Multiple Files

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#113]
https://gist.github.com/IceDragon200/cd4d52066dea302d83b9

**Comment by IceDragon200** [comment]
@Alatyami I've added it to my core-dev branch, as well as jar splitting

**Comment by Alatyami** [comment]
Nice.

**Comment by IceDragon200** [comment]
@Alatyami https://travis-ci.org/Alatyami/Growthcraft-1.7/builds/84995073 I WIN :dancer:

**Comment by Alatyami** [comment]
Nice!
