### ISSUE TITLE
request: plz make bamboo fence mate with vanilla fences

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#116]
just that. seems bamboo  fence cannot be used together with vanilla one a gap is formed between. is kinda like nether fence and vanilla fence issue .

**Comment by IceDragon200** [comment]
Its on the todo, related #73

**Comment by IceDragon200** [comment]
@trollworkout Well, can't fix this, fence blocks are hard coded on minecraft's side of things, the most I can do is have our fences extend "as if" connecting, but minecraft won't respond back, its like proposing to the girl of your dreams only to be left hanging.

**Comment by ghost** [comment]
@IceDragon200  there is a mod called et futurum ganymedes added new fences and they all work with vanilla fences fine.  

see here.   you need to use a special connect to fence event and make sure ur fence extends block fence.
https://github.com/ganymedes01/Et-Futurum/blob/master/src/main/java/ganymedes01/etfuturum/blocks/BlockWoodFence.java

they work . i tested it. i m playing with it. all fences from his mod work with vanilla fence renamed to oak by me using modtweaker 3. 
![screen shot 2015-10-19 at 4 03 31 pm](https://cloud.githubusercontent.com/assets/6987027/10589792/32e7a8aa-767b-11e5-90fc-dbfe622605ec.png)

proof see attached image

**Comment by ghost** [comment]
@ganymedes01 not sure if i can do this but ask him how he did it

**Comment by IceDragon200** [comment]
@trollworkout He overwrote the vanilla oak fence and replaced it with his BlockWoodFence, which is why they all connect

[The Pudding](https://github.com/ganymedes01/Et-Futurum/blob/8a201e59eef4e115fd8ef938d46f745361ae7376/src/main/java/ganymedes01/etfuturum/recipes/ModRecipes.java#L48-L53)

**Comment by buttilda** [comment]
Yup that's how I did it. Not sure if there's any other way to do it

**Comment by ghost** [comment]
@ganymedes01  @IceDragon200  i get it . ah well :D i actually removed et futurum oak fence and enabled vanilla instead cause but renamed it was still showing up in the game as village structures or from mods or in recipes.  too bad ;p
