### ISSUE TITLE
request: please add more life to bees  

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#117]
bees are just an icon in a box. pretty much. see mosquito swarm from twilight forest. bees could be a block of swarming little particles that move from flower to flower or attack if you are too close to the hive. if you "kill" the bee swarm a bee icon drops then that's pretty much normal . also the bees might leave the bee box to go to flowers then come back. so once in a while you will see a swarm of bees and the bee icon is greyed out and cannot be grabbed cause bees are out :)

**Comment by ghost** [comment]
optionally when attacking or grabbing a bee hive a bunch of bees will attack you. you can fight off the bees or run away then at home you can convert the bee hive into a bee box by incorporating the hive into the recipe. when you look inside the bee box you will see a greyed out bee icon . the bee box can be moved or stored but the bees will always be inside the box and  "haunt" the area where the bee box is kept. by haunt i mean once in a while they leave and roam looking for flowers.

**Comment by ghost** [comment]
i was thinking getting the hive is a bit more dangerous swarm of bees attack whoever is closest but once taken then is just whatever u guys have is fine. maybe the swarm comes out and goes from flowers next too bee box once in a while that's it.

**Comment by tehFoxx0rz** [comment]
It'd be nice if at least they had a little particle animation like Forestry's bees (though different in substance) at least.  I think if they inflict damage it should be only when you're breaking their natural hive blocks.

**Comment by PitchBright** [comment]
I'm planning on writing a design doc for the Bee Module that should cover some of your concerns here. That will be a "future thing". I think we're in agreement that Bees has some potential for some expansion of features, but at the same time, the goal is not to recreate Forestry. For that reason, let's close this down, and revisit it at the appropriate time. Consider the request noted, and appreciated. :-)

**Comment by IceDragon200** [comment]
In the future all design related documents should be pushed to https://github.com/GrowthcraftCE/Growthcraft-DesignDocs
