### ISSUE TITLE
Icons for Wikia

### ISSUE THREAD

**Issue by Ar97x** [GrowthcraftCE/Growthcraft-1.7#119]
As previously said, there's this guy that is trying to make a GC Wikia page. He asked for some icons to help him to use the crafting gui, so I created this issue to ask the contributors what do you think we should do about it. Give him the icons, help him with the pages or redirect him to work on the wikis we already have, like FTB and this local one?
EDIT: Idk how this assign thing works, that's why it is so messy below this message.

**Comment by IceDragon200** [comment]
@Ar97x Assign is "this person is in charge of this issue", if you want to ping someone add an @ in front of their name.

As for the issue, if someone wants to do the renders for the blocks, then I see no problem in giving him the icons (its an open source project now :O)

**Comment by IceDragon200** [comment]
@Ar97x Here you are [Icons](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/res/GrowthcraftIcons_2.3.1-46086f4.zip), I exported them using NEI, comes in all the sizes offered by NEI EXCEPT 48x48

This based off the current development HEAD

**Comment by Ar97x** [comment]
Thanks, I'll send this to the guy tonight.

**Comment by Ar97x** [comment]
Closed #119
