### ISSUE TITLE
Modpack Permission

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#120]
Hi.

I'm letting you know that I will be using Growthcraft in Complexity (a new modpack coming to Technic Launcher).

Mod/permission list here :
https://docs.google.com/spreadsheets/d/1yExCzGrqqdEXioG_94wx7h4M9PxfQ6-ZV6C8Vmntb70/edit#gid=0

**Comment by Alatyami** [comment]
Thank you for letting us know. If you find any compatibility issues please let us know.

Inclusion of Growthcraft CE in your modpack is automatically approved.
