### ISSUE TITLE
bug: growthcraft seems to crash with an erebus water bambucket 

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#122]
very niche thing this bambucket  and is disabled in my mod since i cant use it for anything but i m thinking or reporting this bug since it may be from your side and may help smooth out the code

water bambucket + empty growthcraft barrel

see here
http://pastebin.com/F3sEfgzW

**Comment by IceDragon200** [comment]
@trollworkout That's pretty weird, I have no idea whats going on there, but try this [Latest dev Build](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete_development-build0.jar)

**Comment by IceDragon200** [comment]
@trollworkout Can you reproduce this in a pure growthcraft environment?

**Comment by ghost** [comment]
@IceDragon200  ill go growthcraft + erebus only with that new water bottle build. i ll see if it still does it.

**Comment by ghost** [comment]
@IceDragon200  still does it

erebus + growthcraft only..no other mod 
see for yourself: http://pastebin.com/6sWpGKz5

**Comment by IceDragon200** [comment]
@trollworkout  Try this [Build-e107cb0](https://dl.dropboxusercontent.com/u/72618186/minecraft/mods/growthcraft/2.3.1/growthcraft-1.7.10-2.3.1-complete--e107cb0.jar)

**Comment by ghost** [comment]
@IceDragon200  fixed. you can close this. thank you very much :)

**Comment by ghost** [comment]
:+1:
