### ISSUE TITLE
Bee boxes using modded wood

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#124]
Since we are making variants of the bee box using vanilla woods, would it be possible to add variants for modded wood?

**Comment by IceDragon200** [comment]
o_o The thing is, there is a CRAP TON OF THEM

I'd make it an external mod for each Natura, Forestry, etc..

there are just so many of them :O

**Comment by ghost** [comment]
haha  sooooooo many woods

can u make it so u can scan trough all plank ore and apply the texture for that plank to a bee box. instead of premade ones generate the ones you are missing.

theres a ton of them! at least 100 different planks.

**Comment by ghost** [comment]
i'd say dont even bother :) let someone else add an addon using the api if they really want to, just default to oak for anything u don't have.

**Comment by Ar97x** [comment]
I say that we should add the ones from the mods we already have an api or
some sort of compatibility.

**Comment by ghost** [comment]
@Ar97x  u got thaum api so do the greatwood and silverwood for starter
then maybe BOP . seems a lot of people also play forestry , and biomes xl and highlands i think.

**Comment by Ar97x** [comment]
We have an api for forestry too I think, so we should make the variants
from its infinite types of woods. And I don't work with code, I'm just
suggesting.

**Comment by ghost** [comment]
@Ar97x  i deff recommend biomes of plenty as there are "plenty' of people using it.  get it .ok ok. i leave now haha by that extent making barrels from different woods may be also an interesting project. maybe even different woods affect the fermentation speed?

**Comment by Ar97x** [comment]
@trollworkout this seems really nice, different barrels with it's own
properties.

**Comment by ghost** [comment]
@Ar97x  in real life you can get different flavours for your brew depending on what wood you use . maybe im thinking you can generate special brews with extended lengths or custom nbt tags based on what kind of wood you made your barrel from. like flavours. for ex wine is best in oak. so if you use oak you can get aged wine maybe dunno. just a thought. 

young wine, fermented aged wine, fermented aged wine extended. is just a custom nbt tag when you bottle your brew with custom name that's it. not a new item.

**Comment by Sunconure11** [comment]
What about a bee box using bamboo from this mod? We are adding malice wood boxes.

**Comment by IceDragon200** [comment]
@Sunconure11 Good point, I'll whip up the textures

**Comment by IceDragon200** [comment]
So, shameless self plugging https://github.com/IceDragon200/GrowthcraftExtOak

I started a extensionn mod which adds the Forestry Bee Boxes (they require some "special" recipes to craft correctly)

**Comment by tehFoxx0rz** [comment]
On top of this, it'd be great if the rope could work with modded fences.  Especially Woodstuff.

**Comment by IceDragon200** [comment]
Well we have some of the bee boxes in place, mostly the vanilla variants, so I'll close this issue, regarding fences, there is another issue for that already.
