### ISSUE TITLE
Question about Bamboo

### ISSUE THREAD

**Issue by vadis365** [GrowthcraftCE/Growthcraft-1.7#125]
Hello,
I work on the Erebus mod, we are tweaking a few things atm for cross-mod compatibility.
We would like to make our bamboo interchange with Growthcraft bamboo in recipes etc.
Could you tell me if you register Growthcraft bamboo in the oreDict and if so under what name?
I could poke about in your repo looking for it - but I thought I would ask directly :)
Cheers,
Me.

**Comment by spannerman79** [comment]
The only oredict that shows is;
`woodPlank` or `plankWood`
http://i.imgur.com/Q9ENtve.png

Edit: Its easy to find the rest https://github.com/Alatyami/Growthcraft-1.7/blob/development/src/java/growthcraft/bamboo/GrowthCraftBamboo.java#L196

**Comment by vadis365** [comment]
Thanks. Will register our bamboo to be compatible with this. The food item doesn't conform to oreDict standards though...
OreDictionary.registerOre("cropBambooshoot", bambooShootFood.getItem());
OreDictionary.registerOre("listAllveggie", bambooShootFood.getItem());
usually its foodXXXXX as in 
OreDictionary.registerOre("foodMushroom", new ItemStack(Blocks.red_mushroom))

*Edit I can always register it as both ;)

**Comment by IceDragon200** [comment]
@vadis365 We inherited those, I'll update/add all the oreDict names according to the standard, TO THE BEST OF ABILITIES! 

Those ones that you listed are for compat with Harvest Craft, I dunno if they changed it, I can't find the source to peek at orz

**Comment by vadis365** [comment]
Cool - thanks for the reply. Looks like there the 'standards' are actually just common names - my bad.
http://www.minecraftforge.net/wiki/Common_Oredict_names

**Comment by IceDragon200** [comment]
@vadis365 https://github.com/Alatyami/Growthcraft-1.7/blob/8a2745e4d6ebbbdc6704220c38c9541b961b05f2/src/java/growthcraft/bamboo/GrowthCraftBamboo.java#L213-L245

Here are the updated names: comes in 2 variants, vanilla compat and bamboo specific

**Comment by vadis365** [comment]
Awesome - I'll update our oreDict names tonight (U.K.) to make it all good - thanks again for your time :)

**Comment by ghost** [comment]
:yellow_heart:
