### ISSUE TITLE
Drinking pouch and brewers bag

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#126]
drinking pouch = a re-usable leather bag item that can hold up to 5 doses of any 1 type of brew
each use after 1st one increases the chance of tipsy by 10% (60%, 70%, 80%, 90%, and last gulp is guaranteed tipsy). this is calculated based on how much alcohol is left. u could cheat around it by refilling it after each 1 drink. the idea is to make an useful item for adventuring but not without drawbacks. cannot stack. to load it u right click [with it] on a barrel and it fills up based on how much  space it has left and on what is available in the barrel. you cannot mix drinks. shift+right click+hold and release to discard all content.  

crafting
null, rope, null
leather, glass bottle, leather

like this https://img1.etsystatic.com/019/0/6784727/il_570xN.479797045_rj8w.jpg

brewers bag = this item has it's own inventory of 4 slots which can only contain stacks of brew bottles or certain growthcraft items (yeast). to access the inventory you hold it in you hand and right click. 

crafting
leather, leather, leather
leather, rope, leather
leather, leather, leather

http://goodhouseguest.com/wp-content/uploads/2012/06/backpack.jpg

making it out of rope limits the availability early game until u get a lead and also guarantees the recipe is will never conflict with any other mod  (growthcraft only rope)

if you like the idea i can make the art for it.

**Comment by Ar97x** [comment]
This is really cool, I think this mod needs something like this. But we
could have a metal variant for the pouch, that holds up to 8 or 10 doses of
the drink. Do you have any parameter of how much a dose would restore for
hunger? A bottle worth?

**Comment by ghost** [comment]
this mod is really cool and all is missing is some little campy things like wearables , collectibles , decorations or accessories  that players can use to really get into the brewing growing farming mode. like wear your brewers hat, get your farmers coat  and your brewing bag and so forth. just little details to enhance the mod "flavour" and "feel"

**Comment by Sunconure11** [comment]
I think I'll make the waterskin more oval shaped.

http://battle-ready.com/home/wp-content/uploads/bladder-small-dark-brown-round-1.jpg

**Comment by ghost** [comment]
@Sunconure11  sounds great :)

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/7ejywmngtgzu3hv/Screenshot%202015-10-31%2019.39.55.png?dl=0

what am i even doing

**Comment by Sunconure11** [comment]
And that is what pretty much every texture looks like when I first start them. However, I feel like it already looks awkward. Any advice?

**Comment by ghost** [comment]
@Sunconure11  take the image you have and shrink it down then  draw on top of it in a new later make it nicer and smoother

**Comment by IceDragon200** [comment]
@trollworkout @Sunconure11 I gave it a shot, did what trollworkout said, also Pixel art [Tutorial](http://cyangmou.deviantart.com/art/Pixel-Art-Process-413418385)

Normal, 4x, 8x, and 16x respectively
![Water Bag](https://dl.dropboxusercontent.com/u/72618186/pictures/pixelz/minecraft/Growthcraft/WaterBag.png)![Water Bag 4x](https://dl.dropboxusercontent.com/u/72618186/pictures/pixelz/minecraft/Growthcraft/WaterBag_4x.png)![Water Bag 8x](https://dl.dropboxusercontent.com/u/72618186/pictures/pixelz/minecraft/Growthcraft/WaterBag_8x.png)![Water Bag 16x](https://dl.dropboxusercontent.com/u/72618186/pictures/pixelz/minecraft/Growthcraft/WaterBag_16x.png)

The colors could do with some tweaking, but hey :sweat_smile: it works

**Comment by Ar97x** [comment]
That shape is really nice. But like you said, it could use some new colors.
We can make them paintable, too. I think as the main color you can make it
nude, almost sand color.

**Comment by ghost** [comment]
@IceDragon200  looks great i love the color actually. you could try lighter but i think it looks fantastic :))

**Comment by Sunconure11** [comment]
I think that might work better than my attempt at one. However, I was wondering, would it be possible to create a small window on it so that it shows the fluid inside?

**Comment by Sunconure11** [comment]
Also, why not make the bottom a bit darker?

**Comment by IceDragon200** [comment]
@Ar97x, @trollworkout, @Sunconure11 I played around with the contrast, you can see the new texture in the development, I've commited all the textures (colors, you can tweak them as you see fit) and uploaded the latest build

Check https://github.com/Alatyami/Growthcraft-1.7/issues/130, for details and a disclaimer

Now to enjoy the few hours left of my birthday :birthday:

**Comment by Sunconure11** [comment]
I think they look good enough at the moment.

As for the still, I keep forgetting about, and making block models isn't really my forte. I have no clue where to start on it. I'm more used to modelling mobs. Anyone else want to take a gander at it?

**Comment by IceDragon200** [comment]
@Sunconure11 Guess I could give it a shot, I still need to add the Fermenting jar

**Comment by Sunconure11** [comment]
I thought of a way to remove color from pouches if they have been dyed. Why not make them like leather armor, and simply dunking them in a cauldron removes them of color, at the cost of some water.

**Comment by ghost** [comment]
@IceDragon200  Hey I know this is not on your plate right now but just posting it out there for future.

I suggest adding a damage bar to the Water Bag that shows how much liquid it has inside.

**Comment by IceDragon200** [comment]
@trollworkout Marked it down on my todo list

**Comment by ghost** [comment]
@IceDragon200 you can probably close this one since is implemented and quite functional as of latest build. All i request is that damage bar so I can quickly see how filled up it is but that's pretty much it.

**Comment by ghost** [comment]
@IceDragon200  EDIT: in fact I have been using the release build and I am quite pleased and happy with the result and I use the water bag quite often. Very very nice addition as well as the yeast and the other special brews perfect. So much better.

**Comment by IceDragon200** [comment]
Poke, the water bag was added, however the brewers bag wasn't.

There are plenty of mods out there that add a reusable backpack, (BetterStorage comes to mind).
We I think we should drop the brewers bag idea for now unless someone can come up with a VERY GOOD reason why we need a bag.

@trollworkout @Ar97x @Sunconure11

**Comment by ghost** [comment]
@IceDragon200  is all good thank you for adding it very useful :+1:  from my end you are free to close this if you wish. let's see what everyone else has to say.

**Comment by Alatyami** [comment]
Agreed, lets not reinvent someone else's wheel.

Alatyami

**Comment by Sunconure11** [comment]
Maybe when we get to a point where players would be accruing large amounts of specific types of items as a result of future modules (certain meats? varieties of fur? various new seeds? more microbes to culture?), we could add a bag.
