### ISSUE TITLE
Modpack Addition to ProjectRETv8

### ISSUE THREAD

**Issue by BakermanLP** [GrowthcraftCE/Growthcraft-1.7#127]
Hello, 
I want to include the Growthcraft Community Edition Mod in our new Modpack "ProjectRETv8". The complete list of mods can be seen here:
https://github.com/BakermanLP/ProjectRETv8/blob/master/versions.md

Thank you for taking over the mod! I like it!

Michael (aka BakermanLP)

**Comment by IceDragon200** [comment]
@Alatyami PING

Where do we store the list of mod packs using Growthcraft?
I'd handle this in your place, but I have no idea where to note this down.

**Comment by spannerman79** [comment]
@IceDragon200 I assumed it was in the README.md - perhaps creating a seperate file with the filename of `Permissive_Modpacks.md` or something to that effect.

**Comment by IceDragon200** [comment]
@spannerman79 @BakermanLP [Modpacks with Growthcraft](https://github.com/Alatyami/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft)

I hope I got all of them :sob:

**Comment by spannerman79** [comment]
Yes you did @IceDragon200 

[All tagged modpack issues](https://github.com/Alatyami/Growthcraft-1.7/issues?utf8=%E2%9C%93&q=label%3Amodpack+) currently show (at the moment) 8 issues and you have 8 listings

:+1:

**Comment by IceDragon200** [comment]
@BakermanLP You are granted permission to include Growthcraft in your modpack.

If you have any issues, don't be afraid to report them
