### ISSUE TITLE
Thaumcraft 5 support (eventually)

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#128]
~~o_o; I just an email that the Growthcraft build was failing to my surprise, the old Thaumcraft 4 api has taken a hike, replaced by 5.~~

~~I've opened an issue to see if we can get the old api repo back for now, that or I'll be copying the 4.x API into growthcraft against everyone's advice.~~

Issue was resolved https://github.com/Azanor/thaumcraft-5-api/issues/2

Anyway, this will be a 3.x milestone.

**Comment by spannerman79** [comment]
Well technically it's not a good idea to include an API into a mod directly as it can change, but in this case you can add the Thaumcraft API files directly in just as long as you state in the releases and in the file information over on curse forge that the particular release is only used with Thaumcraft 4.x and minecraft 1.7.10

**Comment by IceDragon200** [comment]
@spannerman79 I forgot to update the post, the 4.x api was restored

**Comment by spannerman79** [comment]
Make sure this change (Thaumcraft 5 API) is specific to the 1.8 branch

**Comment by Alatyami** [comment]
I am going to move this to the Growthcraft-1.8 repo.

**Comment by IceDragon200** [comment]
Since we have a 1.8 repo, this issue is no longer valid here.
