### ISSUE TITLE
Feature Request: Configgable Fruit Press Yield

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#132]
Would be sweet if we could change the amount of Cider Fluid Units per Apple. Each apple gives me 40 units, and each bottle holds 333 units. That works out to around 8 apples per bottle of cider. Personally, I'd really like to be able to change it, as needed… and have greater control over it.

Thanks!

**Comment by IceDragon200** [comment]
@PitchBright https://github.com/Alatyami/Growthcraft-1.7/commit/949c62787d686496176439dc6f5b5845ccdea821

You can't configure the fruit press residue yet (as that part of the code is still WIP)

**Comment by PitchBright** [comment]
Dude! Did you just add that feature? And if so, where can I get a jar to test and confirm everything is tickity-boo?

**Comment by IceDragon200** [comment]
@PitchBright #130 features all the current builds

**Comment by PitchBright** [comment]
I can never figure out where you guys keep those builds :(

**Comment by PitchBright** [comment]
Works awesome! Thanks for doing that. That one little feature makes a huge difference. I'm gonna try and get it up on the server tonight.

**Comment by PitchBright** [comment]
Incidentally… and somewhat related, with the apple growth rate settings:

```
# [Higher -> Slower]; Default : 8
I:"Apple growth rate"=8
```

What does the 8 represent? Is it that same weirdness as with the rarity in the previous issue I reported #56 a month or so ago…. or the math different there.

I'm curious because I'd like to make apples take X number of minecraft days to mature. I probably have some math stuff to figure out?

(I can open a different issue if you prefer I would keep it strictly on-topic here, just let me know.)

**Comment by IceDragon200** [comment]
@PitchBright Its a rarity value, one day, ONE DAY I'll unify all of the values into something that makes sense.

The math behind that is `rand(value) == 0`, so you have a 1/8 chance, per "random tick" (note random tick, minecraft will call the block to update at some point, only god knows when though), for the apple to advance 1 stage.
[Reference Line](https://github.com/Alatyami/Growthcraft-1.7/blob/development/src/java/growthcraft/apples/common/block/BlockApple.java#L124)

**Comment by PitchBright** [comment]
Thanks Ice!
