### ISSUE TITLE
Dairy Module

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#142]
I looked up fermented milk beverages out of boredom, and found this:

https://en.wikipedia.org/wiki/Kefir

Do you think we could place this in the mod somewhere? Maybe fermenting milk with any yeast creates it. However, it is not alcoholic, if we want something alcoholic, maybe we could use this instead:

https://en.wikipedia.org/wiki/Kumis

**Comment by IceDragon200** [comment]
@Sunconure11 Seems doable, what sort of effect would it have?
Also this means I'd we'd need to add an actual Milk fluid (Forestry has one, so we'll need to be careful not to break other mods with the addition)

**Comment by Sunconure11** [comment]
What if it clears all negative debuffs (except for tipsy) like how milk does, and inflicts absorption?

**Comment by Ar97x** [comment]
This could give a new path to Cellar Module, milk fermentation, and lead to
a new module, incrementing cool stuff like cheese producing and other food
related stuff. Good call.

**Comment by IceDragon200** [comment]
@Sunconure11 @Ar97x On my computer it **is** a new module **grcdairy** to be exact, I was thinking about adding [butter churn](http://antiqueshopsinmichigan.com/images/antique_items/1825_butter_churn.jpg) as well

**Comment by Sunconure11** [comment]
And I already started a wiki page on said module.

https://github.com/Alatyami/Growthcraft-1.7/wiki/Growthcraft-Dairy-(Concept)

**Comment by ghost** [comment]
@IceDragon200  @Sunconure11  wow awesome!

For status effect I am thinking it should clear all effects except for tipsy then add tipsy. So if you mix it with other drinks you can get super drunk. Milk would remove all effects including tipsy however should be same.

**Comment by Sunconure11** [comment]
I feel well rested enough that I might start on a model for the dairy module. WATER BUFFALO!

**Comment by Sunconure11** [comment]
Water buffalo milk is whats used in mozzarella cheese, BTW.

**Comment by Sunconure11** [comment]
And Kumis, the beverage, is made from horse milk.

**Comment by Sunconure11** [comment]
Yeah this is going to take a bit. Mainly because of those horns. But I'll try to make sure this actually gets done, unlike the distillery. >:U

Also @IceDragon200 you might want to look at the nether module page. I posted some textures and such.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/f41dgcy1l617arg/Screenshot%202015-11-22%2010.42.58.png?dl=0

**Comment by Sunconure11** [comment]
Working on the water buffalo, bit by bit.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/x0rwz8fcv5ugqsx/Screenshot%202015-11-23%2017.00.39.png?dl=0

This is what happens when I model without references because the internet blew out for a bit.

**Comment by PitchBright** [comment]
I wanted to chip in, and contribute, since @IceDragon200 and you guys have been so good (and quick) about implementing features, configurables, fixes and tweaks for me. I hope this does the trick, I did my best to honour Gwafu's style.

http://imgur.com/nnhp9kd

If that's approved, let me know what sizes and formats you need versions of it, and I'll prep a zip of 'em for ya.

**Comment by spannerman79** [comment]
If you need a vote @PitchBright :+1:

**Comment by Sunconure11** [comment]
That looks just like Gwafu's style. That can probably work.

**Comment by Sunconure11** [comment]
I'm going to fix up the water buffalo tomorrow, but, I won't texture it until later. Body is mostly finished, but, needs heavy tweaking as I lacked proper references due to the fact that the internet went out for part of the day.

**Comment by Alatyami** [comment]
Awesome

**Comment by IceDragon200** [comment]
@PitchBright  :+1:

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/hngme4tqdhyvbrh/Screenshot%202015-11-24%2014.45.15.png?dl=0

I reworked the water buffalo model a bit. I'll do details such as the muzzle, tail, and horns later. Then the textures will follow suit. Unless anyone else wants to texture it.

**Comment by Sunconure11** [comment]
Also, if milk from other animals (i.e horse, water buffalo, and possibly other animals) are treated as separate fluids, should they behave any differently from cow milk, aside from certain cheeses and beverages they can be made into?

**Comment by Alatyami** [comment]
Would "milking" a water buffalo result in a Bucket of Water? :)

~alatyami

**Comment by Sunconure11** [comment]
OH

**Comment by PitchBright** [comment]
@Alatyami LOL

**Comment by PitchBright** [comment]
@IceDragon200 @Sunconure11 @Alatyami Can you guys grab this zip for GC_Dairy from my drop box? It's the GC_Dairy logo, in vector Adobe Illustrator format, and TIFF, JPG & PNG as well… and they can be resized to suit any application. Hopefully that's enough cuts of the logo that you can open it and do what you need to do with it (wiki, manual, website, etc).

If there's an asset repository for GC stuff like this, stick it in there I guess. I think it's best that you guys have these files, just incase I get hit by a bus, or whatever-type scenario. 

https://www.dropbox.com/s/92i4zdcn34cdj73/GC_Dairy%20Final.zip?dl=1

Also, please let me know when you've got the file, so I can remove it from my nearly-full dropbox :-)

**Comment by ghost** [comment]
wait. is is water buffalo made out of water? :))

**Comment by spannerman79** [comment]
> Would "milking" a water buffalo result in a Bucket of Water? :)

ffs lol .... really? 

On a more serious note though milk from the buffalo used to make the base material for cheese but needing a different type of material in order to make it mature. Perhaps rotten flesh makes Blue Vein Cheese, etc

**Comment by Sunconure11** [comment]
I'm going to hold off continuing the water buffalo model until Friday.

**Comment by Sunconure11** [comment]
Also one cheese type I thought of for creating using water buffalo milk was mozzarella, as some forms of mozzarella come from water buffalo milk.

**Comment by Sunconure11** [comment]
https://en.wikipedia.org/wiki/Buffalo_mozzarella

**Comment by Sunconure11** [comment]
Also I thought of some form of cheese created with the entomophagy module if that ever goes anywhere.

https://en.wikipedia.org/wiki/Casu_marzu

hue

**Comment by Ar97x** [comment]
I just love Buffalo Mozzarella. I would farm Water Buffalos just to eat it
every day.

**Comment by Sunconure11** [comment]
Also, seeing as using certain ingredients to define certain cheeses was suggested, I'll put some forward:

Gorgonzola (type of Blue Vein): Cow's Milk, Rotten Flesh, Rennet, Starter Culture

Roquefort: Sheep Milk, Rotten Flesh, Starter Culture, Rennet

Cheddar: Cow's Milk, Orange Dye, Rennet, Starter Culture

Mozarella: Buffalo Milk, White Dye, Rennet, Starter Culture

**Comment by spannerman79** [comment]
> Rennet

Obtained via;
- Mob drops (specific killing pig (15-20% drop), cow (50% drop), _maybe_ chicken(1-5% drop))
- Cauldron recipe - Boil 2 x leather with 1 x gunpowder (powdered acid)

**Comment by IceDragon200** [comment]
@Sunconure11 @Ar97x @spannerman79 @trollworkout @PitchBright @Alatyami How do you guys want your cheese, Cheese Items and or Cheese blocks (like cake (not a lie))?

**Comment by Sunconure11** [comment]
Cheese items and blocks. Cheese blocks can placed like cake, and eaten, or picked up, and sliced into 9 slices.

**Comment by Sunconure11** [comment]
Also, vegetable rennet is a thing, maybe that could be added as well. https://en.wikipedia.org/wiki/Rennet#Vegetable_rennet

**Comment by spannerman79** [comment]
The cake is a lie :stuck_out_tongue: 

But yes like cake, different texture

Damnit ninja'd by @Sunconure11

**Comment by Ar97x** [comment]
It could be like melons, but cake sized. If we break it, it'll be separated
into 9 cheese slices, and if we put them all together in the crafting grid
it becomes a block.

**Comment by spannerman79** [comment]
My suggestion about Rennet was based on rough stomach sizes for vanilla minecraft animals. Cow has three stomachs hence higher drop rate

Rennet source normally from cow stomachs anyway

**Comment by Sunconure11** [comment]
Yeah, that can work. But I think having vegetable rennet on the table would work as well, in case players cannot find cows.

**Comment by spannerman79** [comment]
> Yeah, that can work. But I think having vegetable rennet on the table would work as well, in case players cannot find cows.

Thats why I also suggested 

> Cauldron recipe - Boil 2 x leather with 1 x gunpowder (powdered acid)

**Comment by IceDragon200** [comment]
@Sunconure11, @spannerman79 or if your offended by kiling cows/animals in general (feels the guilt of all those sheep who paid the price for their wool...)

**Comment by spannerman79** [comment]
lol @IceDragon200 well _usually_ on most servers - either by mod or minetweaker  2x (or more) rotten flesh in furnace becomes 1x Leather so no need to kill animals - just zombies :stuck_out_tongue:

**Comment by Sunconure11** [comment]
I found a suitable source of vegetable rennet for this mod. Thistles.

**Comment by Sunconure11** [comment]
http://www.ehow.com/how_5728718_make-thistle-flower-rennet.html

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=thistle+rennet

**Comment by Ar97x** [comment]
https://en.m.wikipedia.org/wiki/Queijo_coalho as we are talking about
rennet, we could make this little something from my country :D

**Comment by Sunconure11** [comment]
Queijo coalho: Any milk, two rennet, white dye

**Comment by Ar97x** [comment]
With a stick and put it into the furnace!

**Comment by Sunconure11** [comment]
That could work too.

**Comment by Sunconure11** [comment]
Maybe I'll move goats to this module instead of butcher, and give them more features in butcher.

Pepper Jack Cheese: Cow's Milk, Rennet, Peppers (chili or ghost), Red Dye, Starter Culture

Emmentaler: Cow's Milk, Wheat, Rennet, White Dye, Starter Culture

Queso: Cow or Goat's Milk, Blaze Powder, White Dye, Whey

Cottage Cheese: Can be created by stopping the production of cheese in the curdling process, and then adding white dye.

Cheese Curds: Can be created by stopping the production of cheese in the curdling process.

Appenzeller: Cow's Milk, Wine or Cider, Any Spice, Rennet, Starter Culture

Asiago: Cow's Milk, Rennet, White Dye, Yellow Dye, Starter Culture

**Comment by Sunconure11** [comment]
Also, this list could be useful. Very useful.

https://en.wikipedia.org/wiki/List_of_cheeses

**Comment by Sunconure11** [comment]
I'm going to finish up most of the water buffalo body today, and then do the horns tomorrow. Heads up, if anyone wants to texture it when I am finished, let me know. Otherwise, I'll do it.

**Comment by Sunconure11** [comment]
Also, I wrote a bit more in the dairy, desert, and nether module pages. What should be the big thing for the desert module? A lot of these modules have at least one major, interesting mechanic. The only mechanics I could think of for the desert module are two tameable mobs (American Cheetahs and Shasta Ground Sloths), and oil lamps. I thought of some crops but no overly radical mechanics. Any ideas? I feel like the nether module should also have an interesting mechanic as well, aside from netherrash.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/at3ywc6bhyzoj36/Screenshot%202015-11-26%2022.43.07.png?dl=0

A muzzle looks weird on this model. I'll probably also create a variant with two chests, as in the dairy module, I wanted them to be usable as pack animals.

**Comment by Sunconure11** [comment]
I waaaaaaaaaaay overslept today. I'll finish the buffalo tomorrow.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/qrqtmmbpph202et/Screenshot%202015-11-28%2015.22.11.png?dl=0 Working on it.

**Comment by Sunconure11** [comment]
Well I finished the horns. I'll set up the texture map, and then start texturing it.

**Comment by Sunconure11** [comment]
I'll work on naming each part tomorrow, and then start the texture map. After I make the texture map, I'll make a variant with chests.

**Comment by Sunconure11** [comment]
I think I managed to screw up my sleep schedule slightly. I'll send over some miscellaneous textures I've made in the past that would fit here though.

**Comment by Sunconure11** [comment]
They will be ordered by various biomes they could fit in, assuming modules around them are ever made.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/la71qaxjqiprl6y/growthmisctextures.zip?dl=0

**Comment by Sunconure11** [comment]
Body parts for the water buffalo have been named.

**Comment by Sunconure11** [comment]
I'll set up the texture map for the water buffalo today. Last call, does anyone else want to texture it before I do?

**Comment by Sunconure11** [comment]
Texture map is finished.

**Comment by Sunconure11** [comment]
If no one else makes an offer to texture it (sorry if this sounds lazy or anything) by the weekend, I'll texture it then.

**Comment by Sunconure11** [comment]
I'll begin texturing the buffalo tomorrow, since no one has made an offer.

**Comment by PitchBright** [comment]
Are you concerned that it will turn out really bad? I can't tell if you're trying to give someone else a chance to participate, or if you're concerned that if you do it, it won't look good.  xD

**Comment by Sunconure11** [comment]
I'm trying to give someone else a chance to participate.

**Comment by PitchBright** [comment]
KK… wasn't sure. It's probably best that you do it, since it's for your model. Surely you pictured what it would look like before you started modelling, so I can't imagine anybody else would hit the mark better than you. Lookin' forward to seein' it when it's done!

**Comment by PitchBright** [comment]
If it hasn't been mentioned, this module will need a Salt item for butter and whatnot

It can be something as simple as crafting a water bottle into the salt item (since a lot of other mods already offer Salt as a thing, there's no need to reinvent it… better to just offer a basic item and mechanic to the user incase they don't have any other mods that do minerals)

**Comment by PitchBright** [comment]
Also, will require a mechanic to separate fat from milk. For the purpose of creams.

**Comment by PitchBright** [comment]
@Sunconure11 We need Goats ;)

**Comment by Sunconure11** [comment]
Goats are planned, and yes, we do need a salt item, as salt is used in a lot of dairy products.

**Comment by Sunconure11** [comment]
Salt could be crafted, or mined. If Harvestcraft or another mod is installed that has its own salt ore, the generation can be disabled.

**Comment by Sunconure11** [comment]
Chhurpi: A cheese created from yak's milk, starter culture, rennet, and any vegetable.

**Comment by Sunconure11** [comment]
Animals listed in all modules I've written so far:

Dairy:

Yak, Goats, Water Buffalo, Camels

Desert:

American Cheetah, Shasta Ground Sloth

Tundra:

Mammoths, Musk Ox, Walruses, Right Whales

Butcher:

Turkey

Maybe I should add seals to my plans for the tundra module LOL

Also, if we make any "animals" for the nether module, they should either be small dragons, or some kind of animalistic spirit.

**Comment by Sunconure11** [comment]
Also I screwed up my sleep a bit. The water buffalo texture is going to be held off for a little bit. And by screwed up I mean I did not sleep much today, and various other shenanigans.

**Comment by Sunconure11** [comment]
I'll see about working on the buffalo as soon as possible, though I can barely function past 3 PM EST due to my screwed up sleep schedule.

**Comment by PitchBright** [comment]
Awesome!

**Comment by Sunconure11** [comment]
I'll create the textures for the buffalo tomorrow, along with knifebushes for the nether module. I think I finally fixed my sleep schedule. I will also create a variant for it carrying two chests. The process of making the texture might take a few days though.

**Comment by Sunconure11** [comment]
Well, I'll come up with the color scheme, but, I'm still pretty exhausted.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/vifrl3bsh9occlo/Screenshot%202015-12-09%2016.55.06.png?dl=0 So the texture map has been generated.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/2p2gu9q1ff3udc7/Screenshot%202015-12-12%2010.46.40.png?dl=0

It begins.

**Comment by IceDragon200** [comment]
Let this issue die a quiet and peaceful death, take up any discussion and issues in #187
