### ISSUE TITLE
Feature Request: Configgable Heat Source for Brew Kettle

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#143]
For the guys that do realism stuff… netherrack + fire isn't an option for a heat source (because 'netherrack')… and that leaves just Lava. Lava's pretty unrealistic as a heat source, to be honest, because lava is about 1000 degrees and it would melt your face off.

Would it be possible to get a configgable list of Heat Source blocks for the Brew Kettle in the Cellar.conf? That way users can definte their own sources of heats?

Pretty please :-)

**Comment by Ar97x** [comment]
That would be cool, mostly if we could use heat sources from other mods.

**Comment by spannerman79** [comment]
There is Thaumcraft Nitor as one such source.

**Comment by Ar97x** [comment]
And Thermal Expansion with a large variety, like liquidacted cool (using
that almost useless pulverized coal), pyrotheum and destabilized redstone
(which is probably warm too)

**Comment by IceDragon200** [comment]
@PitchBright @Ar97x Its in the [API](https://github.com/Alatyami/Growthcraft-1.7/tree/development/src/java/growthcraft/api/cellar/heatsource) you need only to add the [entries](https://github.com/Alatyami/Growthcraft-1.7/blob/development/src/java/growthcraft/cellar/GrowthCraftCellar.java#L244-L249)

I could add some config options to configure the default heat sources (fire, lava)

Just for demo purposes [Registration](https://github.com/IceDragon200/YATM/blob/f516d87b8291b2553d914076c66aa5a91476ed14/src/main/id2h/yatm/YATM.java#L642-L645)
[Heat Source Block implementation](https://github.com/IceDragon200/YATM/blob/f516d87b8291b2553d914076c66aa5a91476ed14/src/main/id2h/yatm/integration/growthcraft/HeatSourceHeater.java#L34)

**Comment by Ar97x** [comment]
Wow that was quick. I'll check that as soon as possible

**Comment by PitchBright** [comment]
I hate to admit this, but as a non-coder, I don't know what I'm supposed to do to add the entries. I was hoping for a spot in the config that as an average-joe user, where I could define 'em.

Sorry to be nuisance with this, but if you could do me a fav and gimme a little hand-holding walkthrough on what you mean… I will definitely learn from it and retain the knowledge, and apply it to other things, like the Fruit Press #61 

PS. I'm always in the #growthcraft channel on IRC if you have time for me there.

**Comment by IceDragon200** [comment]
@PitchBright https://github.com/Alatyami/Growthcraft-1.7/commit/413e7e62fdac39d1650e79dc460b3b26733ce273

**Comment by PitchBright** [comment]
If I understand that correctly, you've put a config option to allow us to change the heat values of the default heat sources (vanilla lava & fire). Correct me if I'm wrong there  xD

That said, if that's the case… that's actually not the problem I was having. We use Enviromine mod which simulates ambient temperature, and lava is 1000 degrees centigrade, so any time we go near lava, we get heatstroke and die pretty much instantly. And that's realistic and I'm cool with that.

What I was thinking would be good for the config, is for the user to be able to input their own blocks (including other mod's blocks) to define them as heat sources. For example I might want to enter a Metallurgy Furnace and give it a value of 0.75f.

**Comment by IceDragon200** [comment]
@PitchBright https://github.com/Alatyami/Growthcraft-1.7/commit/67159906f80d7f9171281a2961ee5759bfabcfdb

Go wild? 
This will generate a new config file `$MINECRAFT/config/growthcraft/cellar/heatsources.json` with the default entries

**Comment by PitchBright** [comment]
Wicked! I'll test and then close this up. IceD, you're a rockstar.

How much of a nightmare would it be for you to do the same for #61 (assuming it's a similar type of feature request)?  I know I'm pushin' my luck. But I figured I'd ask while you're on a tear. :)

**Comment by IceDragon200** [comment]
@PitchBright It was on the plan afterwards, but I'm currently overhauling logging first

**Comment by PitchBright** [comment]
Heat source JSON works beautifully! I'm so happy. Thanks so much for bangin' that out. You shoulda seen me try to build our Brewery, I could only be in that building for 15 seconds at a time, then I'd have to go cool off in the snow for 5 minutes. LOL.

Just curious… what's the 32767 mean in the config? Is that the same as a wildcard?

**Comment by IceDragon200** [comment]
@PitchBright Its the internal wildcard value, you can set it to anything less than `0` (like `-1`) and it will convert it to a wildcard internally.

**Comment by PitchBright** [comment]
Okay cool. Thanks again!

**Comment by Sunconure11** [comment]
Quick question, does anyone know the ID of the technical block for Nitor?

**Comment by IceDragon200** [comment]
@Sunconure11 Use NEI and dump the block data

**Comment by spannerman79** [comment]
> ID of the technical block for Nitor

`Thaumcraft:ItemResource:1`

**Comment by IceDragon200** [comment]
@Sunconure11 @spannerman79 That only gives you the item, the actual block is `Thaumcraft:blockAiry:1`

The Heatsource would be this:

``` json
{
  "mod_id": "Thaumcraft",
  "block_name": "blockAiry",
  "states": {
    "1": 1.0
  }
}
```

I've added it as a default entry in the user heat sources if you have Thaumcraft available, be sure to remove your old heatsources.json to generate the new one.
