### ISSUE TITLE
Fermentation Barrel progress bar doesn't really indicate anything

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#145]
The white arrow above the yeast/netherwart slot zips up repeatedly, but it gives the user no real sense as to where they are in the fermentation process timeline. 

Would it be easy enough to make the progress bar reflect the user-configured fermentation time?

**Comment by IceDragon200** [comment]
@PitchBright Its a decoration, pay attention to the bubbles instead, they, are the real progress indication.

Fermentation time is configable (nether wart fermentation time is hardcoded as `fermentationTime * 0.66`, so thats something that may change)

**Comment by PitchBright** [comment]
I didn't realize that netherwart ferments faster than the value I stick in the config. Thanks for the heads up on that. (I've got my barrels ferment time set to something like 24000000).

May I suggest just getting rid of the decorative arrow and enlarging the Bubbles so that they become more readable? Conversely (and preferably, because it actually makes a lot more sense on both fronts)… I would make the bubbles the decorative part because they would indicate that "fermenting is happening/bubbling"… and the progress arrow shows the user the true stage of fermentation (because it's easier to read, and more intuitive to read for that purpose).

I can do any GUI changes you need done in photoshop, just hit me up here, or on your IRC channel and I'll take care of it right away so that you have something for your testing purposes while you're making changes to the code.

**Comment by IceDragon200** [comment]
@PitchBright 8a8bce6 !?
I slowed it down a bit too so you can watch it go up sloooowly every 60 ticks >.>;

**Comment by PitchBright** [comment]
Yeah, that's pretty cool. I'll test it out in-game just so we know she's good, and then close this one out. I think this'll make things make way more sense in that GUI, plus more useful when it comes to long Ferment times (1000 mc days) :-)

**Comment by PitchBright** [comment]
Confirmed fixed. Works amazing… and I think it's a sharp improvement! Thanks!
