### ISSUE TITLE
[Modpack request] Tame the World 

### ISSUE THREAD

**Issue by Alnarra** [GrowthcraftCE/Growthcraft-1.7#148]
Hey there folks, you guys said in your section to make a new issue and list the mods I'd be working with so I wanted to go ahead and do that

Modpack Thread is Here: http://forum.feed-the-beast.com/threads/1-7-10-tame-the-world-magic-and-tech-exploration-and-pain.127218/

Mod listing is: 
Antique Atlas by Hunternif
AppleCore by squeek502
Aroma1997Core by Aroma1997
AtomicStryker's BattleTowers by AtomicStryker
Automagy by Tuhljin - Granted
Baubles by Azanor
BiblioCraft by Nuchaz
Botania by Vazkii
Carpenter's Blocks by Mineshopper
Chisel 2 by warlordjones, tterrag1098, TheCricket26, Drullkus
CodeChickenCore by Chickenbones
CodeChickenLib by Chickenbones
CoroUtil by Corosauce
Dark Menagerie by RWTema
Deadly World by FatherToast
DenseOres by RWTema
Dr. Cyano's Lootable Bodies by Dr Cyano
DragonAPI by Reika - Granted
Dungeon Mobs by GnomeWorks
DungeonPack by Stuuupiiid
Ender Zoo by CrazyPants
Enhanced Inventories by ANIMENIAC7
Ex Astris by LoveHoly
Ex Nihilo by Erasmus_Crowley
Falling Meteors Mod by AlexDGr8r
FastCraft by Player - Granted
Forbidden Magic by SpitefulFox
Forge Multipart by Chickenbones
HarvestCraft by MatrexsVigil, Rhodox
Hunger Overhaul by iguana_man
Immersive Engineering by BluSunrize
In-Game Wiki Mod by MineMaarten
INpure Core by denoflionsx
Inventory Tweaks by Kobata
IronChests by cpw, progwml6
JABBA by ProfMobius
Lava Monsters by FatherToast
Localized Weather & Stormfronts by Corosauce
Lycanite's Mobs by Lycanite
Malisis Core by Ordinastie
Malisis Doors by Ordinastie
MineTweaker by StanH
Mob Properties by FatherToast
NEI Addons by bdew
NEI Integration by Tonius
Not Enough Items by Chickenbones
OpenEye by Mikeemoo, boq
PneumaticCraft by MineMaarten
Primitive Mobs by Daveyx0
Random Things by Lumien
Roguelike Dungeons by Greymerk
RotaryCraft by Reika - Granted
Ruins by AtomicStryker
Special Mobs by FatherToast
Thaumcraft by Azanor
Thaumcraft NEI Plugin by DjGiannuzz
Thaumcraft Node Tracker by Dyonovan
Thaumic Horizons by TheKentington
The Spice of Life by squeek502
Trophy Slots by Lomeli12
Twilight Forest by Benimatic
Waila by ProfMobius
Waila Harvestability by squeek502
Witchery by Emoniph - Granted
Zombie Awareness by Corosauce

Currently

**Comment by Alatyami** [comment]
Thank you for your modlist there are some mods that we haven't seen before.

Usage in you modpack is approved.
