### ISSUE TITLE
Rice Patty conflict with AgriCraft

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#150]
When AgriCraft is also installed with Growthcraft users cannot create Rice Patties for planting rice. When you right click with the shovel it creates a Water Pad Block. The AgriCraft forums state that this is configurable via a config file. I am logging an issue so that we can look into it and document the work around or find a way to interface with AgriCraft.

**Comment by Ar97x** [comment]
Good to now. I use both mods but I haven't got to plant rice yet. Hope you
fix it soon, I can't wait to get some sake going.

**Comment by IceDragon200** [comment]
@Alatyami, @Ar97x Okay, I'm about to look into this, just gonna grab the Argicraft development build first

**Comment by IceDragon200** [comment]
@Alatyami @Ar97x Not sure how to go about this one, we could add a new tool specially for making paddies, but that seems like overkill.

I'm really not sure, WDYT?

**Comment by Alatyami** [comment]
I'm thinking that making a set of Growthcraft tools using a dictionary
would be the solution. But with mods moving to MC 1.8 we might just push
this fix to Growthcraft-1.8.

**Comment by InfinityRaider** [comment]
Hello, I'm the creator of AgriCraft, what do you say if the player is sneaking, I do nothing and it creates your rice paddy?

**Comment by PitchBright** [comment]
I think this issue creates an opportunity to make GrowthCraft better, by ditching the shovel part of the process, altogether. IRL, you plant rice on the tilled soil, then flood it. So if we cut out that second step of converting the farmland to a rice paddy, then flooding it, and then planting in it (which is backwards, I might add)… and go with 1-Till Farmland with Hoe, 2-Plant Rice, 3-Dump bucket of water on Rice Crop and it converts to the Rice Paddy block.

That's more realistic, makes GC better, and it also solves the AgriCraft problem and then Infinity won't have to do anything on his end. Win-Win-Win sitch.

**Comment by Ar97x** [comment]
Well, I've played awhile ago with this and I'm sure it's fixed, cause I can make the rice paddy by r-clicking with a shovel, and the agricraft variant by shift-r-clicking with the shovel. Can we close this one?

**Comment by Sunconure11** [comment]
Can anyone else confirm what @Ar97x found? If so, then close this.

**Comment by aflame13** [comment]
Made an account just to respond to this thread. I can say this is not fixed with Growthcraft 2.5.2 and Agricraft 1.5.0 installed together if the Agricraft config for sneak-making the water pads is default (false). I changed it to "true" and making rice pads now work if not sneaking.

**Comment by Ar97x** [comment]
Oh I must have enabled it. What if we change the way it is so our rice
paddy is the one that needs shift-clicking by default? This way we only
need to mention it on the future ingame books and, for now, on the update
log.

**Comment by xenoswift** [comment]
Since AgriCraft has a setting in its config now which mediates this behaviour;
"set to true to only create water pads while sneaking"

I think this issue can be safely closed or re-labelled for a config option in a future enhancement.
