### ISSUE TITLE
[Modpack Request] Project Pear

### ISSUE THREAD

**Issue by SentinelX101** [GrowthcraftCE/Growthcraft-1.7#155]
Hello, 

I'm requesting permission to use Growthcraft Community Edition in the Project Pear modpack which is currently private but will be released to the public soon™.

Also keep up the great work with this, I was very happy to discover this new Growthcraft when I was in the process of updating my modpack. 

**Mod List/Permissions:** http://docs.google.com/spreadsheets/d/1MpN4Hp8ey0AQtOkfzz4eMX25SizyNOYakVuVvDYjhAQ/edit?usp=sharing

**Comment by IceDragon200** [comment]
Thank you for picking Growthcraft for your modpack!

Permission is hereby granted to use Growthcraft in your modpack.

Be sure to check our development for the Growthcraft 2.4.0 which will be released soon™ (actually I have no idea when).
