### ISSUE TITLE
Use new Forge event hook

### ISSUE THREAD

**Issue by labpaw** [GrowthcraftCE/Growthcraft-1.7#156]
Instead of temporal fix here https://github.com/GrowthcraftCE/Growthcraft-1.7/commit/502934bad0dfdee5355e2c126a8c888d54268dae maybe it's better to use [new Forge event](https://github.com/MinecraftForge/MinecraftForge/commit/d1598763853a1b87854ecfb647639c59c5183aea)?

**Comment by IceDragon200** [comment]
@Adaptivity I hope that patch is available in 1558, or you're gonna have to stick with that temporal fix.

EDIT:
Nope, the event is not available, in 1558, I will not implement it until it enters the recommended build.

Wish we had a "wontfix-yet" label

**Comment by labpaw** [comment]
@IceDragon200 it will not go to recommended build. Because there are probably will be no new RBs for 1.7.10 since 1.7.10 support is finished. Only _major_ bugs will be fixed, no new features or improvements. However, I think it's safe to use latest build. Few mods switched to this build already. So, we can say that Forge 1566 is the last build for 1.7.10, mostly.

**Comment by spannerman79** [comment]
Recommended builds are there for a purpose @Adaptivity.

And no, 1566 won't be the last build for 1.7.10 as many patches are backported to 1.7.10, even as far back as to 1.6.4 - perfect example was 9.11.1.1345 for 1.6.4

**Comment by labpaw** [comment]
9.11.1.1345 for 1.6.4 -> gradle was added back. Such a big change...
You will see there are will be no updates anymore (and no more backports). Only if bug _worth fixing_. I still can't see the difference between RB and last build... because they are same, no experimental or unstable features. Just no difference, they are both stable. Anyway, it's up to GC devs.

**Comment by spannerman79** [comment]
Well its pretty easy to see, @IceDragon200 added wontfix label

**Comment by labpaw** [comment]
Also, here you go as I said before: https://twitter.com/voxcpw/status/664959099164041218 "There also the _final_ RB". Final. RB.
And LexManos: "We do not plan on updating 1.7.10 anymore, but if MAJOR bugs are found we can. 1.7.10 is old, it's time to move on." Sitting here and waiting for next RB is basically same as waiting for new RB for MC 1.2.5

**Comment by spannerman79** [comment]
And if that was the actual standard [this](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html) would also be updated - take note on the right - Recommended 10.13.4.1558

Twitter is not the be all and end all of statements, nor can social media be relied upon 100%.

**Comment by labpaw** [comment]
Yeah, I mean that there are will be no more _RBs_ as twitter says. 1558 will stay as recommended for forever. However, new versions MAY out but only if major bug need to be fixed. I still think it's good to go on 1566. Nothing will break.

**Comment by ghost** [comment]
i was forced by erebus to use latest build  so I don't know how it will affect me but latest [growthcraft] dev as well as latest official build both work fine
