### ISSUE TITLE
Checkstyle warnings

### ISSUE THREAD

**Issue by labpaw** [GrowthcraftCE/Growthcraft-1.7#157]
Getting a lot of checkstyle warnings during compiling the mod. This happens only once when you building the mod in clean instance. Minor issue but still.
How to reproduce:
1) Download latest source
2) Create _another clean_ instance of Growthcraft code
3) Run _gradle build_ command

**Comment by IceDragon200** [comment]
@Adaptivity If the warnings are from Thaumcraft, or while building forge, just ignore them.

I just rebuilt forge 1558, and had 99 warnings from building forge alone, I'd fix and send a PR for the Thaumcraft ones, not sure if Azanor will accept my pr though...

**Comment by spannerman79** [comment]
If those errors were to do with ore registry I think it's to do with the mod register ores at the wrong time.

`register your ore dictionary entries after the GameRegistry`

**Comment by IceDragon200** [comment]
@spannerman79 Forestry had quite a bit of them, never got around to reporting it though

**Comment by spannerman79** [comment]
I think all 1558 is push mod dev to do their ore dictionary registers correctly lol.

I'm no mod dev but from a user and someone that runs a server view that's the only difference that I see

**Comment by labpaw** [comment]
Nope, those errors comes from Growthcraft. This is how they look (there are a lot of them):
![asdasdasd](https://cloud.githubusercontent.com/assets/1560181/11453044/fa8ea4d4-960c-11e5-9b5e-6837910af2d4.jpg)

**Comment by IceDragon200** [comment]
@Adaptivity Oh Windows. 

Nothing to see here then _removes the checkstyle line to shut windows up_

**Comment by IceDragon200** [comment]
@Adaptivity It should be resolved now, I commented out the newline check

**Comment by labpaw** [comment]
Fixed now.
