### ISSUE TITLE
rope does not work on custom fences including bamboo fence

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#158]
while testing golems i noticed rope only sticks on default MC Fence  and any custom fences including Growthcraft bamboo does not work.

can anyone else verify this?

**Comment by IceDragon200** [comment]
@trollworkout They're hardcoded for vanilla oak fences.

They don't even work on netherbrick fences.

Its on the TODO, but low priority

**Comment by ghost** [comment]
@IceDragon200  aight.  n o worries. is not a must right now anyway.

**Comment by ghost** [comment]
@IceDragon200  This will probably require some heavy code changes which will add a few bugs so i'd move this to 2.4.1+ or later. I wouldn't say this is a bug really. I's more like a missing feature haha.

**Comment by IceDragon200** [comment]
@trollworkout Now present in the latest development build

**Comment by ghost** [comment]
@IceDragon200  NICE :+1:
