### ISSUE TITLE
grape vine leaves don't seem to want to spread in mushroom biome (plz double check my findings)

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#159]
i made my base in mushroom biome and seems grapes don't wanna spread on the ropes. 

I may be able to manually spread them using bonemeal but it may be some issue with the vines checking for grass/dirt underneath and if is mycelium it doesn't spread. You can till mycelium by breaking the block and then placing the dirt back and tilling it. If a water source is nearby it stays tilled but grapes don't wanna spread .

by grapes i mean grape leaves.. the grape plant grows all the way to the rope but it doesn't spread

Can someone investigate this issue and double check my findings?

Is either mycelium or mushroom biome

**Comment by IceDragon200** [comment]
@trollworkout There isn't anything that would prevent them, unless you didn't place the ropes correctly

Grape leaves grow in a + pattern, where the center is the trunk, it will only extend 3 blocks away from the trunk, any further and leaf decay will kick in, you can place trunks at intervals to keep up the range

```
TTT
|||
|||
|||
TTT

Where `T` is a grape vine trunk
and | is a Rope
```

**Comment by ghost** [comment]
@IceDragon200  I will try again but I'm pretty sure I have it proper and 3 blocks. i'll check again.

**Comment by IceDragon200** [comment]
Can anyone confirm this?

**Comment by PitchBright** [comment]
Works for me. No bonemeal was used at any point during the growth process either. http://imgur.com/a/4MVAI

**Comment by IceDragon200** [comment]
@trollworkout Case of badluck?
