### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#16]
Ex Nihilo, Botania, Thermal Expansion and Thaumcraft are all in the realm of possibility.

**Comment by Ar97x** [comment]
I don't know very much of ExNihilo or Thaumcraft, but I play a lot with
Thermal Expansion. What do you have in mind? Growing crops with the
Photogenic Insulator? Storing booze on Portable Tanks? Using the Liquid
Transposer to transfer drinks?

**Comment by Ar97x** [comment]
Interactions with Thirst Mod is something that I have in mind too.
Em 27/07/2015 20:37, "Victor Diehl" vdiehl97@gmail.com escreveu:

> I don't know very much of ExNihilo or Thaumcraft, but I play a lot with
> Thermal Expansion. What do you have in mind? Growing crops with the
> Photogenic Insulator? Storing booze on Portable Tanks? Using the Liquid
> Transposer to transfer drinks?

**Comment by Sunconure11** [comment]
A lot of what you mentioned, plus some machines that turn on them TE is installed, such as electric stills, and electric juicers.

**Comment by Sunconure11** [comment]
For Botania support, it would be mainly allowing mystical flowers to spread near beehives. Craftable flowers cannot and will not spread. Not even early game stuff like Pure Daisies. For Thaumcraft, more aspects on stuff. Ex Nihilo support was highlighted by another user on the forums. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286298-growthcraft-jul-15-2014-proper-1-7-10-release?comment=2249

**Comment by Ar97x** [comment]
Yeah I saw it before. Do you think that we need to prioritize the mod
support stuff or the new things that is under development?

**Comment by SynfulChaot** [comment]
Probably ask Vazkii on the mystical flower spread.  Forestry doesn't allow them to spread with it's beehives as it bypasses Botania's own flower spread method (Jaded Amaranthus).

**Comment by Sunconure11** [comment]
Maybe mod support first. Also, Botania is open source, who said we need to ask her? We can see how the Jaded Amaranthus spreads flowers, and how to allow the mystical flowers to spread with the beehives. But if we cannot figure it out, then yeah, we can always ditch that, or ask her.

**Comment by SynfulChaot** [comment]
I think it's the spreading the flowers without the resultant mana cost that is the reason for not having beehives spread mystic flowers.  Perhaps if it needed to use mana to spread them?

**Comment by Ar97x** [comment]
Perhaps if we put mana producing flowers nearby as a condition to mystical
flowers to multiplicate it could work well. I think we should at least ask
the modder if it's fine for him/her.

**Comment by Sunconure11** [comment]
Hm, a mana-infused apiary might be interesting.

**Comment by Ar97x** [comment]
Yeah. That sounds cool.

**Comment by Sunconure11** [comment]
For Botania, why not allow the Drum of the Wild to harvest our plants?

**Comment by SynfulChaot** [comment]
Remember that the Drum of the Wild may harvest, but it also _always_ fully uproots them.

**Comment by Ar97x** [comment]
How do I invite someone to this?

**Comment by IceDragon200** [comment]
@Ar97x Place an @ infront of their name, they'll be pinged, and they'll be subscribed once they comment, unless they opt out

**Comment by IceDragon200** [comment]
@Sunconure11 How about a checklist of mods to support?

> ## Mod Support
> - [ ] Ex Nihilo
> - [ ] Botania 
> - [ ] Terrafirma Craft
> - [ ] Thermal Expansion
> - [x] Thaumcraft (See #105)
> - [x] Forestry
> - [x] Buildcraft (See #104, #106, wrenches, and pipe colours)

**Comment by Sunconure11** [comment]
Here are some other ideas for mod integration:

Vegan Option
Harvestcraft
Garden Stuff
IC2?
Hunger Overhaul (crops and animals should be affected by it)
Minetweaker

**Comment by Sunconure11** [comment]
As this was brought up by another user, I will mention it here.

There should be some integration with mods with seasons, as well as better climates.

Reasonable Realism and Enviromine would probably be the best choices for this.

We could probably start such integration when progress begins on the Tundra or Desert modules (probably not for a while though).

**Comment by Sunconure11** [comment]
@IceDragon200, how feasible is it to add support for modded flowers for apiaries in a future update?

Also, if you actually do that, would it be possible to allow one to blacklist specific plants from the apiary?

**Comment by IceDragon200** [comment]
@Sunconure11  Should be doable, you won't need a blacklist, because you'll be whitelisting plants anyway

**Comment by Sunconure11** [comment]
I see.

What about a function to invert the whitelist into a blacklist? A lot of mods do that. There are mods like PmP that add a lot of flowers. Maybe some inbuilt support for all flowers in that mod (angiosperms, of course, no ferns or fungi, or other weird stuff)

Biomes O' Plenty would be easy for a player to pull off, but, might make a good default setting anyways. Same with ExtraBiomesXL.

As for other mods that add their own flowers, lets just let the players add them to the whitelist. (I would like to add F&A flowers, but, there are very few true flowering plants in that mod, so, that would be an example of something players should do on their end)

If the whitelist function is added, it should also be possible for players to remove existing flowers from the default configs without issue, even vanilla ones.

**Comment by IceDragon200** [comment]
@Sunconure11 We don't even have a "flower list" per say, only the vanilla flowers, which is why I said "we don't need a blacklist"

**Comment by Sunconure11** [comment]
Alrighty

**Comment by Sunconure11** [comment]
However, would it be possible to add oredictionary support and support for a wildcard function to call all variants of a flower block without using a ton of entries?

Edit: Derp

**Comment by IceDragon200** [comment]
If you'd like us to support a particular mod, please open an issue specifically for that mod and what you'd like us to support or integrate with.
