### ISSUE TITLE
[SUGGESTION] OreDictionary support for heat sources and input items for presser

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#160]
Would it be possible to add OreDictionary support for heat sources, and input items for the fruit presser? Say I want all items in the ore dictionary for nuts to be able to be usable in the fruit presser. Would it be possible to add this in the future?

**Comment by IceDragon200** [comment]
@Sunconure11 Most certainly, I'll add it right now (once this headache goes away)

Example:

``` json
#  for regular items
"item": {
  "<insert ItemStackSchema>"
}
"input_item": {
  "<insert ItemStackSchema>"
}

# for ore dictionary items
"ore": {
  "name": "nutWalnut",
  "amount": 1
}

"input_ore": {
  "name": "nutChestnut",
  "amount": 1
}
```

**Comment by IceDragon200** [comment]
@Sunconure11 Okay, so I can give you OreDictionary support for everything except Heat Sources.

Reason: Heat Sources require a block, not an item, the OreDictionary returns ItemStacks, which gives me Items, some mods have different ItemBlock behaviour which will make it difficult to pull the actual block required from them.

Here 78cd5486cc831d56868bbbca6e574ffac6afc622, I'll update the wiki in a bit with instructions on how to use this

**Comment by Sunconure11** [comment]
Thanks, I'll toy around with this later.

**Comment by Sunconure11** [comment]
```
[{
        "input_ore": {
            "name": "sourceVegetableOil",
            "amount": 1
        },
    "fluid": {
        "name": "VeganOption.fluidOilVegetable",
        "amount": 40
    },
    "time": 40,
    "residue": {
        "mod_id": "VeganOption",
        "name": "waxVegetable",
        "amount": 1,
        "meta": 0,
        "pomace": 0.3
    }
}]
```

Can you tell me what I'm doing wrong with this?

**Comment by IceDragon200** [comment]
@Sunconure11 My post was actually a mock up, the format is the same as the original, just replace 
"mod_id", "name" and "meta", with "ore"

The former are used for specifying items directly from the GameRegistry, while the latter is the new OreDictionary directive

``` json
[
    {
        "item": {
            "comment": "When using ore dictionary items, simply replace the 'mod_id', 'name', and 'meta' with 'ore'",
            "ore": "sourceVegetableOil",
            "amount": 1
        },
        "fluid": {
            "name": "VeganOption.fluidOilVegetable",
            "amount": 40
        },
        "time": 40,
        "residue": {
            "comment": "Residue items are also regular items, they only have an extra 'pomace' field",
            "mod_id": "VeganOption",
            "name": "waxVegetable",
            "amount": 1,
            "meta": 0,
            "pomace": 0.3
        }
    }
]
```

If `waxVegetable` is an ore dictionary item you use:

``` json
        "residue": {
            "comment": "Drop the name, mod_id and meta",
            "ore": "waxVegetable",
            "amount": 1,
            "pomace": 0.3
        }
```

The format hasn't changed, I just added a new field for ore dictionary support.

[Docs](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/User-API-%282.4.x%29#item-key-schemas)

Forgot to mention, I added a "comment" field to most of the schemas, you can check the link for full details

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/lcq4b4d36411jjq/Screenshot%202015-12-03%2006.32.36.png?dl=0 Got it working, looks like the syntax was wrong.
