### ISSUE TITLE
Pressers will not take items from hoppers

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#161]
Basically, if you try to place any item into a press via a hopper, it won't take the item.

It might be affecting pipes and such from other mods as well. I tried it with hopperducts and had no luck.

Edit 1: It appears to be related to the position of the piping and hoppers. Would it be possible to allow pressers to take items from all sides around the base?

**Comment by IceDragon200** [comment]
@Sunconure11 Do hoppers inject items from the side?

If not, I don't think a hopper will work with the fruit press, its made from 2 blocks, the Fruit Presser (the top) and the Fruit Press (should have been called the Basin, the bottom), the presser has no inventory, so it would not respond to the hopper if you placed it on top.

I'll look into this later

**Comment by Ar97x** [comment]
So the input and output only works on the bottom? And yes, the hopper
inputs in the direction you place it.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/41huslv7fijf158/Screenshot%202016-01-22%2016.29.04.png?dl=0

This setup is fully functional.
