### ISSUE TITLE
Modpack Permission (Interchange)

### ISSUE THREAD

**Issue by frewmack** [GrowthcraftCE/Growthcraft-1.7#162]
Hello!  I'd like to add Growthcraft Community Edition to my modpack Interchange on the ATLauncher.  I'd always been a fan of this mod, and I'm really happy that you guys decided to keep it alive.

Here's my modlist as of now: https://docs.google.com/spreadsheets/d/1RruPGkLy4y2dLPN0s6kZQ4DP5buQCA7vKZ_ME2gQbs4/edit?usp=sharing

Thank you!

**Comment by IceDragon200** [comment]
@BadSniper Permission is hereby granted for you to use Growthcraft in your modpack, if you have any trouble, issues or general questions feel free to open an issue here on github, or leave us a message in the `#Growthcraft` irc channel on `esper.net`
