### ISSUE TITLE
Growthcraft Wheat Module Suggestions

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#163]
Just puttin' this out there for consideration:

Input: Vanilla Wheat 

GC Scythe - Cut the wheat down
GC Thresher - Separate the grains from the straw
GC Winnowing - Separate the grain from the husk
GC Flour Mill - Multiblock structure (that only works if sitting on a River biome) to grind grain into flour
GC Breadmaking (Oven?) - Yeast, Water, Flour, etc

Output: Vanilla Bread + other GC food products/ingredients

Make GC components OreDict compatible for other mods harvestables such as Barley, Rye, Oats, etc.

Crude mockup of the guts of the Watermill/Flourmill that make the milling magic happen. http://imgur.com/a/gxcBL

**Comment by Sunconure11** [comment]
This could probably fit into the granary module idea.

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Granary-(Concept)

**Comment by PitchBright** [comment]
Ah ya, definitely!

**Comment by Ar97x** [comment]
I think this is a great idea, but I'd like to add that we might want to
lock the vanilla bread recipe, to make the people really need to use the
whole process. If not, we could change the drops from the wheat crop, like
grains or whatever you think is appropriate.

**Comment by PitchBright** [comment]
Yeah, the vanilla bread recipe would totally have to be removed, otherwise this whole module would be pointless. That said, grains aren't dropped when you harvest wheat, so to go straight to grain from wheat would negate half of the process of the module (Threshing step).

**Comment by PitchBright** [comment]
@Alatyami @everyone While I'm here… I noticed the topic title changed. And that brings me to something that, while I don't think it's a problem… I definitely noticed it, and I think it's at least worth mentioning. But, only if we intend to stay close to the way Gwafu did things. And that's in the way modules are named. Again, this isn't make or break for me.

Gwafu named his modules based on the resource, not the process or the theme. "Apples", "Hops", "Grapes", "Rice", etc.

That's why I titled it "Wheat" module.

But what I see happening here is we're naming modules based on processes or components. "Dairy", "Tannery", etc.

Not a big deal to me (just saying that again, so y'all know)… but if we're looking to be consistent AND carry the Gwafu torch, we should be naming the modules "Milk", "Leather", "Wheat", "Meat" … not "Dairy", "Tannery", "Milling", "Butchery", etc blah blah blah.

**Comment by Alatyami** [comment]
<2Cents> Or we can leave wheat and bread alone as vanilla items and make
all of the GC Granary breads have a beneficial effect. I really do not like
modifying vanilla recipes and items. It would force a change that the
player might not want or affect other mods that use bread. </2cents>

**Comment by Alatyami** [comment]
@PitchBright you are absolutely right regarding the module name and that is why we are doing a community edition to keep us all on track. We'll apply the changes the other new modules as well.

**Comment by PitchBright** [comment]
TBH, I'm not a proponent of imposing effects on players. The hardcoded effects on the boozes for example, completely break the balance of other systems that I personally have in play, that utilize effects (health regen, temperature based stuff - ie. Enviromine, Player Movement, Hunger Overhaul). That's pretty much the reason I don't make anything beyond Young Booze and Fortified Booze available on my server. That means I'm only using about 15% of the booze system you guys worked so hard on, because I don't want to incur the impositions that came with it, via effects. (Although I whispered to the IceDragon that I wouldn't mind him making booze effects configurable when he's really bored and looking for something to do.  <3 ya IceD!)

So buffin' the hell out of GrowthCraft breads with effects just to make it worth it to players to go through the labour-intensive process of making GC Breads, versus Vanilla bread… for the sake of justifying leaving Vanilla bread recipe untouched… creates new headaches, to an even greater extent than touching that vanilla recipe would. (Although I don't think disabling that one recipe would break a whole lot with other mods, to be completely honest.)

That said, why would anybody add a "Wheat Module" if they didn't want to change the way wheat works? I think we should march on, fearlessly, and go ahead with killing the vanilla bread recipe. i honestly can't see a situation where another mod needs the player to make bread via 3xWheat on a crafting table, or else breaks.

**Comment by Sunconure11** [comment]
I'm working on changing the module names.

Tundra and Desert have multiple crops, but, the only one that stands out for either is Agave. What should they be named?

**Comment by PitchBright** [comment]
I haven't read about those modules yet. What is the primary resource that each introduces?

**Comment by Sunconure11** [comment]
Agave and Desert will be merged, so, here are the pages for both:

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Agave-(Concept)

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Desert-(Concept)

And here is the tundra module:

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Tundra-(Concept)

Both modules have concepts for many resources, though one that connects them both is some form of oil, whether it be the jojoba oil from desert, or whale oil from tundra.

**Comment by PitchBright** [comment]
Okay I just scanned them real quickly. I see what's involved there.

Here's my take on it… and please understand that I'm not opposed to those ideas being implemented in "the game". I love your ideas and research @Sunconure11 @trollworkout @y'all and I want a lot of the same things you do. That said, I feel like those two things in particular aren't really "GrowthCraft" things. They're more like BiomesOPlenty meets HarvestCraft type stuff.

I know BOP and HC have even dabbled in those areas. And I also think (in defense of the champs that do the coding on this stuff)… that we shouldn't be looking to retrace paths that other mods have already gone down, unless we're talking about a major major improvement or replacement/overhaul type situation… on those other mod's approaches to said mechanics/features.

To my way of thinking, or at least how I perceived it when Gwafu gave birth to this mod… was that his approach was to take an existing vanilla resource, or to introduce a simple new single resource (via Module)… and add a few "realistic" processes (and mechanics) that make use of those resources, to produce a new commodity.

An example of this would be "Wool Module". Take vanilla wool, clean it, (some other steps in here Im' sure), stretch it out, put it on a GC Spinning Wheel, produce Vanilla string, put it on a GC Loom, produce vanilla carpets.

Again, I'm not trying to crap on anybody's ideas or any of that. I love what you guys are coming up with and I could sit and talk about it with you all day, and I love to learn what you've researched on that stuff too. I think I'm saying this stuff because I'm taking the Gwafu thing into consideration, as well as the coder-dudes who we're creating a mountain of work for by tossin' this stuff out at them.

As the "idea'r guys", I think we need to organize our thoughts and proposals a little more selectively before pitchin' them on the "to-do or for consideration heap". A short list of Tiny bits that make huge improvements to minecraft… is a lot more appealing and do-able-feeling to the coders… than a big list of lotsacoolstuff that might not "technically" be in the original spirit of the mod.

I feel like a shit, because honestly, I'm not trying to be a party-pooper.

**Comment by Sunconure11** [comment]
Hmm... what could make either module more unique? They are based around plants and animals in certain biomes. I tried to think of unique mechanics like that, but, I cannot think of anything that would fit either, except for unique growth for certain crops.

**Comment by PitchBright** [comment]
@Sunconure11 Off the top of my head. Cactus module. Ya got Tequila, and then I'm sure there's other basic uses for cactus that you could research, if you wanted to make the desert a more worthy place to spend time… in the spirit of GrowthCraft.

**Comment by Sunconure11** [comment]
Hmm... what about pressing cactus plants themselves for water?

**Comment by PitchBright** [comment]
If that's an IRL thing, I'm all for it!

**Comment by Sunconure11** [comment]
And what would be a good mechanic for the tundra module? I'm considering something with blubber and refining oil.

**Comment by PitchBright** [comment]
Snow module?

**Comment by Sunconure11** [comment]
For snow, what would even be a good use for that?

**Comment by Sunconure11** [comment]
Though snow module would be a good name for it.

**Comment by Ar97x** [comment]
I prefer to eliminate the regular vanilla recipe, to add a purpose to use
the harder process. And if we make the result being the vanilla bread, I
don't see how this could affect other mods. And I don't like the idea of
buffing the breads, as we already have a buff provider (booze). But I see
an obvious intersection with the Dairy Module (or whatever it'll be
called), at sandwiches making and stuff. My thought was working on
something like Terrafirmacraft food, that you can eat repeatedly, and
combine ingredients and sandwiches to make even bigger ones. As a last idea
(big texts inevitability '-') we should make the saturation for the
sandwiches something outstanding, in a progression system based on which
ingredients are used. Modularity (Idk if this word exists) would be a real
thing on this module in my head.

**Comment by Sunconure11** [comment]
Also I researched into water from cacti... probably not something pleasant.

**Comment by PitchBright** [comment]
I was just tryin' to be stand-up comedy guy… with the quick-quip… but I'm sure there's stuff that the Eskimo and Inuit cultures have done to make use of Snow as a resource.

**Comment by Sunconure11** [comment]
Perhaps some decorative blocks from snow, for one thing? Also, maybe a way to boil ice and snow for water.

**Comment by PitchBright** [comment]
@Ar97x I'm with ya all the way…except that HungerOverhaul and HarvestCraft (foods) cover that ground already. I feel like it would be a misappropriation of the coder-guys' time to try to develop a system there. If they make the components available, people will cross-configure them with other mods to achieve those ends you're proposing.

**Comment by Sunconure11** [comment]
I suggest hunger overhaul integration in another thread.

**Comment by Sunconure11** [comment]
The plants from this mod don't seem to abide by Hunger Overhaul's mechanics.

**Comment by Ar97x** [comment]
Ice Cream Module :D (say yes day yes please)

**Comment by PitchBright** [comment]
^ Milk Module

**Comment by Sunconure11** [comment]
Ice Cream could work in the Milk module.

**Comment by Sunconure11** [comment]
I'm working on some minor mechanic ideas at the moment. Check the bottom of the desert module page now, and the new page for the snow module.

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Snow-(Concept)

**Comment by Ar97x** [comment]
@PitchBright I've never played with Harvestcraft because my computer is
lame. I didn't know that they already had sandwiches worked on. But a
little work on them, just the simple ones wouldn't be so bad.

**Comment by PitchBright** [comment]
It's tough because, while I love all the ideas listed in that concept… I see them as being more of a BOP thing. Or a completely new mod.

**Comment by Sunconure11** [comment]
Yeah, harvestcraft has tons of sandwiches. https://www.dropbox.com/s/k3tkwq3jihkdjyi/Screenshot%202015-12-11%2014.58.22.png?dl=0

**Comment by Sunconure11** [comment]
And I'm working on cacti ideas. However, its kind of tough to use vanilla ones alone, as they are not a specific species, and many cacti are horribly poisonous.

**Comment by PitchBright** [comment]
@Ar97x What ya'd do is make Bread (and Slices)… with different types of bread and bread-based foods… as part of the Wheat Module. That would introduce new foods (or base components to "meal-making") that another mod like HarvestCraft could utilize via OreDict.

**Comment by Alatyami** [comment]
This is where need to clearly define the scope of Growthcraft. While we do want to preserve what Gwafu did, we also want to expand it using the same ideology.

**Comment by PitchBright** [comment]
@Sunconure11 The other thing is, it doesn't have to be horribly complex or intricate. A simple little module that gives a little bit more relevance and purpose to the sole useful resource in the Desert (Cactus)… ain't a bad thing. Plus, it'd probably be super easy to add (code-wise) and it's a small victory, as well as a positive contribution to the roster of modules and GC as a whole.

**Comment by Ar97x** [comment]
@PitchBright That's the idea, simple stuff like bread and butter or cheese
(from Dairy module). OreDict is something necessary of going this way.

**Comment by Sunconure11** [comment]
I wrote this down for extracting water:

Cacti can be pressed for water, but, not without being processed first. First, you must hack the skin of the plant off with a knife, and then only then can you extract water from the meat.

I also added an entry for leaves from prickly pears.

Prickly Pear leaves: These can be harvested from young growth on a prickly pear plant using a set of shears. If you try it with your hands, you will take damage. The leaves can then be steamed in a furnace for food.

As for the snow module, you need a refiner to make whale oil. Jojoba oil from the desert module is weaker, but, does not require a refiner.

Refiner: A crude block, used for refining oil from blubber. It takes a while to refine oil, but, there are whispers that certain fruit from the nether can speed up the process...

And some minor tweaks for the snow module:

You can boil ice for water in a cauldron. First, you must take a piece of ice, and shove it in the cauldron. But it needs a heat source placed underneath it in order to melt.

Snow, when it falls in a cauldron, will slowly pile up. When enough snow is collected, you can boil it for water.

**Comment by PitchBright** [comment]
Quick research tells me that Cactus are used as food, booze, and medicine. We could do some very simple things there, that help to create the illusion of depth, all while staying within the spirit of GC. Again, go simple on it, is my thought.

**Comment by Ar97x** [comment]
Decorative blocks for snow module is a nice idea. Maybe making the snow
block crafting a little different, like putting enough snowballs in a
frame, ice tiles crafting with a knife.

**Comment by Sunconure11** [comment]
Hm... what about the fruit of prickly pears being usable in healing potions? I also contemplated aloe.

**Comment by Sunconure11** [comment]
I'll write down decorative blocks for snow next.

**Comment by Sunconure11** [comment]
And I have the booze part for cacti pretty covered already.

Colonche is made from prickly pear cacti.

**Comment by Sunconure11** [comment]
Decorative ice and snow blocks: In order to create any decorative blocks from ice, you must craft a knife, and then carve the ice into 9 parts, which will yield cut ice. Cut ice, in an emergency, can be used as a one-time weapon. Now, in order to craft decorative ice blocks, you must obtain some snowballs, and craft them together in specific patterns. Uncut ice can also be used in ice-carving patterns. As for snow, you must craft a frame from wood and wooden sticks. Then, place snowballs inside, and carve specific patterns with a small shovel.

**Comment by Sunconure11** [comment]
How does this sound?

**Comment by Sunconure11** [comment]
And while this sounds like a red herring, I'm going to start the texture for the water buffalo for the milk module tomorrow. I generated the texture map, I've just been a bit busy lately.

**Comment by Sunconure11** [comment]
I should write down a concept for aloe. We have very few industrial crop ideas, and I am rather fond of bamboo (and the concept for jojoba). >:U

**Comment by PitchBright** [comment]
Wiki entry made.
