### ISSUE TITLE
suggestion: splash brews + expand netherash fermented brews

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#165]
Create throwable splash brews  by adding gunpowder to a fermented  brew . And in the barrel add a new gunpowder icon ( netherwart, gunpowder, redstone, glowstone). 

(OPTIONAL READ) These new throwable brews look identical in style with regular brews except when you right click you throw them rather than drink them. Whoever is in the splash radius gets the effects + tipsy. Note that if you throw enough of them your target will eventually get blindness and all other bad tipsy effects. These throwable brews need to travel a bit of time to get full duration otherwise the duration is less. So if you throw them at your feet you get less duration while if you throw them above you to hit you on the head you will get full duration. Just like other brews you cannot combine it with extended or potent . All the extra modifier dusts are mutually exclusive. If you add glowstone it turns potent instead. If you add redstone becomes extended instead. Etc.
## 

Netherrash yeast creates more negative effects other  than poison 1  depending on the brew you ferment  such as wither 1, weakness 1, slowness 1. All effects are level 1. Although you cannot extend or make potent these brews you can make them throwable splash brew by adding gunpowder. 

What do you think??

**Comment by ghost** [comment]
im thinking the effects of netherash fermenting is the opposite of normal fermentation for example

apple cider normally gives absorption but with netherash gives random negative effect I
mead normally gives regeneration but with netherash it gives poison I
grapes normally give resistance but with netherash it gives weakness I 
lager normally gives speed and haste but with netheash it gives mining fatigue and slowness
sake normally gives jump boost  but with with netherash gives confusion

**Comment by Sunconure11** [comment]
Netherrash is an infectious agent, but, I suppose that can work as opposed to hyper-extended potions of slowness. In addition to those effects, it inflicts netherrash potion effects, which, spreads to other players and mobs, and slowly damages the player, as well as halts regeneration.

**Comment by PitchBright** [comment]
This info/idea goes with:

https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/66

**Comment by Sunconure11** [comment]
Closed as the nether module is inactive.
