### ISSUE TITLE
Modpack Request (Botanic Adventures)

### ISSUE THREAD

**Issue by ezterry** [GrowthcraftCE/Growthcraft-1.7#166]
I'd like to include this mod in a mcupdater pack (file is pulled from curseforge)  I'm working on/about to release.  Full dev modlist is here (so if you reference this later and something changed it ought to be up to date):

http://sandbox.devnull.name/minecraft/MCUpdater/botanicadv/dev-mods.html

Glad to see the mod is alive, and working with the newer versions of forge.

**Comment by IceDragon200** [comment]
@ezterry Permission is hereby granted to add Growthcraft to your modpack.

If you have any problems and general inquires please peruse the wiki, or open an issue, we'll respond within 1 or 2 days (or a few minutes)
