### ISSUE TITLE
Growthcraft in game books and manuals

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#167]
A little book that you can get in game information about brews, yeasts and (optional) brewer's tools and machinery.   I am thinking it would look like a regular book and each page has 1 brew, yeast or tool listed and there is a bit of introduction. 

pg 1 Apple Cider Young (recipe)
pg 2 Apple Cider Fermented (recipe)
....
pg ?? Brewer's Yeast (recipe)
...

easy and simple :)

**Comment by spannerman79** [comment]
Crafting recepie = book + potion (not sure which type).  Maybe Apple + Book (shapeless) = Growthcraft Book

Side Note:  I'd like to mention the mod [Enchiridion](http://minecraft.curseforge.com/projects/enchiridion) which allows you to create books from json format.  Not to mention its much more stable then IGW-Mod.

Perhaps a hook for Enchiridion to be considered?

**Comment by ghost** [comment]
@spannerman79  I say keep it simple at first make it better later if you want to. See witchery books are pretty basic but quite useful. All you need is a regular MC book with a custom data that has all that info laid out. The only thing is that the last page opened must be remembered when you open the book again.

**Comment by spannerman79** [comment]
Ah yes Witchery books- badly formatted, disjointed, Unicode unfriendly.

Or shock/horror - how about something that is actually cross mod compatible and able to be modded in every single way without looking like cr@p?

One of many reasons why I pulled witchery from my modpack.

**Comment by ghost** [comment]
@spannerman79  I don't disagree with you for example Thaumonomicon is a beautiful book and it has it all. Ideally you'd want that but honestly anything would do to stop me from having to pause the game to check this https://docs.google.com/spreadsheets/d/1ykz1iqWUkarnZC76FGyjKs2wExdOgLJ7XHt3haNOV30/edit#gid=1739283064&vpid=A1

**Comment by ghost** [comment]
@spannerman79  For the recipe I am thinking it's 1 apple and 1 book and the book is present ONLY if you installed the Cellar module in fact is an item added by the Cellar module in that module.

**Comment by Sunconure11** [comment]
Idea for the book name: Brewing 101: The Definitive Guide

**Comment by Alatyami** [comment]
We'll be creating a series of books. Great suggestion and it'll be added to the backlog.

**Comment by ghost** [comment]
@Alatyami  sounds great looking forward :+1:

**Comment by ghost** [comment]
Hey guys while I am waiting I decided to be proactive and create my own book with custom NBT tag script in MineTweaker 3. But if you make an item stack with this data it will work in minecraft.  Like new ItemStack ..

Link to Minetweaker 3 script here http://pastebin.com/JBUyGE7a

it has custom pages filled with all the info provided by a spreadsheet I found that one of you guys compiled. I linked the spreadsheet a few posts above.

![screen shot 2015-12-08 at 12 11 18 am](https://cloud.githubusercontent.com/assets/6987027/11648251/3720ae9e-9d40-11e5-890f-8620dfb5d20a.png)

**Comment by ghost** [comment]
OF course is not the proper 100% great and fancy plus it doesn't remember the last page I opened but AT least I have all the info I need right in the game . I called it Brewer's Manual tentatively . Anyway. Whoever is using MT3 can use the above script and will work fine. Is crafted using an apple and a book.

**Comment by labpaw** [comment]
For the books I suggest to use Guide-API mod(http://minecraft.curseforge.com/projects/guide-api?gameCategorySlug=mc-mods&projectID=228832) as soft-dependency. With this mod you can create any book you like and make it look as you want. Soft-dependency basically means that books will be enabled only if user have Guide-API mod. You also can make Growthcraft auto-download Guide-API.

**Comment by ghost** [comment]
Id rather have them make their own stuff no extra apis needed for a book lol

**Comment by spannerman79** [comment]
Guide-API is not Unicode friendly. So no

**Comment by Alatyami** [comment]
We are going to have own books that do not depend on other mods. We
generally frown on cross mod dependencies as we do not want to force
another mod on the user that they might not want to use.

**Comment by ghost** [comment]
@Alatyami :+1:

**Comment by Ar97x** [comment]
A idea for the book is following Agricraft example: you unlock things as
you make them, like if you make a Apple Cider for the first time, the
recipe shows up on the book and it also shows the combinations you might
wanna try. And I like the thought of making books for each module, so
people can play everything without having to look at Wikis. For Cellar
Book, I suggest using a book and a bottle of any liquid from the mod.

**Comment by Ar97x** [comment]
Or we could do like TiC and make the books spawn in your hand as soon as
you make a Fruit Press, a Brew Kettle or a Fermenting Barrel.

**Comment by Sunconure11** [comment]
Close as https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/178 will do it.
