### ISSUE TITLE
suggestion/idea/feature/module: growthcraft/minecraft  seasons  and seasonal crops + Farmer's Alamanc book

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#168]
This is a fictional module that is all about adding seasonal aspects to Minecraft and growthcraft. The simplest method is adding 3 seasons: "Sunny", "In-between",  and "Rainy" . 

In Sunny season the weather  is clear with  no clouds if is not raining, rain lasts short time and rains very little, days are longer and nights much shorter. During  Rainy season the weather is mostly rainy, always cloudy, rain lasts longer, days are shorter and nights much longer. The In-between season is identical to regular Minecraft. 

How does time work in minecraft? Day cycles follow a 0 - 2400 time period then back to 0. 0/2400 = sunrise, 6000 = noon, 12000 = sunset, 1600 = midnight. Following this logic each season has exactly 24 full day night cycles (aka days). So every 24 days season will change up to Sunny then In-Between, then Rainy, then In-Between, then Sunny and so forth forever.

How will time work during seasons? Pretty simple actually.  If you are in Sunny and is day time the cycle is slowed down by 2 in real time but the time passes same way is just it appears much slower to us. And conversely the night cycle is sped up inversely proportional thus keeping the overall day / night time in Minecraft constant. 

Now in order for you to keep track of time you craft an  item called a Solar Dial. This item has to be placed under open sky. When clicked during day time will tell you the current day / season like so Day 5 Rainy season. Note that while days go from 0 to 24 ,  0 and 24 are essentially same thing so in the information there is no 0 only 1 - 24

Some crops prefer Sunny , some crops prefer Rainy. All? (or most) crops grow in the In-Between season. Furthermore some plants such as grape vines will not grow from seed until the season is Sunny but will not produce grapes until the season is Rainy. So is a bit of a tricky thing there. If you plant the crop at the end of Sunny season then you must wait all the way until next Sunny season for the vines to grow. Or pumpkins want to be planted in Rainy but will produce Pumpkins in Sunny.  In order to help you with all that there is a special book called Farmer's Alamanac which lists what grows when and when to plant each type of crop.

**Comment by PitchBright** [comment]
Not to shoot the idea down, but I don't see this as a GrowthCraft thing, nor should it be. It's more of a Time, World, Weather, Temperature thing. GrowthCraft is about taking a resource, and introducing mechanics and procedures between the resource and the end-product.

The idea is great, though.

That said, there are a few mods out there, that you can use (and would have to use) in combination with one another, that will achieve the desired effect you're after (plus more). And with that in mind, I'll let you know now, once you start down this road, you're looking at a monumental configuration job. Imagine a year or more of research and configuration entry… assuming you're looking to do a half-way decent job of it. I say this, speaking from experience. My use of the word "monumental" is understating the task.

**Comment by Sunconure11** [comment]
I don't think seasons would fit in this mod, but, we could integrate with mods that do have seasons.

**Comment by ghost** [comment]
no worries :)
