### ISSUE TITLE
Possible idea regarding the handling of certain animal and plant products in the future

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#169]
Since some of the modules have plans for items that would drop from multiple mobs from various modules, I have proposed an idea to make this work without requiring say, 5 types of fur. If we add a fur item for instance, it should be handled by the core mod, and only become useful and visible when a submod that uses it is installed.

Plus, it would make the modules able to function a bit more on their own. Players won't need to run the tundra module to play with say, the desert module, or even some of my ideas for the marine module. This could apply to many other modules aside from tundra, desert, and marine.

**Comment by Sunconure11** [comment]
Me and Pitch had a convo regarding this. Maybe this could be handled by a coremod, which handles all of the animal drops?

**Comment by IceDragon200** [comment]
@Sunconure11 We can do this via existing forge hooks, see the milk module calf stomach drops.
