### ISSUE TITLE
Entomophagy module?

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#17]
I showed some friends that I was aiding with this, and it ended up evolving into a conversation about an entomophagy module. Would anyone be interested in a concept for a module that expands upon the use of insects, as well as add other stuff, such as earthworms, and a composter?

Maybe the bees module could be merged into it as well.

**Comment by Ar97x** [comment]
Insects? Maybe. If we can make it interact with agriculture or fishing it
would be really cool. Like Humus production, with a tax of growth
acceleration on crops planted on it. But stuff like butterflies of Forestry
is pointless to me.

**Comment by Sunconure11** [comment]
I'll write some concepts for this module, as well as some other modules that have been suggested.

**Comment by Sunconure11** [comment]
I'll make some interact with agriculture, whether it be destroying your crops, providing buffs, and so on.

**Comment by Sunconure11** [comment]
https://github.com/alatyami/Growthcraft-1.7/wiki/Growthcraft-Entomophagy-(Concept)

**Comment by Alatyami** [comment]
This will have to be for MC 1.8. With the release of 1.9 we'll be looking to update GC to 1.8 Forge. I plan on completely rebuilding GC for 1.8 from the ground up with dictionaries and all the new methods or mod development. I'll see about back porting this to 1.7.10, i.e. growthcraft 2.x

**Comment by Ar97x** [comment]
Well, that's true, the first priority we need to have is porting it to
1.8.x. But keep it updated on 1.7.10, it's hard for players and modpackers
(neologism) to move totally to a recent version.

**Comment by SynfulChaot** [comment]
I'd put the priority on 1.7.10 as that's where the current community is at and many intend to skip 1.8 entirely.

**Comment by Alatyami** [comment]
I agree but most of the mod is written for 1.6 and a lot of code is outdated.  Definitely still going to fully support 1.7.10.

**Comment by axlegear** [comment]
Maybe a bit of a necropost but I would love a bug-mod.  However I have no intention of using 1.8 anytime soon...

**Comment by Sunconure11** [comment]
@axlegear Maybe sometime on 1.8.9 I could see about working this out, even though this is necromancy. I do have some minor ideas. Silk anyone?

**Comment by IceDragon200** [comment]
@Sunconure11 "Growthcraft", not insect/animal/creature craft, this idea would be suited for a different mod :)
