### ISSUE TITLE
Growthcraft Leather Module (concept idea)

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#170]
Tannery expands the world of leather adding a bit more related content.

New Items:
Tannin = A liquid made out of leaves, seeds, saplings, grass and soft plants (not wood or bark). Is used in treating animal skins. Is made from 1 Water Bucket and enough soft plant material in the crafting grid shapeless. Leaves are the best to use. 4 leaves 1 water bucket. Or something like that. 
Hide = Sheep, Horses, Pigs will now also drop Hide when killed which must be processed into leather using Tannin before being useable.  By default hide is not useable in anything other than making Rawhide and Sheep Rug. 
Rawhide = Decorative item crafted from Hide. Rawhide can also be used to craft a drum using wood.
Sheep Rug = Decorative item crafted from White Wool and Hide in a TNT like pattern. 
Fish Leather = This is leather processed from fish skin. It is considered ore:leather so anything using leather will be able to use Fish Leather.
Treated Leather = an improved leather that is made using Leather and Tannin. It can be crafted into armour that is as durable as leather but as protective as Iron.
Drum = Three different sized drums each with their own pitch. Crafted from wood and rawhide.
Tanning Barrel = A sideways barrel like block used in the tanning process. It has an input, a liquid and an output slot.  Right clicking on it with a tannin bucket will fill it up with tannin. Right clicking on it will open it's GUI showing input, how much tanning is inside and output. The tannin is 2 buckets worth.
Saddles = Can now be crafted using Treated Leather and Rope.
Coracle (Leather Boat) = a lightweight boat that can easily be picked back up by hitting it as it drops itself. It does not break on impact like wood boats. It is crafted using sticks and Treated Leather.
Bedroll = A portable sleeping bed that is can be used to sleep anywhere by right clicking on it but does not reset spawn point. If monsters are nearby you will not be able to sleep. It is crafted from  sheep skin, raw hide and rope. 

Process
1. Tannin is made using water bucket and plant material. The result is a Tannin Bucket.  A fluid that gives Poison II if swimming in it. 
2. A Tanning Barrel  is crafted and placed in the world.
3. Tanning Barrel  is filled with Tannin liquid and hides (or fish or rotten flesh see below). The Tanning Barrel  will start spinning and the tannin is absorbed into the hide creating leather as output. The process is quite fast much like brewing. If leather is placed as input inside a Tanning Barrel  it will become Treated Leather as output however this takes as long as fermenting in a cellar barrel and requires several refills of tannin. 

Rabbit hide can be placed in the Tanning Barrel  and will convert to 2 rabbit hides into 1 leather consuming a bit of tannin.

Rotten Flesh can also be converted to leather but much slower pretty much same as creating Treated Leather.  

Fish Leather can be produced from Fish placed in the Tanning Barrel  same speed as regular hide processing although 4 fish will be consumed when 1 leather is produced.  If not enough fish nothing happens. 

What do you think? Good? Bad?

**Comment by PitchBright** [comment]
+1 from me, for the idea of adding mechanics for the hide to leather process.

I've never made leather IRL, but I've watched a lot of vides, and read up a lot on it… so I think some of things you are proposing are a little off or are whacky. I would probably contest you on that stuff… so I'm not sure I understand the rationale behind some of the features you're proposing here… but overall, I'm definitely a proponent of the idea.

Support!  :)

**Comment by Sunconure11** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/GRC-Tannery-(Concept)

Created a page for it.

**Comment by Alatyami** [comment]
I would add some kind of leather tool for making the saddle. Maybe a swivel
knife? Saddles shouldn't be too easy to make as in real life it is an
undertaking.

**Comment by Sunconure11** [comment]
Added a swivel knife, and a few other things.

**Comment by Sunconure11** [comment]
I might see if I can sneak a texture in for sinew when I make the water buffalo and knifebush textures

**Comment by ghost** [comment]
@Alatyami  sounds good. saddles should be a lot of work

**Comment by ghost** [comment]
@Sunconure11 nice :+1: 

I love the sinew idea.  I was also thinking sinew can be crafted into glue using the Brewing Cauldron and water . A bunch of sinew boiled up in water should give up a bucket of glue which can be crafted into 3 glue bottles . Glue liquid gives highest Slowness effect when swimming in it. Glue bottles are same as slimeballs.

**Comment by PitchBright** [comment]
Is that how glue is actually made, boiling sinew in water?

**Comment by Sunconure11** [comment]
Some forms of glue are made that way, yes.

**Comment by Sunconure11** [comment]
https://en.wikipedia.org/wiki/Animal_glue

**Comment by ghost** [comment]
@PitchBright  i think some glue is made from soft animal tissue especially tendons or sinew or skin parts but also bone that has been softened and shaved down into little pieces

**Comment by ghost** [comment]
In reality  glue could also be made form hide, bone and raw meat. I wanted to keep it sinew only to make it much more rare (only four legged animals should drop it). I like sinew idea cause is both a string and if you guys like this idea a slimeball if processed.  

I am still thinking about this module and how it could work better. I could probably help with stuff too.

I am thinking Tannin could also be made in the brewing cauldron from plant matter and water.   And different plant matter is consumed faster or slower in the brewing process. Saplings are probably the best then leaves then regular plants. And if you're too close to the cauldron when brewing Tinnin you will get nausea effect in the area since it smells really badly. 

What you guys think?

Is somewhat close to reality. The Tanning Barrel is actually real thing . http://www.goldenkirat.com/media/factory/11-Nov-2013-13-14-07-fact4.jpg You pace hide that has all hair and flesh removed in there and  let it sit in Tannin for months to soften it and turn it into leather.

**Comment by ghost** [comment]
This mean that the brewing cauldron might have to be moved to the core then disabled until either this module or cellar is present. I don't know . I have noticed Growthcraft tends to do this with a few things.

**Comment by PitchBright** [comment]
The barrel is the way to go, just like IRL. We've got the model for it already too. We would just need some sort of action that; when a barrel is placed upright and (action performed) the top face of the barrel is removed. From there, the user dumps water into the barrel (cauldron code for that), and places plant matter (oreDict "tanninMatter"). Then it's just a waiting game.

**Comment by ghost** [comment]
@PitchBright  the barrel is almost same as the regular barrel except is sideways like in the picture i showed you . and has a big square hole in the centre 

just take the regular barrel but move it sideways and add some form of supports underneath then add that window. 

the reason the barrel has to be different is because it's a completely different machine and should not be confused with the fermenting barrel. plus the gui is also different .

for example like this
![image](https://cloud.githubusercontent.com/assets/6987027/11683786/255ac4a0-9e3b-11e5-9c0f-8bf54671dd62.png)

**Comment by ghost** [comment]
@PitchBright  also a tanning barrel / tanning drum spins when is in use see for ex this video https://www.youtube.com/watch?v=Fu0Eg0jxst0

you can see the tannin or whatever liquid they use being poured out at 6:30. there are about 20 or so chemical techniques all involving this barrel and is usually made from wood or some weird plastic because the chemicals are too corrosive for metal

**Comment by spannerman79** [comment]
> (oreDict "tanninMatter")

Tannnin is actually a liquid once in the barrel, so it actually should turn water (in cauldron/barrel/etc) + plant material into `liquidTannin`

Once defined as a liquid it can be stored easily enough by any other mod as its defined as a liquid.

**Comment by ghost** [comment]
seems growthcraft got the liquid thing figured out quite nice .you can store pretty much anything in yeast jars and barrel no kidding . i even put lava in there lol. nothing happens  but is funny that you can. even in the liquid bar in gui you can see the actual liquid. tannin is light brown in real life but you can probably make it green cause there is nothing green in growthcraft.

**Comment by PitchBright** [comment]
I meant that "whatever a player wants to define as something that can be processed into tannin"… should be oreDict'd as "tanninMatter"

**Comment by ghost** [comment]
oh i see. yea that could work. but different plant material has more or less tannin therefore it consumes more or less of that item. so saplings would be like 20 or so saplings per bucket while something like leaves is more like 30 leaf blocks per bucket. so there has to be a bit more than just adding to oredict . there needs to be anyhing that is sapling oredict is x 1, anything that is leaf oredict is x2 anything that is growable is x3 consumption

**Comment by PitchBright** [comment]
Yeah true. Best bet is to make the Barrel configgable, like the other stuff (ferment, kettle, press). Then ya do away with oreDict.

**Comment by ghost** [comment]
@PitchBright  No but I see your point of what you're saying. I have used this system in my single player world in Minetweaker 3 scripts I made it so all meats for example can be used in all meat recipes by adding all meats to ore:foodMeat and then change the recipes to use ore:foodMeat instead of the actual meat item. It makes more sense.  
edit: for ex witchery stew i want to use other meats from et futurum mod for example so I added those meats too. sorry a bit offtopic but I get what you're saying.

**Comment by PitchBright** [comment]
Yeah, same here. I think that's why I automatically thought "oreDict". But I do prefer the configgable stuff that @IceDragon200 has done with the Press and Fermenting Barrels and Brew Kettles. It puts so much power and flexibility in the hands of the user.

**Comment by PitchBright** [comment]
I see what you're saying about the Barrel. I'll defer to your knowledge on the matter. I was just going by some "survivorman" videos that I remember watching awhile back. Those guys tended to use normal barrels for their purposes. https://www.youtube.com/watch?v=CgK3SEeZNEk

**Comment by Sunconure11** [comment]
I'm wondering if this should be merged into the butcher module, and turned into a large module just based around animals and their products.

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Butcher-(Concept)

**Comment by PitchBright** [comment]
Naw, it's too broad.

**Comment by Ar97x** [comment]
Well, there were a lot of research around this and the concept seems really
amazing, I took almost 10 minutes to read all the comments, so I absolutely
support it.

**Comment by Sunconure11** [comment]
Closed. I'll re-open this at a future date when this can be looked at and formulated more.
