### ISSUE TITLE
Release Version 2.4.0

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#171]
I am queuing up the release notes. I'd like to cut 2.4.0 before Christmas. If you have a ticket/issue that you do not think can be done by Dec 21st please move it to version 2.5.0 or 2.4.1 depending how close to completion you are.

**Comment by IceDragon200** [comment]
You can pull an idea for the release notes from the #130 Notes section

#144 I'm waiting on feedback to see if its fixed
#158 Will require a bit of movement, I don't think I want to introduce yet another breaking change so late

**Comment by ghost** [comment]
The rope not working on custom fences probably requires some heavy changes so you should move that for 2.4.1+

**Comment by Alatyami** [comment]
Pulling together the release notes now.

**Comment by spannerman79** [comment]
Make sure that on curseforge you put into the top of that change log that Forge 10.13.4.1566 is needed.  Most won't read through the whole change log that was in the PR
