### ISSUE TITLE
[REQUEST] Texture Pack Formatting

### ISSUE THREAD

**Issue by Oraiz** [GrowthcraftCE/Growthcraft-1.7#172]
Hello,

I would be really interested in trying to get all the file paths for this mod, as I'm trying to slowly cobble together a 64x texture pack that covers every mod I'm using for my own modpacks.

If it would be possible to provide the structure I'd need for a texture pack for all the different modules etc. it would be wonderful, or tell me how I'd work it out myself.

e.g. "/growthcraft/assets/textures/blocks/blahblahblah.png"

Thanks in advance for any help!

**Comment by IceDragon200** [comment]
@Oraiz https://gist.github.com/IceDragon200/b7b2aac018b946e7f051

**Comment by Oraiz** [comment]
Thank you very much for the prompt reply, however this doesn't seem to work for me (unless I'm being really stupid and missing something - I've checked spellings etc).

e.g. I have the bamboo leaves in "/growthcraft/assets/grcbamboo/textures/blocks/leaves.png" and "/leaves_opaque.png", but they're just showing the 'vanilla' textures.

EDIT: Yeah I was just being really stupid: should be "/assets/grcbamboo/textures/etcetc".
