### ISSUE TITLE
Dumb idea regarding bottles

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#173]
Would it be possible to create variants of each form of booze in the future that can be placed as decorations?

**Comment by IceDragon200** [comment]
@Sunconure11 Had the idea, along with a Wine Rack, however I swept under the rug as a duplicated effort, since I believe other mods already have similar furniture (Bibliocraft comes to mind).

Though its worth considering, WDYT (@ everyone)

**Comment by Sunconure11** [comment]
Yeah, Decocraft and Bibliocraft can be used to create such things. But I still think its a good idea.

**Comment by Sunconure11** [comment]
Maybe between the production of the next module, I can create models for both.

**Comment by Alatyami** [comment]
I like the idea ... maybe out of bamboo/GC only materials?

**Comment by Sunconure11** [comment]
For the wine rack, yes. Bamboo, malice, plus vanilla woods, and the wood of most future trees.

**Comment by PitchBright** [comment]
Rename this to "Feature Request: Booze Rack Block" or something. Or close it if you're not going to do the model.

**Comment by Sunconure11** [comment]
Closing until I am ready to make the wine racks and such, as I won't put them in this build.
