### ISSUE TITLE
Weird bug with water bags and the everful urn from Thaumic Exploration

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#174]
It seems you can fill the bag from the urn, but, thats not the issue. When I do so, the bag turns white.

**Comment by IceDragon200** [comment]
The Water Bag's Item Damage was probably modified, does this happen with any other fluid related block?

if not, its probably a bug in Thaumic Exploration

EDIT: 
It's a bug.
https://github.com/Flaxbeard/Thaumic_Exploration/blob/master/java/flaxbeard/thaumicexploration/block/BlockEverfullUrn.java#L147-L148

``` java
new ItemStack(item, size[, damage])
```

**Comment by Sunconure11** [comment]
Is there anything we can do to work around this, or are we going to have to work with the TE devs?

**Comment by IceDragon200** [comment]
@Sunconure11 Its a bug on their side, they shouldn't be creating a new item stack there

They could copy the stack, or just modify it in place

``` java
else if (entityPlayer.inventory.getCurrentItem().getItem() instanceof IFluidContainerItem) {
// what they have - boo boo
    ItemStack newStack = new ItemStack(entityPlayer.inventory.getCurrentItem().getItem(),1);
// could do this - preferred (since this also copies the nbt)
    ItemStack newStack = entityPlayer.inventory.getCurrentItem().copy();
    newStack.stackSize = 1;
// or this - kinda works, but eh
    ItemStack srcStack = entityPlayer.inventory.getCurrentItem();
    ItemStack newStack = new ItemStack(srcStack.getItem(), 1, srcStack.getItemDamage());


    entityPlayer.inventory.decrStackSize(entityPlayer.inventory.currentItem, 1);
    ((IFluidContainerItem)newStack.getItem()).fill(newStack, new FluidStack(FluidRegistry.WATER, 1000), true);
    if (!entityPlayer.inventory.addItemStackToInventory(newStack)) {
        entityPlayer.dropItem(newStack.getItem(),newStack.stackSize);
    }
    world.playSoundAtEntity(entityPlayer, "liquid.swim", 0.5F, 1.0F);
}
```

**Comment by ghost** [comment]
@Sunconure11  just post the bug on their side and give the suggestions that @IceDragon200  has given see what they say

**Comment by Sunconure11** [comment]
Probably can't be fixed at the moment. I will close this.
