### ISSUE TITLE
Add in-game book for growthcraft: cellar

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#178]
Going to focus on increasing our in-game documentation. I recevied a private message on the forums suggesting using an in-game.

**Comment by Sunconure11** [comment]
I seriously think this should be tackled soon. I should say after the milk module is fairly stable. I suppose I could whip up a texture for the book when the time comes.

My reasoning for bringing this up again is that I decided to look at the 4chan thread for minecraft, and noticed that some users do not seem to know how all of the new brewing changes work.

Admittedly, I'm not overly fond of 4chan, but, listening to user feedback on more sites is crucial.

If you wish to see what has been written, check this thread. Press CTRL + F and type "growthcraft" to navigate faster.

http://boards.4chan.org/vg/thread/128585546/minecraft-general-mcg-stuck-in-a-tree-edition

**Comment by Alatyami** [comment]
I'm opening a branch for it today. Didn't realize we were on 4chan. Thanks for looking out there. User feedback is user feedback. I am going focus on ingame documentation and wiki documentation as well.

**Comment by PitchBright** [comment]
Let's close this down if it's not going to happen.

**Comment by Alatyami** [comment]
It's going to happen, I am having to learn how to do books ;) I'll open a
branch for it.

Alatyami

**Comment by PitchBright** [comment]
Okay, just trying to do some housekeeping on the git issues. Sorting out what's an actual issue, from stuff that is already covered in the wiki (concepts or otherwise), and also the stuff that is just people discussing ideas/daydreams/wishlists that there's no actual intent to execute.

**Comment by Alatyami** [comment]
I'm going to go ahead and close this. I'll make some books in the future, but need to think it out first with layouts and how the content will go.

**Comment by Sunconure11** [comment]
Alrighty.
