### ISSUE TITLE
OreDictionary bug causing java exception in server log

### ISSUE THREAD

**Issue by SniperHauss89** [GrowthcraftCE/Growthcraft-1.7#179]
Hi, I'm just reporting a little java exception I noticed in my server log as I was scanning it after updating you guys' mod as well as others and it said to report it to the mod author so I am :).

It's nothing game breaking but I thought you guys might want to know anyway.

log: https://goo.gl/49YK69

Forge 1614
Growthcraft 2.4.0

**Comment by Alatyami** [comment]
Thank you for reporting it, we'll look into it.

**Comment by SniperHauss89** [comment]
No problem always glad to help.

**Comment by IceDragon200** [comment]
@SniperHauss89 Is that the only one? Also check #180 for a test build :smile:

**Comment by SniperHauss89** [comment]
I didn't check my GitHub for a couple days... anyway yes it appears it was the only Java exception specifically for Growthcraft.
