### ISSUE TITLE
Growthcraft-1.8

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#18]
With the release of MC 1.9 we need to start thinking about Forge for 1.8.

Forge 1.8 support will be in GC 3.0 and officially launch the Growthcraft Community Edition

**Comment by spannerman79** [comment]
I'd go for this as long as there was continued support for MC 1.7.10 until Sponge is ready.

**Comment by labpaw** [comment]
I would suggest you to skip 1.8 and wait for Forge 1.8.8. And 1.7.10 should be supported until mods actually start moving to 1.8.x

**Comment by Alatyami** [comment]
With the announcement of locking the 1.7.10 recommended, I have created the 1.8 repo. Invites will go out shortly. 1.7.10 is still the focus.
