### ISSUE TITLE
Rice is Messed Up - Realistically Speaking

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#181]
Rice is not something that should be grow-able simply by putting it on tilled+irrigated land.  Rice patties grow under water - realistically about 3 to 6 inches below the surface.  Sure, it's nice to say that we can have rice in the game, but if someone is going to go through the trouble of adding it, shouldn't it be accurate - isn't that a part of what Growthcraft is about?

Thank you for your consideration(s).

Respectfully sent,
thefirstgamemaster
_Uses Minecraft 1.7.10_

**Comment by Sunconure11** [comment]
Upland Rice is a thing, and I'm pretty sure various cultivars of crops were planned a long time ago, though I am not sure what became of that plan.

https://en.wikipedia.org/wiki/Upland_rice

And the rice in this mod is a close approximation to "generic rice" without going into either deepwater or upland rice territory.

https://en.wikipedia.org/wiki/Deepwater_rice

**Comment by ghost** [comment]
Acknowledged.  Unfortunately, this answer will not likely sate the desire of my Okinawan (Japanese) counter-part (a real gardener) to play in-game with something more familiar to them.  Upland Rice is, apparently, not a thing in their culture...

**Comment by spannerman79** [comment]
To cater for everyone will get to the stage where people will be **only** be able to just have the mod GrowthCraft due to forge item ID limits.

There _has_ to be a limit at some point.

**Comment by ghost** [comment]
Agreed.  I'm not suggesting to cater at this point... I'm just thinking "out loud" if you will.  Sorry to bother you all about this...

**Comment by Sunconure11** [comment]
The item ID limit is so high that it won't be a huge problem, plus we can use metadata and such. Blocks are more limited, but, we are unlikely to hit that limit with this mod.

Also, me and pitch are... reworking some ideas and such. We might be able to figure this rice issue out with the next module plan though.

**Comment by ghost** [comment]
Would it be included in a 1.7.10 release, or are you moving on to newer versions?

**Comment by Sunconure11** [comment]
Obviously 1.7.10. While 1.8 has a sudden burst of activity due to BTM, most likely this mod will be on 1.7.10 for quite some time. A 1.8 port appears to be in progress, but, so far, nothing has been made for it. I'll talk to Pitch about this to see if this can be handled when we work on the next module (currently we are working on one now, and we are almost done with stuff like textures and such)

**Comment by ghost** [comment]
This would be awesome!  Is there some kind of notice that I will get, or is it (I presume) up to me to watch for it?

**Comment by Sunconure11** [comment]
You will see a pull request for the next module, then we will possibly see about dealing with this rice conundrum. No guarantees, but, due to the nature of what is planned afterwards, it can be at least considered.

**Comment by ghost** [comment]
Awesome!  Thank you for your time!

**Comment by spannerman79** [comment]
> The item ID limit is so high that it won't be a huge problem, plus we can use metadata and such. Blocks are more limited, but, we are unlikely to hit that limit with this mod.

Yes but who plays modded minecraft with just one mod?  The typical number of mods are in the 60 - 200 range.  So forge is already at some limits already.  Go too far to satisfy every little whim and modpacks will have to cull/remove mods to make room.  If a mod that adds blocks that are only for "realism" (come on its minecraft) then personally I know what I would be doing with that mod....

**Comment by Sunconure11** [comment]
Good point, but, at this point, this mod probably cannot breech the block limit unless you are near it already. I'm running this in a modpack with 130 mods with no problems.

**Comment by PitchBright** [comment]
There's already plans to address this process, as per the comments in #150

**Comment by IceDragon200** [comment]
As stated by @PitchBright, this will be addressed later, along with #150
