### ISSUE TITLE
Feature Request: Disable Discard Button on GUIs

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#182]
If possible (and if easy to do), it'd be great to have the option as a server admin, to be able to disable the "discard" feature on barrels and fruit press and brew kettle (etc), to prevent players on the server from being able to make fluids magically disappear.

**Comment by IceDragon200** [comment]
@PitchBright https://github.com/GrowthcraftCE/Growthcraft-1.7/commit/f94c2c7578278853dfb9ad4c4f8afd68634398ee

Sadly its apart of the grcmilk branch

**Comment by PitchBright** [comment]
Wicked, thanks for doing that.
