### ISSUE TITLE
Idea: Config setting to turn off potion effects on booze aside from tipsy

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#184]
This is based off of some convos between me and PitchBright. Also, this could work for hardcore packs.

**Comment by PitchBright** [comment]
He knows… we've already talked about it :-)

I was thinking configurability in terms of pick-and-choose what to change them to…. but now that you mention it, your idea here of a straight up disable option via .cfg would be wicked… if even possible.

**Comment by IceDragon200** [comment]
@PitchBright @Sunconure11 Added in the latest grcmilk build (13)

**Comment by Sunconure11** [comment]
This has been handled.
