### ISSUE TITLE
GrowthcraftCE/Growthcraft-1.8 Acceses Updated

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#189]
I opened up the default group member permissions on the 1.8 work. Report here if you cannot get into it. We still need to do the first commit. Before I did that I wanted to float it out there ... do we start from scratch or mod the Growthcraft-1.7 to work with Forge for 1.8? 

Let's hear the ideas / suggestions ...

**Comment by IceDragon200** [comment]
@Alatyami Shouldn't this be in the 1.8 repo?

I was planning to rewrite the mod from scratch, but its a huge undertaking

**Comment by Alatyami** [comment]
My plan was to keep it here until we comfirm everyone has access to GC-1.8 and poll the GC-1.7 repo watchers.

**Comment by Alatyami** [comment]
I was thinking of a rewrite for GC-1.8 as well.

**Comment by Alatyami** [comment]
Closing this one out. Permissions have been setup on the 1.8 repo for when we get there. If anyone else has issues with the 1.8 repo, catch me in IRC.
