### ISSUE TITLE
Pull in the requests/forks on Gwafu's repo

### ISSUE THREAD

**Issue by rikai** [GrowthcraftCE/Growthcraft-1.7#19]
Would be nice to pull in the pull requests from Gwafu's repository and some of the other forks so that we've got one primary 'community edition' with all the changes.

Current ones that i see are:
Gradle build files & mcmod.info: Gwafu/Growthcraft-1.7#5 (primarily the mcmod.info stuff)
A Hungarian translation @ [ender11hun/Growthcraft-1.7](https://github.com/ender11hun/Growthcraft-1.7/tree/patch-1)

**Comment by Alatyami** [comment]
Very true ... we'll have to come up with a plan for that.

**Comment by Alatyami** [comment]
I am reaching out to Gwafu to be added to his project and we can redirect people to here.

**Comment by Alatyami** [comment]
Message has been sent via reddit.

**Comment by IceDragon200** [comment]
Hi, I got the message and moved my PR over #20 :)

**Comment by Alatyami** [comment]
The last pull has been merged.  Until Gwafu gives me access to his repo, I'll check in one it every now then and then redirect them here.
