### ISSUE TITLE
Yeast jar is ginormous 

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#192]
If it's not too much work, can the yeast jar be knocked down to a more realistic size? Right now it's the equivalent of a bottle occupying the space of a cubic meter.

I can do a model and textures if needed.

**Comment by IceDragon200** [comment]
@PitchBright Sure, knock it down a few I modeled it after Thaumcraft's Jars

**Comment by Sunconure11** [comment]
Okay, this appears to have been handled. Should I close this now, @IceDragon200, @PitchBright?
