### ISSUE TITLE
[SUGGESTION] Configurable Fish Traps via user api

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#194]
This would allow for better integration with other mods that add their own fish.

Also, we could extend it even further by allowing players to set fish to be able to be only caught in specific biomes or biometypes (biomedictionary). The same could apply to loot dug up from fishing.

**Comment by Ar97x** [comment]
That's a good idea for the fishtrap module revival, if I get some time free
I'll work on the wharf structure.

**Comment by Sunconure11** [comment]
When/if you make the wharf structure, could you add it as a pull to the milk module being worked on? Just so it can be released in the next major build.

**Comment by Ar97x** [comment]
Sure.

**Comment by IceDragon200** [comment]
@Sunconure11 You can try the latest build (Build 8+) in the milk module, I've added the Fish Trap User Api, I'm going to add it to the docs now

[User Fish Trap Entries](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/User-Api-%282.5.x%29#fish-trap-entries)

**Comment by Sunconure11** [comment]
I think this has been handled. I will close it.
