### ISSUE TITLE
[SUGGESTION] shishi-odoshi model

### ISSUE THREAD

**Issue by gchpaco** [GrowthcraftCE/Growthcraft-1.7#195]
For context, https://en.wikipedia.org/wiki/Shishi-odoshi

The shishi-odoshi is that weird bamboo thing you see in traditional Japanese gardens; it makes a characteristic noise periodically and uses flowing water as a timer.  I think it would be awesome to have in GC bamboo, maybe emit redstone as a timer, or maybe just as atmosphere.

It may be better to target this at 1.8.

**Comment by Sunconure11** [comment]
I could probably model this around the same time as the wine racks.

IRL, it appears to be used to scare off animals. I think that could give it another functional purpose.

I have to finish Baykok for Totemic first before I do more models.

**Comment by PitchBright** [comment]
Can close this. #206 carries it.
