### ISSUE TITLE
Modpack Permission - The Feed the Creeper Pack

### ISSUE THREAD

**Issue by thor12022** [GrowthcraftCE/Growthcraft-1.7#196]
I'd like to add Growthcraft Community Edition to my modpack: The Feed the Creeper Pack. It will be available on the Technic Launcher and will be submitted to the Feed the Beast launcher.

**Comment by Alatyami** [comment]
Inclusion of the Growthcraft Community Edition in your modpack is approved.
Let us know if there are in incompatibilities.
