### ISSUE TITLE
Feature Request: Yeast configgable by Biome Name

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#197]
An additional option to config biomes by name (versus tag/type) would be handy. Especially for folks with hundreds of biomes who would like to isolate their yeast to specific biomes, where tags wouldn't do the trick.

**Comment by Sunconure11** [comment]
I second this.

Also, still no response from mDiyo.

**Comment by IceDragon200** [comment]
@Sunconure11 @PitchBright Added to the latest grcmilk build (10+ I think?)

**Comment by Sunconure11** [comment]
Alright, I'll close this then.
