### ISSUE TITLE
Interest check: RTG Support

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#198]
In the future, maybe after the milk module is finished, would anyone be interested in setting up support for the bamboo forest from this mod into RTG?

https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/448

**Comment by Sunconure11** [comment]
Check the latest comment, Ice, when you have the time.

**Comment by IceDragon200** [comment]
So we go le integration now, guess we can close this :)
