### ISSUE TITLE
Modpack Inclusion Request: Spilled Juice

### ISSUE THREAD

**Issue by slidingmike** [GrowthcraftCE/Growthcraft-1.7#199]
Semi- Public Pack available via ATLauncher.

Pack code: glassofmilk

Mod List Link: https://www.atlauncher.com/pack/SpilledJuice

**Comment by IceDragon200** [comment]
@slidingmike  Permission is hereby granted for you to use Growthcraft in your modpack, if you have any trouble, issues or general questions feel free to open an issue here on github, or leave us a message in the #Growthcraft irc channel on esper.net
