### ISSUE TITLE
Add portuguese translations

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#2]

**Comment by Ar97x** [comment]
Do you know where is the lang files?

**Comment by Sunconure11** [comment]
Here is an example. Following this, you can find the others:

https://github.com/alatyami/Growthcraft-1.7/tree/master/src/resources/assets/grcapples/lang

**Comment by Ar97x** [comment]
Thanks. I always forget where it is lol.

**Comment by Ar97x** [comment]
I've forked and translated one already, what should I do now? Create a _new
branch_ for this commit and start a pull request?

2015-07-21 16:10 GMT-04:00 Joseph Caleb Jones notifications@github.com:

**Comment by Ar97x** [comment]
I never did it directly on GitHub

2015-07-21 19:08 GMT-04:00 Victor Diehl vdiehl97@gmail.com:

**Comment by Sunconure11** [comment]
Well, you are a contributor, you can do it directly.

**Comment by Alatyami** [comment]
Go ahead and either modify the development branch or create your own translation/portuguese branch. Language files rarely break anything.

**Comment by Ar97x** [comment]
Did it. I will keep an eye for further translation on what's coming next.

2015-07-21 20:01 GMT-04:00 Alatyami notifications@github.com:
