### ISSUE TITLE
Crash when adding bundled Growthcraft

### ISSUE THREAD

**Issue by nmarshall23** [GrowthcraftCE/Growthcraft-1.7#202]
This crash doesn't happen if I add the Complete jar. 

If I just add all of the jars from the bundled zip, I get this crash.
http://pastebin.com/iBRaWUqe

When I removed the bees jar I get:
http://pastebin.com/CTbfKmB5

I get the same Exception with just the core and api jar.

**Comment by Sunconure11** [comment]
@IceDragon200 Might want to look into this, I am hearing multiple reports of this issue.

**Comment by PitchBright** [comment]
@nmarshall23 

I was able to load the game with "growthcraft-1.7.10-2.4.0-complete.jar" fine, no issues.

What do you mean by "If I just add all of the jars from the bundled zip"?

EDIT: Disregard… I see you're talking about the CurseForge download.

**Comment by IceDragon200** [comment]
@Sunconure11 @PitchBright @nmarshall23 Remove the API jar.
The API is always included with the core, so you don't need the extra jar

I've added this finding to the [FAQ](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/FAQ---Troubleshooting#nosuchmethoderrors)

Please do share with users experiencing the same problem and help spread the word, sorry for the inconvenience

**Comment by nmarshall23** [comment]
> Remove the API jar.

Hmm now I get a new error. http://pastebin.com/LN7uNRCu
That that test I had just core and bamboo jar installed. The same error happens with just core.

**Comment by IceDragon200** [comment]
@nmarshall23 That error is from RotaryCraft though, did you try Growthcraft alone and get the same error?

**Comment by nmarshall23** [comment]
@IceDragon200 You are correct. The game loads fine when I pulled RotaryCraft and add in just the core. I left in a buch of Reika's other mods. 

But that's a tangent. My bug report is that the Complete build jar works fine. The Bundled one conflicts with RotaryCraft.

I've also open a bug report with Reika. He might have insight into what could cause this crash. 

Are there build instructions to build the bundled version? I am a java developer.

**Comment by IceDragon200** [comment]
@nmarshall23 Surprisingly there isn't a guide in the wiki... I thought I wrote one.

Here we go:
https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/How-to-Build-Growthcraft

I don't build the a bundle, I only cut the complete jar apart to create the modules via a ruby script, if you can rewrite the process in gradle that would be swell :smile: 

My primary language is ruby, so I haven't dug around gradle enough

**Comment by ReikaKalseki** [comment]
[This is entirely Forestry's error](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/616#issuecomment-182089922).

**Comment by IceDragon200** [comment]
@ReikaKalseki Hey, nice to have you here.

@Sunconure11 
Something is telling me we should probably handle Forestry integration ourselves...
I'm still up for it since there are a few items that need changing in that plugin, and it would be better if we had control over those recipes.

**Comment by Sunconure11** [comment]
Go ahead and add some more support for Forestry in the dev builds if it will fix this.

**Comment by ReikaKalseki** [comment]
> Go ahead and add some more support for Forestry in the dev builds if it will fix this.

Forestry needs to remove or fix their broken handlers. Nothing you do would fix it.

**Comment by IceDragon200** [comment]
Okay, responded to their issues and threw in a request

Hopefully they respond quickly :O

**Comment by IceDragon200** [comment]
Now that everything has been hopefully resolved, and we've learned our listen about shipping the API jar with the bundle, I believe I can close this.
