### ISSUE TITLE
Modpack Inclusion request: Bevo's Tech Pack Reborn

### ISSUE THREAD

**Issue by b0bst3r** [GrowthcraftCE/Growthcraft-1.7#203]
Bevo originally had permission to include Growthcraft in his BTP pack but that was a while ago (old link - https://www.atlauncher.com/pack/BevosTechPack# on page 12)

Since I'm renewing the pack on his behalf and since the pack has probably changed hands since, can I include GC in BTPR.

Preliminary mod list is https://github.com/BevoTechPack/BevoTechPack/blob/master/BTP15/Preliminary_Modlist.txt subject to change before launch.

**Comment by IceDragon200** [comment]
@b0bst3r  Permission is hereby granted for you to use Growthcraft in your modpack, if you have any trouble, issues or general questions feel free to open an issue here on github, or leave us a message in the #Growthcraft irc channel on esper.net
