### ISSUE TITLE
Modpack Permission - Still Thinking About Name

### ISSUE THREAD

**Issue by Ravin890** [GrowthcraftCE/Growthcraft-1.7#204]
Decided to finally ask for permission for my modpack, which I shall add to the curse launcher soon, and I will probably think up a name. I am thinking of calling it "Deadly Encounters"

Here is a list of my mods: https://docs.google.com/spreadsheets/d/1hjUU7aHuc1bl9mysIfQtMYFeeV4WHuyOOSeQeAJAxfs/edit?usp=sharing

*I will probably post name here when i finally confirm what i want to name it.
*Trying to figure out how to add tags like modpack...

**Comment by IceDragon200** [comment]
Permission is hereby granted... ah forget it just click the fancy image below.

[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
