### ISSUE TITLE
Bamboo needs some love!

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#206]
Also bees, but that's a different story.
## Suggested Features
- Bamboo Weapons, Tools, Armor?
- #195 Shishi-Odoshi
## Fixes, Integrations
- #158 Rope doesn't attach to bamboo fences
- [Tinkers Construct tool parts](https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/200#issuecomment-183716490)

@Drakoflame @Sunconure11 Discuss bamboo stuff here

**Comment by Sunconure11** [comment]
I had an idea for an entire bamboo expansion that I want to tackle around the next module after milk. However, if you are interested...

> A shishi-odoshi is a fountain, used for startling off animals. It can emit a redstone signal, and serve as a timer as well, in addition to startling off mobs from your stuff. It must be filled with water first, and when it runs out of water, it must be filled again. Rain can also fill it.
> 
> Bamboo slips can be made from bamboo, and can contain up to two pages of text. Slips can be combined many times though, to rival the length of books (two slips + a piece of string, and so on into infinity). However, this will take a long time. Bamboo slips are crafted with 1 ink sack (any ore dictionary black dye can be taken), 1 feather (any ore dictionary feather can be taken), and 1 bamboo strip. They can then be combined with other bamboo slips for longer books and more info (will save existing info) using 2 bamboo slips and 1 piece of string. Unlike a book, they can be cleaned of any ink using a water cauldron, and then you can write on it again. This will however, also strip information on the author as well.
> 
> Bamboo strips can be made from bamboo logs, which can be turned into bamboo hats.
> 
> Shinai are created with 1 stick and two bamboo strips. They do not deal a lot of damage, but, are very durable. (about as much damage as a golden shovel)
> 
> Silambam staffs are made with 1 stick, 1 bamboo, and 1 bamboo strip. They do as much damage as an iron sword, but, have a small chance of shattering upon use, and have the durability between stone and iron. They have a high swing speed. (as much damage as an iron sword)
> 
> Bo staffs are made with 1 stick, and two pieces of bamboo. Very durable, and deals a bit of damage. Held with both hands. (as much damage as a stone axe)
> 
> Tiki torches are torches created from bamboo and bamboo charcoal.

**Comment by Sunconure11** [comment]
Bamboo slips are based off of these, BTW:

https://en.wikipedia.org/wiki/Bamboo_and_wooden_slips

**Comment by Sunconure11** [comment]
Nvm, I did write it down.

**Comment by Sunconure11** [comment]
Also, how far did you get into pushing the fix out to milk? I shouldn't rush you, but, I am waiting on it for something urgent today.

**Comment by IceDragon200** [comment]
@Sunconure11 ~~Updated~~ Added new build, I'm having dinner, sorry for the delay

**Comment by spannerman79** [comment]
> Tinkers Construct tool parts

There is something that I'd like to say that might not be well received.

The dev for Tinkers Construct has moved onto 1.8.9 mod development.  Meaning that if there is anything that is required for integration on TC won't happen.  As stated on mcf.net the dev will only do fixes and nothing else for the 1.7.10 variant of TC.

I'd suggest that you move TC parts into the 1.8 branch.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/6j9q2pxau0n27ak/bostaff.png?dl=0

Tried my hand at a bo staff

**Comment by Sunconure11** [comment]
@IceDragon200 

https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/448#issuecomment-185869924

**Comment by IceDragon200** [comment]
@Sunconure11 e627d76

**Comment by Sunconure11** [comment]
So we have writing surfaces, hats, new weapons, torches, and a fountain to scare away animals. Anything else we can do with bamboo? Bamboo fiber is a thing, but, the chemical processes required to make it might not be possible within Growthcraft's tech range.

https://en.wikipedia.org/wiki/Bamboo_textile#Manufacture_of_bamboo_viscose

It appears there is a traditional method, but, I cannot find info on this.

Edit 1: Could this method for bamboo textiles and such (alternatives to string and wool from bamboo) be feasible? http://www.canada.com/life/fashion-beauty/bamboo+fabric+made/2459065/story.html

Edit 2: I was also thinking of how we should approach future modules with fruit trees and plants. Give certain trees and plants a module all to their own if there are many uses for them (cherries (the cultivar system could be experimented with this, so we could have flowering cherries, and fruiting cherries), coconuts), and bundle up others that do not have as many uses into other modules, centered around a specific theme (acerola, mamey sapote, sea grapes, etc). Themes could range from stuff like certain climates, novel means of growth, wild edibles, and so on. Although this might sortof be done with some other plants in a future module, but, mainly because they compliment each other...

**Comment by Sunconure11** [comment]
Actually it should. I'll write down some stuff for lye production via this mod.

**Comment by Sunconure11** [comment]
While lye can be done by this mod, the stuff required for bamboo textiles is too technologically advanced. Unless someone can think of a way to fit that in, it can't be done.

Edit: I found a way that while is a recent innovation, should be possible via the tech in this mod. Someone can think of a better way.

> 1. Create lye via mixing charcoal with water in a kettle.
> 2. Place bamboo planks in a kettle containing lye.
> 3. Resultant product will be bamboo pulp. Place it down in the world, and you can press out the fiber using a piston. This will destroy the fluid, and yield anywhere from 3 to 9 pieces of bamboo string. Bamboo pulp does not flow like most fluids.

http://life.gaiam.com/article/how-are-eco-friendly-fabrics-made

http://www.teonline.com/knowledge-centre/bamboo-fiber.html

http://textilelearner.blogspot.com/2011/12/bamboo-fiber-bamboo-fabric-production.html

**Comment by Sunconure11** [comment]
Also, maybe its time to use the bamboo ladders from the old idea pile? That could fit here.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/xap9bt3dpx6h0xy/kendosword.png?dl=0

Here is your kendo sword. I had to pretty much base it against katanas from balkon's weapons to keep it within 16 x 16 pixels. Cheese blocks will come later today/tomorrow, depending on how you view it. I also need further clarification on how to do it, as what you told Pitch is rather vague.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/3gzgxrlsap1vkit/Screenshot%202016-02-22%2022.11.51.png?dl=0

Tried my hand at the Shishi-Odoshi, but, something looks wrong. Any tips, before I go to make the texture map and such for this?

Also pitch, if you are seeing this, I'm using Techne for all of my models, but, Tabula for finer tweaking.

**Comment by IceDragon200** [comment]
It's not big enough? I think it would be a tad bit bigger, also why not do it at an angle instead?

**Comment by Sunconure11** [comment]
Yeah, it is kind of small, though I found them in all of kind of sizes. Either way, I'm going to go to bed soon, a convo me and Pitch had two days ago fucked up both of our sleep schedules.

I'l try to angle certain parts too. I angled the bamboo piece that dumps the water into the pool, but, tell me what you had in mind for angling, and I can do that in the morning.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/wxbxrahak1bdr4e/Screenshot%202016-02-26%2007.38.11.png?dl=0

Scaled up the Shishi Odoshi a bit. I think the pool should be removed, and instead, it should dump water into the nearest spot. What do you think of that idea?

I'm going to also possibly add some other stuff to it once I get my sleep fully back on track.

Also, while the person who originally suggested the idea suggested we should use it as a timer, I'm starting to have doubts on doing that idea. I can't think of anything that might make it better than timers from other mods (such as the hovering hourglass from botania), for one thing. Giving it something that might make it better than other timers is the only way we should pursue that idea.

**Comment by IceDragon200** [comment]
@Sunconure11 Why not place the entire structure into a basin? 
Something like the Pancheon?
A stupid idea I had was to pour any fluid in, like booze or milk, or even lava?

**Comment by Sunconure11** [comment]
That could work.

**Comment by esotericist** [comment]
> Also, while the person who originally suggested the idea suggested we should use it as a timer, I'm starting to have doubts on doing that idea. I can't think of anything that might make it better than timers from other mods (such as the hovering hourglass from botania), for one thing. Giving it something that might make it better than other timers is the only way we should pursue that idea.

Two notes:
One, I think there's quite a lot of value in a timer that has an audio cue attached. Especially if you guys can locate a particularly good sound for it.

Two, it might be a little odd from an implied-tech point of view, but would it maybe be plausible to have it interact with comparators to provide a rising signal strength over time, cycling through as the bucket fills and empties? We don't have a lot of triangle wave generators outside of high-tech mods, redstone-specific mods, or weird hopper engines in vanilla. It might be odd, but it's a legitimate feature?

**Comment by esotericist** [comment]
>  A stupid idea I had was to pour any fluid in, like booze or milk, or even lava?

Would it at all be feasible to have the cycle time of the device be based on the fluid going through it? Based on viscosity, maybe?

**Comment by Sunconure11** [comment]
That might be a good way to give it an edge over other timers.

**Comment by esotericist** [comment]
> That might be a good way to give it an edge over other timers.

Yeah, with it functioning in that fashion, I would probably use it in conjunction with other timers, to get non-uniform cycle patterns through the combination (probably using automagy redcrystal to clamp values). I can't remember what exactly I last built that needed this sort of thing, but I have wanted this in the past.

I personally think 'is usable alongside other timers' is a better position for it as a functional object than just 'does timers better somehow'.

**Comment by Sunconure11** [comment]
I like your idea for the usage of the Shishi-Odoshi as a provider of a rising signal. I'll send over the model and create a texture after I finish Baykok for Totemic, that model is more complicated, and thus, requires more of my time. The body is finished, but, the texture will take a bit of time.

I need to get this model done before I do other stuff, I need to focus on one thing at a time for the moment.

In addition, I will tweak the model for the Shishi-Odoshi slightly before I send it over. There are a few minor tweaks I want to add on. As well as that, I will likely hunt for sound files, the Shishi-Odoshi has a distinct sound.

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.

We are looking at implementing this request in newer versions.
