### ISSUE TITLE
Order of uploading

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#208]
Due to some fuckery with Curse, I will just sortof pin this to an extent, for future reference.

First, upload the bundled build. Afterwards, upload the full build. This will make curse download the full build, and players will have to go to the site to download the bundled build.

**Comment by Alatyami** [comment]
Will do.

Alatyami

**Comment by PitchBright** [comment]
Good stuff, Sunny.
Please put this in the Wiki, in a Dev Info section or something… and close this issue.

**Comment by Sunconure11** [comment]
Already created a wiki page.
