### ISSUE TITLE
What is wrong with my code?

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#209]
I'm trying to make BoP flowers grow via the bee boxes, and it seems players are having a hard time with them.

http://pastebin.com/AT19QF6f

**Comment by IceDragon200** [comment]
@Sunconure11 BoP flowers refuse to be placed they seem to return false for their canPlaceBlockAt.
I'm reworking the flowers system a bit, create custom handlers later
