### ISSUE TITLE
Forestry apiculture support

### ISSUE THREAD

**Issue by SynfulChaot** [GrowthcraftCE/Growthcraft-1.7#21]
Would it be possible for Growthcraft Cellar to detect if Forestry's Apiculture module is loaded and if so be able to utilize Forestry's honey to make mead even if Growthcraft Bees isn't loaded?

**Comment by Ar97x** [comment]
That could be something interesting, since forestry apiculture is more used
than GC Bees, because using both in a modpack is kinda redundant. Maybe
this is just a oreDictionary case, using not the item "Honey" but the
oreDict. "Honey". But I know almost nothing of programming so I must be
saying shit.

**Comment by Alatyami** [comment]
Should be easy to do actually. A simple post init.

Sent from Yahoo Mail on Android

**Comment by Sunconure11** [comment]
This would be a good idea.

My sleep schedule has gotten worse, so I might not be active for a few days.

**Comment by Ar97x** [comment]
I'm studying 30h per week, so time is scarce by now, but I'll try to work
on the translation on this weekend as well as getting some tests and
leveling on COD hahaha

**Comment by ghost** [comment]
there is also erebus honey and bamboo and also biomes of plenty bamboo (i don't use this one but i do use the other one).

**Comment by IceDragon200** [comment]
@trollworkout If you can collect all the Ore Dictionary names for these items I'll register our items under those names as well (or is it the other way, you wish to use BOP's bamboo for our items?)

**Comment by ghost** [comment]
growthcraft has best bamboo itemsalso i will loook into it as i got first 2

**Comment by Sunconure11** [comment]
Was this covered by the new forestry integration?

**Comment by IceDragon200** [comment]
@Sunconure11 I would believe so, even if it isn't, _shrug_
