### ISSUE TITLE
Beeswax should be oredictionary compatible

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#210]
I think the title speaks for itself.

Examples would be beeswax and wax from harvestcraft. The vegan option and garden stuff also have their own forms of wax. All of these are bound via the oredictionary. I suggest looking at their oredictionary settings, and applying it to our beeswax. Bonus points if you could do something like say, make red candles from harvestcraft craftable with red beeswax, though thats not required, its just a dumb little idea that one could do in minetweaker within a few minutes.

**Comment by IceDragon200** [comment]
@Sunconure11 It's already in the ore dictionary, `materialBeesWax`, `materialBeesWaxRed`, `materialBeesWaxBlack`, give me a list of all the common registered names and I'll change it.
Makes my job much easier.

EG.

> Mod X has Y registered as Z, we should consider register our A as such.
> 
> For beeswax:
> - materialBeeswax
> - materialBeeswaxRed
> - materialBeeswaxBlack
> - beeswax
> - beeswaxBlack
> - beeswaxRed

**Comment by Sunconure11** [comment]
Harvestcraft Beeswax:

> materialWax
> materialPressedWax
> materialBeeswax

Harvestcraft Candleberry Wax:
Same as above for the most part, though I think I ended up using minetweaker for some of this stuff. However, many wax adding mods use these definitions.

Garden Stuff Wax:

> materialWax
> materialPressedWax

Vegan Option Vegetable Wax
Same as garden stuff wax

**Comment by IceDragon200** [comment]
@Sunconure11 Okay I've added `materialWax` and renamed our `materialBeesWax` to `materialBeeswax`, not sure about us using PressedWax though...

**Comment by Sunconure11** [comment]
Pressed wax appears to be used in all of the wax entries that I dredged up from my modpack, I suggest using it for extra compatibility. I didn't create the entry via minetweaker either, even though it is possible to make entirely new definitions.

**Comment by IceDragon200** [comment]
@Sunconure11 Added to latest dev build :)
