### ISSUE TITLE
Modpack inclusion request: PWoT Island

### ISSUE THREAD

**Issue by Igfig** [GrowthcraftCE/Growthcraft-1.7#211]
Hi there, 

I'd like to use Growthcraft in a survival island / ocean exploration based modpack tentatively called "PWoT Island."

The current list of mods is at https://goo.gl/TtgChm, though it may change slightly in development.

Thanks!

**Comment by IceDragon200** [comment]
@Igfig Your mod list needs to be public, I can't read it 

:P No approval for you until that happens

**Comment by Igfig** [comment]
Oh, sorry. Should be public now.

**Comment by IceDragon200** [comment]
@Igfig Here, have an approval sticker [![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
