### ISSUE TITLE
Barrel models are bugged

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#214]
Just went to go to test to make sure the issue with the flowers is solved with the new entry changes, and I uh, found this with the barrels.

https://www.dropbox.com/s/d9tojsee8nxkpi6/Screenshot%202016-02-22%2022.27.44.png?dl=0

**Comment by IceDragon200** [comment]
Hot damn, what the hell happened there D:

Ah, so THAT'S WHY THAT METHOD EXISTED

``` java
private void setRenderBounds(RenderBlocks r, double x1, double x2, double y1, double y2, double z1, double z2)
    {
        r.setRenderBounds(x1, y1, z1, x2, y2, z2);
    }
```

I was trimming up the code yesterday and remove this, gimme sec, readding

**Comment by Sunconure11** [comment]
Can someone re-open this, due to the fact I no longer have collaborator status? I just discovered yet another weird barrel model bug, while trying to do your request for obtaining salt water from oceans.

https://www.dropbox.com/s/92x65endhyc46fb/Screenshot%202016-02-23%2018.56.06.png?dl=0

**Comment by IceDragon200** [comment]
THIS BARREL IS HOLLOOOOOOOOOW _high note_

And fixed in latest build, this time for sure

**Comment by Sunconure11** [comment]
Yes, it has been fixed. Thank you.

Also, regarding the old kumis beverage, do you still plan on removing that, as it was in the old plans before me and Pitch came along? Or do you plan on fixing it up?

**Comment by IceDragon200** [comment]
@Sunconure11 Yeah, it needs fixing along with adding proper milk fluids if Forestry isn't present
