### ISSUE TITLE
Saltwater can only be obtained via survival

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#215]
Just a minor nuisance, but, I can only get saltwater from oceans if I go into survival mode. I cannot do it in creative.

The buckets also have no name.

**Comment by IceDragon200** [comment]
@Sunconure11 Could be a forge thing, I don't have any filters or checks on that would prevent it on gamemodes

EDIT:
Milking cows in creative doesn't work either if that makes you feel better

**Comment by Sunconure11** [comment]
Apparently unfixable. Closing for now unless it can be fixed in the future.
