### ISSUE TITLE
Help for Milk Module Translation

### ISSUE THREAD

**Issue by Ar97x** [GrowthcraftCE/Growthcraft-1.7#216]
I decided to work on the missing portuguese translations, and I'm having some trouble to get to know everything on milk module, so I want you guys, especially @Sunconure11 and @PitchBright, that I know that did some researching about it, to brighten it up to me so I can find a compatible translation to it. At first, what about teaching me what is the starter culture?

**Comment by Sunconure11** [comment]
Everything you need to know is in this file:

https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/blob/master/GrowthCraft%20Milk%20Module.pdf

If needed though, I can give you more precise notes.

For... starters though, starter culture is a group of fungi and bacteria used to start the fermentation process of cheese.

**Comment by Ar97x** [comment]
This kind of specific and technical language is hard to translate if you don't have knowledge about it. I'm doing my best.

**Comment by PitchBright** [comment]
What are you trying to translate, the names for blocks and items?

**Comment by Sunconure11** [comment]
I have a few ideas for how you can translate Starter Culture into Portuguese.
1. Directly translate it
2. Find the equivalent of sites like this (http://www.cheesemaking.com/cheeseculturesandmoldpowders.html and http://www.culturesforhealth.com/starter-cultures.html but in Portuguese) and see what they refer to starter cultures as
3. Call up a local dairy, and ask them for the term for starter culture in Portuguese.

**Comment by HanatakeYurii** [comment]
Have translated the module in french.
Give it a look

**Comment by Sunconure11** [comment]
I don't think he knows French, but, that could also work. Mainly to see how you managed to translate it.

**Comment by HanatakeYurii** [comment]
Aw, sorry, didn't see it was about Portuguese.

But if you have any tought about a specific term to translate, feel free to ask as I did the work just before.

**Comment by Ar97x** [comment]
Thanks, I'll continue it soon, I'll ask if I have any questions.

**Comment by marcoasfonseca** [comment]
Hi guys :) I'm portuguese, maybe I can help you with something!

**Comment by PitchBright** [comment]
That sounds good. @Ar97x can you share what you've got so far with @marcoasfonseca and maybe he can help you fill in the blanks and wrap this up quickly.

Thanks guys!

**Comment by Ar97x** [comment]
Oh good, nice to have someone to help with the work. @marcoasfonseca I'll keep writing in english if that's ok to you, so the other guys can take note of what we're saying. Do you think we need to split the langs to Portugal and Brazil's portuguese, or is it ok to you if you make changes to the pt_BR file and I adapt it in case of discordancy between our portugueses? And have you ever worked with translations on Git?

**Comment by Ar97x** [comment]
And thanks @HanatakeYurii, but I don't speak french (yet). I'll post here in case we have something you might be able to help us.

**Comment by PitchBright** [comment]
Can you put up a text file of the translations you've made so far? Perhaps pastebin.

**Comment by PitchBright** [comment]
Sunny and I can help clarify what any items/blocks are (and what they do)… if you guys are confused about any of them.

**Comment by Ar97x** [comment]
You mean the translations for the milk module or for all of them?

**Comment by PitchBright** [comment]
Milk Module.

**Comment by marcoasfonseca** [comment]
Look I'm from Portugal so I prefer pt_Pt, even because I don't know all brazilian expressions. Yeah I already worked in translations on Git. If you need help for all of them, i can help you with that :)

**Comment by marcoasfonseca** [comment]
I'm giving a look on the translation for Milk Module and the translation for starter culture is "Fermento Lácteo" :)

**Comment by Ar97x** [comment]
Great. I think it can work for us both. I'll put it later.

**Comment by marcoasfonseca** [comment]
Hi :) someone knows what is/ what happens in the progress of "Waste Stage" on milk production?

Thanks :P

**Comment by Ar97x** [comment]
I think the most likely translation for it is "Estágio Residual".

**Comment by marcoasfonseca** [comment]
I thought that too, but i was seeing the cheese production in portuguese and i don't found nothing with a similar name, so i'm questioning just to have sure. 

Do you need help with something? If yes you can look at the translation that i made to have an idea or just ask me :)

**Comment by Ar97x** [comment]
I'm out of home today, but I guess I'll have some time to work on it later
night. I'll ask if I need something.

**Comment by marcoasfonseca** [comment]
@Ar97x maybe you should look at the "Apple Cider" translation because is "Sidra" and not "Cidra", at least, here, in Portugal. I've committed the same error :)

**Comment by Ar97x** [comment]
I always ask myself which one is right. I'll fix it on a later date.

**Comment by Ar97x** [comment]
Alright people, it's time for some translations! Sorry for taking too long, I've been busy for awhile.

**Comment by Alatyami** [comment]
Which translations do we still need?

**Comment by Ar97x** [comment]
Milk module is fully translated for what I know. We can close this.
