### ISSUE TITLE
Use Travis CI to conduct builds

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#22]
If anyone has worked with the .travis.yml file format before, we'd like some assistance with it so that we can start building is distributing.

**Comment by IceDragon200** [comment]
@alatyami http://xeiam.com/configure-travis-ci-to-deploy-snapshots/

Maybe something like this?

**Comment by Alatyami** [comment]
Perfect. I am going to look into curse forge for distribution.

**Comment by Alatyami** [comment]
Ok .. looks like in order to have gradle produce the separate jar for each sub-module we are going to have to restructure the project with the following:

```
workspace
|__Mod A
   |__src
      |__main
   |__build.gradle
   |__... ...

|__Mod B
   |__src
      |__main
   |__build.gradle
   |__... ...

|__eclipse (empty folder!)
```

I'm really wishing the GitHub had a voting system for issues. It might be easier to just add a boolean into the config for if the mod is to be activated or not.

**Comment by Alatyami** [comment]
ProjectRed does this same method of releasing separate jars. I'll look into how they did it this week.

**Comment by IceDragon200** [comment]
@alatyami can you close this now, don't we have builds/releases now?

**Comment by Alatyami** [comment]
Closing ... if there is demand to split the jars out then we will revisit it, so far there is very little demand for it and honestly I like only needing to update one jar on my SMP servers.
