### ISSUE TITLE
Add a unifying OreDictionary definition for cheese blocks

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#220]
IMO, all cheese blocks should be registered under blockCheese, so that modpack and modders can take advantage of it easier.

In addition, I'd like to add proper sound to Dynamic Surroundings for cheese. Currently, with that mod installed, they sound like stone slabs when stepped on. I can easily add support for it once the definition is added, as it would just require me to push out a pull request on their end using some of the easiest and most stable code to modify it.

**Comment by PitchBright** [comment]
What are the differences between Material.ground,cloth,cake,sponge? Just curious there.

Also, maybe we should .setStepSound(soundTypeCloth)?

**Comment by IceDragon200** [comment]
@PitchBright ground is generic, cloth probably makes it flammable, cake is food, sponge soaks up water probably*
Minecraft might have special conditions for these materials, but I'd need to dig around first.

Take my guesses with a bottle of salt

**Comment by Sunconure11** [comment]
I would say make it sound like cake when stepped on. For Dynamic Surroundings, I want it to make the "mud" sound when stepped on, as expected when stepping on cheese... once the oredictionary definition is set in place.

**Comment by IceDragon200** [comment]
@Sunconure11 I've added these some commits back I believe
https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/73cfddbbc7bcd31b780d681486b94ced81ab5675/src/java/growthcraft/milk/init/GrcMilkBlocks.java#L112-L115

https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/73cfddbbc7bcd31b780d681486b94ced81ab5675/src/java/growthcraft/milk/common/block/BlockCheeseBlock.java#L59-L61

Feel free to close if this is okay :)

**Comment by Sunconure11** [comment]
This should be good enough.

**Comment by Sunconure11** [comment]
I do have one question though. Is it possible to add it to all cheese blocks in the future, including those in the process of aging?
