### ISSUE TITLE
Third-Party app access

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#221]
I'm using CodeHub app to comment on repositories. I can't seem to comment on the GC issues with it, so I looked into it, and it seems that we may need to enable something on your side for me.

Explanation of problem and solution:
https://codehub.uservoice.com/forums/221116-general/suggestions/9206064-add-comment-fails

Information about third-party app restrictions:
https://help.github.com/articles/connecting-with-third-party-applications/

How to enable:
https://help.github.com/articles/about-third-party-application-restrictions/

@Alatyami would you mind poking around the repo's settings and seeing if you can enable that for me, please and thanks!

Cheers,
Pitch

**Comment by Alatyami** [comment]
Test

**Comment by PitchBright** [comment]
Test

**Comment by PitchBright** [comment]
Worked. Thanks!
