### ISSUE TITLE
Question: what are water bags (purpose, craft, uses)

### ISSUE THREAD

**Issue by HanatakeYurii** [GrowthcraftCE/Growthcraft-1.7#223]
Hi,

As said in title I can't get what are the purposes of water bags. I could'nt either find a recipe or an use (no craft in NEI, no reaction with water source). I didn't find anything in the wiki as well.

All I can say is that the water bags are in the Growthcraft Celler creative tab

EDIT: hum, wait a bit, i have a little problem with NEI

EDIT 2: 
Found recipes, NEI was bugging, but no purpose found

**Comment by Sunconure11** [comment]
They store fluid, usually alcohol.

**Comment by HanatakeYurii** [comment]
Ah? ok... (this don't seems to do anything with water source but it was in creative and I can be mistaking).

Isn't it a bit weird calling them "water" bags?

(Either I will close this after)

**Comment by Sunconure11** [comment]
Try using them in survival.

**Comment by HanatakeYurii** [comment]
Thx, will try

Closing this anyways

**Comment by HanatakeYurii** [comment]
Opening Again,

Tried on a water source block and didn't anything (EDIT: in survival)

**Comment by Sunconure11** [comment]
Try it on alcohol then. I'll go and test too, maybe something is bugged, I've been discovering bugs left and right lately, and have been sending the information to the coder.

Are you doing this in survival, or creative BTW? A few fluids appear to not function properly if you try to obtain them with tools like buckets and bags via creative.

Edit: Right click on a barrel filled with fluid. That works. https://www.dropbox.com/s/e4e44f9mycjr6mn/Screenshot%202016-03-01%2016.38.03.png?dl=0

**Comment by HanatakeYurii** [comment]
ok, thx.
Wouldn't it useful to make it functionning on water sources? In some special packs, it could be very interesting.

**Comment by Sunconure11** [comment]
IIRC, it was like that in the past.

**Comment by Sunconure11** [comment]
Also, you should probably close this for now until you find any major bugs with this.

**Comment by HanatakeYurii** [comment]
Okay... lost in time...

I close this
Thx for responding
