### ISSUE TITLE
Player crashing when placing saltwater in kettle

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#224]
I decided to show some of the people lurking on the minecraft forums the preview builds, and apparently one of them crashed while putting saltwater in a kettle.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10?comment=229

**Comment by IceDragon200** [comment]
Salt water is missing an icon ~~again~~
