### ISSUE TITLE
Development Build, error while including Chromaticraft

### ISSUE THREAD

**Issue by SvEgiiVEteR** [GrowthcraftCE/Growthcraft-1.7#225]
growthcraft-1.7.10-2.5.0-complete--14fccd2.jar Crash
http://pastebin.com/6taV3U7q

**Comment by HanatakeYurii** [comment]
What were you doing?

It seems that Reika's Chromaticraft is involved again (yes again because Reika's mods are involved in too much issues with other mods). Did you report this issue to him as well?

**Comment by IceDragon200** [comment]
@SvEgiiVEteR Looks like you tried to do a Game Registry dump and it failed, I'm assuming you set the "Enable Game Registry Dump"

**Comment by SvEgiiVEteR** [comment]
Yes, I have included this option, but then turned off. and it did not help ..
but now everything is okay. It was still such a mistake
http://hastebin.com/ilezicanof.md
but I do not know because of what.

**Comment by IceDragon200** [comment]
@SvEgiiVEteR Did you try removing Growthcraft to see if we are the ones causing this chaos?
That log has no trace of Growthcraft, soooooooo, what is going on?

EDIT:
I've just been informed this works fine with the latest development release AND the latest releases of Reika's mods, please update the mods and try again

EDIT2:
Hope you don't mind, I renamed the topic to avoid confusion with our existing "Preview Builds" issue

**Comment by Alatyami** [comment]
To second @IceDragon200 Reika released a version 11 a few days ago. There was an Exception thrown with the version 10 mods. I tested v11 with my modpack and the exception went away. Also do not forget to clear out your ./conf/growthcraft directory as there is a known issue with the previous conf directory when upgrading from GC 2.4 to 2.5.

**Comment by SvEgiiVEteR** [comment]
@IceDragon200 now I sit on 254788b.jar
all is well. enabled "Enable Game Registry Dump"

**Comment by IceDragon200** [comment]
@SvEgiiVEteR  :smile: Glad to hear, I'll close this then

**Comment by SvEgiiVEteR** [comment]
@IceDragon200 I understand why there is no breakage. This file has not been created ..
GameRegistry_Blocks.txt

Suddenly, a new crash .. although previously it was not.
I have a full version of my modpack and same mod and your option is enabled...
and there everything is good
strangely ..
http://hastebin.com/noyifidepe.md
