### ISSUE TITLE
Can't seem to make cheese curds

### ISSUE THREAD

**Issue by gchpaco** [GrowthcraftCE/Growthcraft-1.7#234]
My cheese vat will accept milk and rennet, and will let me put starter culture (which I have cheated in) into it, but won't start.  I have been right clicking it with a sword.  I am doing this in an environment with MFR, but that a) hasn't stopped the pancheon from working and b) didn't make a difference when I disabled it, nor did turning off the Forestry milk liquid.  Is this just not implemented yet in the 2.5.0 previews or something?  I dug through the code and it seems like it should be wired up.  I am running the 66c0719 build.

**Comment by IceDragon200** [comment]
@gchpaco Cheese Vat requires a heat source, such as lava, fire or Nitor (if you have Thaumcraft), check the `growthcraft/cellar/heatsources.json` config file.

Also, if everything was done correctly, you should see smoke particles rising from the vat, it takes awhile to complete.

If you disabled Forestry's milk, it should fall back to our implementation.

Now if my memory serves me correctly:

## Curd Procedure/Recipe:
- 5 buckets of Milk
- 1 bottle of Rennet
- 1 Starter Culture
- Whack Vat with Sword
- Watch for smoke particles
- Should turn into curds
- Remove Whey from Vat using Bucket

## Cheese Recipes:

All cheese recipes should activate automatically (so put your fancy sword away.)

### Cheddar
- 1 Salt
- 1 Orange Dye (dyeOrange) OR 1 Pumpkin

### Gorgonzola
- 1 Salt
- 1 Fruit (Apple or Growthcraft Grapes, anything that was registered as `foodFuit`)

### Emmentaler
- 1 Salt
- 1 Wheat (cropWheat)

### Appenzeller
- 1 Salt
- 1 Bucket of Wine (any grape wine will suffice, anything tagged with "wine" via the FluidDictionary), Or 1 Bucket of Cider (any apple cider will suffice, anything tagged with "cider" via the FluidDictionary)

### Asiago
- 2 Salt
- 1 Yellow Dye (dyeYellow)

### Parmesan
- 1 Salt
- 1 White Dye (dyeWhite)

### Monterey
- 1 Salt
- 1 Red Dye (dyeRed)

Hopefully this helps everyone in the future as well :mask:, now I must be resting

**Comment by Sunconure11** [comment]
That post has been turned into a wiki page.

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Milk:-Cheese-Production

**Comment by gchpaco** [comment]
I had nitor underneath it (heat levels hover between 99% and 100%).  Screenshot: http://imgur.com/GtYeJUd

No smoke particles, basically ever, with normal cheeses.  I have gotten it to make ricotta curds.

Mod list: BTP Beta D https://www.atlauncher.com/pack/BevosTechPack/ with RTG 0.7.0 and growthcraft beta.

**Comment by Sunconure11** [comment]
Which growthcraft build? If you are using the latest, clear all of the folders within the growthcraft config folder. Sometimes leaving behind old configs causes problems with this mod.

https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/200

Also, once you have curds made, extract them with a cheese cloth. Place the ingredients for specific cheese types within the kettle. Then let the curds dry over a pancheon, and place the dried curds in a cheese press.

**Comment by gchpaco** [comment]
Running 66c0719.  I did clear the configs, which fixed a problem where I couldn't make rennet legitimately.

**Comment by Sunconure11** [comment]
Huh, wtf? I'm trying to create cheese and now I'm running into the same issue involving cheese making. Some of it is time-based, but, this appears to be a bug.

Edit: Check the flowchart at the bottom, see if one of us missed something:

https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/blob/master/GrowthCraft%20Milk%20Module.pdf

**Comment by gchpaco** [comment]
That looks like what we're supposed to be doing.

**Comment by IceDragon200** [comment]
@gchpaco @Sunconure11 Not your fault folks, made a typo
https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/66c071998c65096a8d331a6dccd17fc4f1d9f54b/src/java/growthcraft/milk/common/tileentity/TileEntityCheeseVat.java#L245

This should be:

``` java
// If the slot is NOT full, then return false
if (!rennetFluidSlot.isFull()) return false;
```

Added a new development build which should resolve this

**Comment by gchpaco** [comment]
Can confirm, I can make cheese now.
