### ISSUE TITLE
Modpack Inclusion: Into the Otherworld

### ISSUE THREAD

**Issue by Solistor** [GrowthcraftCE/Growthcraft-1.7#237]
Formal request to include Growthcraft into my modpack: [Into the Otherworld](https://drive.google.com/open?id=1XCMvE9awu5EL51XiPGQLFOHO0VP8P92ybWuuoJUoZ5U), a lore-based magical exploration and RPG pack. I've been using it privately amongst a few friends for some time now but now I wish to push it as a public pack on the Technic platform.

Thanks for your time!

**Comment by IceDragon200** [comment]
@solReaper [![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
