### ISSUE TITLE
White Grapes addition

### ISSUE THREAD

**Issue by marcoasfonseca** [GrowthcraftCE/Growthcraft-1.7#245]
Hi :) I was thinking that would be cool having white grapes in the game too; so you can make red wine with the red grapes that exist in the game and you could also craft white wine with the new ones :)

I don't know how to program but i think the code could be the same that the "normal grapes".

Think about it, that would be cool :cool:

**Comment by Sunconure11** [comment]
I remember someone had vague plans for various grape cultivars, and I did make the textures for green and red grapes, but, I doubt this will happen anytime soon.

If you feel you have a case for this, follow this page:

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Module-Contribution-Guide

I suppose you can dredge up my old grape textures if you follow this idea ever. If you feel you can pull this idea off in a presentable format, I will give you permission to use the red and green grape textures for this.

**Comment by killerjdog51** [comment]
How do I support this idea? Like i really like it.  Or is there a way to help elaborate on it? because I already have everything planned/thought of with this.

**Comment by Sunconure11** [comment]
Create a design document with all of the information. Follow that guide mentioned above, and set it up on google documents, and work it out with someone willing to help you. There are two other module ideas I have at the moment, one of which is another collab, like milk, and I cannot aid you. If you want some more places to start, here is some stuff for you to look at, if you are really going to pursue this.

https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/blob/master/GrowthCraft%20Milk%20Module.pdf (to see how design documents are done)

https://en.wikipedia.org/wiki/List_of_grape_varieties#White_grapes (What variety is based off of? White grapes are actually green in color, so, there is an existing texture you can use for that)

Obviously, a new grape variety will require a new form of wine from your white grapes. Any specific type? It should not be something that would require one to make the distillery as soon as possible.

https://en.wikipedia.org/wiki/Chardonnay (This might be the best variety to base it off of, and you could call the wine Chardonnay.)

https://docs.google.com/document/d/1Xkayhks7syOTTfCnJGpaLiiMJLXWvyLo-rGzxnYAi9Y/edit?usp=sharing (Final product of the milk module (part 1) document, before being turned into a pdf.)

Usable textures, that are currently unused:

https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/development/src/resources/assets/grcgrapes/textures/blocks/green_grape.png

https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/development/src/resources/assets/grcgrapes/textures/items/greengrapes.png

You will also need something that isn't wine or such to distinguish white grapes from the default grapes, so they are more than just retextured grapes.

**Comment by Sunconure11** [comment]
I think this can be closed, there is a design document for this created by @killerjdog51, which has been posted to the design documents page.

**Comment by Sunconure11** [comment]
https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/issues/2
