### ISSUE TITLE
[BUG] [2.5.0] Fermenting barrel does not progress

### ISSUE THREAD

**Issue by hron84** [GrowthcraftCE/Growthcraft-1.7#266]
I trying to make a fermented Wine and Cider, but neither start progressing. Sometimes the fermenter brewer's yeast/netherwart disappears, but the fluid keeps young. 

I using the latest 2.5.0 build with default (newly generated) configuration files (no customization) on a SMP server.

Also the progress bar is a bit weird. If I keep open the GUI, the bubbles goes upward but the arrow does not progress, when I close the GUI and open again (same barrel) the bubble animation does not stat. If I reopen the same GUI again, the bubbles start again.
WAILA does not display a progression, stays at 0%.

**Comment by Sunconure11** [comment]
Before installing 2.5.0, did you clear out your old growthcraft config files? Do that, and try again. If that solves it, then close this. If not, then keep it open.

**Comment by hron84** [comment]
Yes, I cleared out the old growthcraft config files, because MC crashed otherwise. I can try it again... give me few moments.

**Comment by hron84** [comment]
@Sunconure11 It works but as soon as I open the barrel's GUI the progression stops. So, I keep open the issue.

**Comment by Sunconure11** [comment]
Odd.

**Comment by Sunconure11** [comment]
Can you list the build you are using? 2.5.0 is not enough info.

**Comment by hron84** [comment]
Latest build, `growthcraft-1.7.10-2.5.0-complete--1ae3bd2.jar`

**Comment by hron84** [comment]
I keep the barrels sealed so I hope they will finally ferment.

**Comment by Sunconure11** [comment]
What do you mean, sealed? They don't need any blocks placed on them, just place them in a spot, fill them with young booze, then use brewers yeast or netherwart to ferment.

**Comment by hron84** [comment]
"Sealed" means "untouched" for me.

Btw, the fermentation process finished (according to WAILA) and the fermenter (brewer's yeast in this case) vanished, but the content of the barrel kept young.

**Comment by IceDragon200** [comment]
@hron84 It's a client/server timemax mismatch.

The ferment barrel has a default "timemax" value, it returns 0 on the client instead of the actual value since the recipe recipe details are unavailable to the client.

I've addressed it now, I'll be uploading the new dev build in a few minutes.

Should be fixed in the latest dev builds

**Comment by hron84** [comment]
@IceDragon200 I moved to  893085b but the issue is same. As soon as I reopen the GUI, the progression stops. When I reopen the GUI again the progression starts from beginning. The arrow has a tooltip now, but when the progression stops it shows 0/24000 without changing. When the progression is works then the first number counts up (possibly to 24000).

It broke between the latest 2.4 release and the 2.5 releases somewhere. Still keep the report open.

**Comment by Sunconure11** [comment]
Try the latest build, and see if that fixed things. If it did, close this.

**Comment by hron84** [comment]
@Sunconure11 I can confirm 60880a1 fixes the barrel issue, reopening GUI does not lose progression. Still waiting for my cider become fermented, as soon as the process finishes, I'll close the issue.

**Comment by hron84** [comment]
Fermentation succeeded, Fermented Apple Cider created,
