### ISSUE TITLE
compatibility with Plant Mega Pack

### ISSUE THREAD

**Issue by darthvader45** [GrowthcraftCE/Growthcraft-1.7#267]
@ Plant Mega Pack's poisonous plants could be used to make poisoned beverages until the Nether module is completed.  They are all based off real-life poisonous plants, like Lily of the Valley, Deathcap, Wooly Gomphus, etc.

**Comment by Sunconure11** [comment]
I'm considering discussing a new poisoning agent with Ice, since the nether module has actually been scrapped (but might be made into a seperate mod). However, it won't rely on another mod to do it.

**Comment by darthvader45** [comment]
Yeah, and the current build allows getting ethereal yeast from the mushroom biomes, but I cannot get origin yeast.  Any idea on how origin yeast is obtained?

**Comment by Sunconure11** [comment]
Origin yeast is from mushroom biomes.

**Comment by darthvader45** [comment]
Yeah, I'm in a Mushroom biome, fermenting young cider in the culture jar, but only getting ethereal yeast.  Any idea why?

**Comment by Sunconure11** [comment]
Can you clear your old growthcraft configs, and see if it continues? Often times, there are issues with various configs from older builds causing all kinds of havoc.

**Comment by darthvader45** [comment]
I'll try and report back.

**Comment by darthvader45** [comment]
I cleared the configs, and when I opened the yeast.json it was the exact same as before I cleared it.

Edit: Still only getting ethereal yeast.  Using the latest release build on Curse.

**Comment by Sunconure11** [comment]
@IceDragon200: Do mushroom islands count as magical biomes? If so, would it be possible to make origin yeast spawn in mushroom islands no matter what?

**Comment by IceDragon200** [comment]
@Sunconure11 Nope, they are just `MUSHROOM`

Ethereal can be formed in MUSHROOM and MAGIC biomes

**Comment by darthvader45** [comment]
Weird, I'm getting ethereal yeast in Mushroom biomes, and the config I have for yeast.json labels ethereal as coming from both biomes tagged MUSHROOM and MAGICAL, yet nothing in the config for origin yeast.  Is this fixed in the dev builds, and if so, please have a release out soon.  I'd love to be able to naturally get origin yeast, as I cannot currently.

**Comment by IceDragon200** [comment]
@darthvader45 I've just realized that origin was not in the yeast config.

You could add it yourself, but I've updated the dev build.
Be sure to remove your old `growthcraft/cellar/yeast.json` config

Also in the future you may add your own yeasts to this config file, or patch existing ones

**Comment by darthvader45** [comment]
How would I patch the original (i.e. the one I have)?  Just copy/paste the ethereal info and change the tag to origin and set biome to mushroom?

**Comment by IceDragon200** [comment]
@darthvader45 Growthcraft will generate a default config, just run the game once and check the directory for `growthcraft/cellar/yeast.json.default`, copy the contents in your new config, or just delete the `growthcraft/cellar/yeast.json` before starting the game

**Comment by darthvader45** [comment]
I'm still running 2.4.0 Complete.  I'd prefer to wait and use a release build.

**Comment by darthvader45** [comment]
Also, any chance you could add the ability to make other kinds of beer, like pilsner or stout?  Imagine a tavern in Minecraft serving the blocky equivalent of a Guinness stout on St. Patty's Day?  Perfect.  As for wines, merlot, cabernet sauvignon, and pinot noir, as well as shiraz, sauvignon blanc, chardonnay, riesling & Gewürztraminer would be nice.

**Comment by Sunconure11** [comment]
Pretty much most of that cannot be implemented at this point in time.

**Comment by darthvader45** [comment]
I know, sounds like a lot, but hey, it seems good for an addon, if not a full-on addition to the mod.

**Comment by darthvader45** [comment]
One more thing:  How do we get the beebox to have a bonus?  Is it the diamond shaped farms, or what?  I'm stumped.

**Comment by Sunconure11** [comment]
@IceDragon200 Close?

**Comment by darthvader45** [comment]
I was just needing one last question answered, before I close this myself.

**Comment by Sunconure11** [comment]
It was already answered in the yeast page which you necroed. Use orange or red dye on a beebox.

**Comment by darthvader45** [comment]
Ok, sorry.

Edit:  Neither dye works.  Can't use it, craft it with the bee box or anything.  I think that may be for the dev build.  Release build 2.4.0 doesn't seem to have that.

**Comment by IceDragon200** [comment]
@darthvader45 Correction, Pink (gives a 9600 tick bonus) and Magenta (4800 tick bonux), I'd just throw every dye at it and see what sticks.

When I say "use" it on the bee box, I mean hold the stack and right click on a placed bee box

**Comment by darthvader45** [comment]
Found pink by experimentation, magenta I shall also try.  Thank you for clarifying
