### ISSUE TITLE
Brewing eats ingredients, doesn't go past young

### ISSUE THREAD

**Issue by gchpaco** [GrowthcraftCE/Growthcraft-1.7#268]
This is on 893085b.

Reproduction step:
- take ferment barrel
- fill with young alcohol (tested with mead, sake, grape wine)
- put brewer's yeast in
- wait

Expected outcome:
- ferment barrel full of fermented alcohol

What actually happens:
- barrel consumes yeast but doesn't change state.

I wiped the config and let it regenerate, and the relevant section of `fermenting.json` looks like it should be correct:

``` json
    {
      "comment": "",
      "item": {
        "comment": "Brewers Yeast",
        "mod_id": "Growthcraft|Cellar",
        "name": "grc.yeast",
        "amount": 1,
        "meta": 0
      },
      "input_fluid": {
        "comment": "Mead",
        "name": "grc.honeymead0",
        "amount": 1
      },
      "output_fluid": {
        "comment": "Mead",
        "name": "grc.honeymead1",
        "amount": 1
      },
      "time": 24000
    },
```

**Comment by hron84** [comment]
See #266 same issue and somehow related to GUI handling.

**Comment by gchpaco** [comment]
893085b is quite a bit further than the patch for #266 although symptoms are very similar.

**Comment by IceDragon200** [comment]
@gchpaco @hron84 Could you try the latest build for 60880a1

**Comment by esotericist** [comment]
As the person whose server @gchpaco plays on, I'm testing 60880a1 with our private pack in SSP now. Will check SMP shortly after.

Sadly, I can't accelerate the growth using an nbt editor to advance the timer. Growthcraft seems to react to editing the time tag by zeroing it. Makes testing a little slower, but such is life. :)

**Comment by esotericist** [comment]
Well, after testing with mead, it certainly seems like 60880a1 resolves the problem. I haven't exhaustively tested the various alcohol types, but given it works for the one -- given the nature of the fix -- I'm personally prepared to assume until proven otherwise it's working fine for the others.

**Comment by gchpaco** [comment]
Confirmed 60880a1 works for me with ale.  Thanks!
