### ISSUE TITLE
[Suggestion] [Milk] Add a system to make different chocolate

### ISSUE THREAD

**Issue by hron84** [GrowthcraftCE/Growthcraft-1.7#269]
It would be great if we can make different type of chocolate in growthcraft, possibly utilizing milk. I can imagine different type of milk can play a role in this, or the amount of ingredients. 

Also milk chocolates should accept fruits as "upgrade" to make them more tasty (bigger hunger/saturation buff) based on the values of the original fruit. Integrations can play a role here, especially Forestry and Harvestcraft.

**Comment by Sunconure11** [comment]
Can you please post suggestions like this on the forum for now? This is for bugs.

However, this idea might be taken into consideration.

**Comment by hron84** [comment]
@Sunconure11 What do you mean under "the forum"? The MCF post?

**Comment by Sunconure11** [comment]
Yes.

**Comment by IceDragon200** [comment]
@Sunconure11 @hron84 You guys could make use of the https://github.com/GrowthcraftCE/Growthcraft-DesignDocs Design doc repo for ideas and suggestions, I made it for that stuff

**Comment by hron84** [comment]
@IceDragon200 so I can post issues like this there? Personally, I prefer GitHub for ideas because I can get instant notification about answers in discussions like this.

**Comment by IceDragon200** [comment]
@hron84 But it is github, it's just a different repo D:

**Comment by Sunconure11** [comment]
Don't use the design documents page for posting an idea unless it is fully complete, and you are willing to send a complete pdf file via a pull request.

Also, your idea might fit in somewhere in the future, so, I'll handle it.

**Comment by hron84** [comment]
Thanks.

**Comment by killerjdog51** [comment]
Seriously, we could just add compatibility with my chocolate mod. I have milk chocolate, white chocolate, chocolate, and dark chocolate in it.

**Comment by hron84** [comment]
@killerjdog51 I don't want to hurt you, but please stop advertising your mod. Growthcraft developers can and will decide they want to integrate with your mod (you can do it btw yourself) or they rather want to go on their own way because they have different ideas in their mind (take look into the Milk module's documentation, it is a idea-rich stuff). If you want to make an integration, just do it do it, Growthcraft has a bunch of API available for you, but repeating yourself will not bring you closer to the integration.

**Comment by IceDragon200** [comment]
@killerjdog51 Hmm, saying we should add compat to a mod, making it sound like a demand, and then NOT LINKING SAID MOD. 
That's 3 strikes isn't it, well 2, no problem with asking for compat.
How am I suppose to assess the possibility of adding your mod for compat, if I don't know what and where it is?

@hron84 NINJA'D

**Comment by hron84** [comment]
@IceDragon200 I intentionally didn't mentioned he didn't linked the affected mod. I took some digging (OK, I just checked his GitHub profile) but the [mentioned mod](https://github.com/killerjdog51/Chocolate-Mod-1.7) is very poorly documented. No Curse link, no MCF page link, not a single word about the mod itself (Wiki feature is enabled, but also empty). Because everyone should know about ChocolateMod! It's a biggest famous mod on the earth! I simply don't like this attitude, and can't imagine a good communication developers behaves in this way. I strongly wish I think it wrong, but...

**Comment by killerjdog51** [comment]
I deeply apologize. I did not mean to sound demanding nor was I trying to advertise. I was just simply suggesting the possible option of compatibility. I was not trying to have an attitude, My mod is not famous or good, I am still trying to learn how to program. I also did not know however that growthcraft had a bunch of API available. And I am sorry about my communication skills, I was not born with the ability to learn how to communicate properly due to my autism. I am sorry and I hope you'll forgive me.

**Comment by hron84** [comment]
No problem. Autism is not something that comes over the wire during I read your writing. However, if you want to make your mod widely know, make some documentation or ask someone to write one. Both API and gaming documentation.

**Comment by killerjdog51** [comment]
What kind of documentation? And I'm not exactly sure what API is.

**Comment by hron84** [comment]
Gaming documentation: introduce your blocks, item and mechanics, how do you brew chocolate, how do you make dark choco and so on. Search for "spotlight" on youtube, watch some different videos from the result and you will know what i mean.
API documentation: how other developers can interact with your mod. Registering custom recipes (if there is any), interacting with your blocks, and so on. Take a look at Growthcraft developer documentation, and make something similar, but for your own mod.

**Comment by Alatyami** [comment]
We are currently working on the ingame documentation.

**Comment by hron84** [comment]
@Alatyami Sorry, my reply sent to @killerjdog51 about his own mod, not about GC.

**Comment by killerjdog51** [comment]
@hron84 I see. So basically a wiki?

**Comment by Alatyami** [comment]
For external we ate using the github wiki.  After that is updated then we
will look into doing some ingame books.

**Comment by killerjdog51** [comment]
Github has a wiki?!.... sense when? And what kind of ingame books?

**Comment by hron84** [comment]
@killerjdog51 GH has a wiki support for a years, you can enable it on the settings of the repository. Ingame books: you can either spawn a normal vanilla written book - but this cannot contain images -, or you can make custom books, like how Botania or Immersive do it.

**Comment by killerjdog51** [comment]
hmmm, that sounds interesting. but difficult to do.

**Comment by IceDragon200** [comment]
https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/issues/1
