### ISSUE TITLE
GameRegistryDumper Preview Builds

### ISSUE THREAD

**Issue by SvEgiiVEteR** [GrowthcraftCE/Growthcraft-1.7#279]
growthcraft-1.7.10-2.5.0-complete--7f278f1.jar
https://paste.ee/p/uYTcI
if     B:"Enable Game Registry Dump"=true

**Comment by IceDragon200** [comment]
@SvEgiiVEteR This should be fixed in the latest build, I now check if the item has subtypes, hopefully the item was implemented correctly

**Comment by SvEgiiVEteR** [comment]
2.5.0-complete--74ec77e
http://paste.ee/p/oKroQ
sad .... the problem remains ... ((

and one request ...
if you can fix it.
You can to make what  create a file server too?
GameRegistry_Blocks.txt
GameRegistry_Items.txt

**Comment by IceDragon200** [comment]
@SvEgiiVEteR We can't create the sub blocks and sub items on the server, the methods are only available on the clients :(

**Comment by IceDragon200** [comment]
@SvEgiiVEteR Could you try the latest build RC12 or later (Release Candidate 12)

**Comment by SvEgiiVEteR** [comment]
http://paste.ee/p/6GvN2
sad .... not working
Here is the complete log can help you...
http://paste.ee/p/cGvgv

**Comment by IceDragon200** [comment]
@SvEgiiVEteR Man, this is madness, try the latest build RC13

**Comment by SvEgiiVEteR** [comment]
@IceDragon200 Thank you! everything now works))
