### ISSUE TITLE
Using Growthcraft Community Edition in my Modpack

### ISSUE THREAD

**Issue by LTornadoGaming** [GrowthcraftCE/Growthcraft-1.7#287]
CrystalWing
DamageIndicators
Ars Magica 2
Mine & Blade Battlegear 2
AnimationAPI
ArchimedesShipsPlus
Backpack
BetterStorage
BiblioCraft (Including BiblioWoods:Forestry and BiblioWoods:Natura)
BloodMagic
Carpenter'sBlocks
Chisel2
CodeChickenCore
CraftableHorseArmour
EnderCompass
ExtraTiC
ExtraUtilities
Farlanders
Forestry
Guide-API
IguanaTinkerTweaks
InventoryTweaks
JourneyMap
MagicalCrops and MagicalCropsArmoury
Mantle
MovingWorld
Natura
NEIAddons
NEIIntegration
NotEnoughItems
OpenEye
Optifine
Pam's HarvestCraft
Pam's Simple Recipes
Roguelike Dungeons
RopeBridge
StorageDrawers
TConstruct
Thaumcraft
TiCTooltips
Tinkers Defense
TMechworks
TravellersGear
TwilightForest

**Comment by IceDragon200** [comment]
@LTornadoGaming But but but, Growthcraft isn't on your list, why don't you make a google docs page with the mods

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft

See I like to link to both the mod list and your request here ;O

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)

If you would like to make changes to your entry in our mod pack list, send us a message on the irc, or create an issue here.
