### ISSUE TITLE
Using GrowthcraftCE in modpack

### ISSUE THREAD

**Issue by Spleenczar** [GrowthcraftCE/Growthcraft-1.7#290]
This is the mod list:
https://docs.google.com/spreadsheets/d/1Mpbp9HUoob63up8GIu34Cam-GPuggZTM1eR3g5MT56Y/edit?usp=sharing

Do I have permission to use this mod in the pack??

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)

If you've like any changes made to your entry in our wiki, let us know in the irc, or open an issue here.
If you have any problems with Growthcraft, please open an issue here, we'll address it if possible, asap.
