### ISSUE TITLE
[CRASH] Startup

### ISSUE THREAD

**Issue by f0kx** [GrowthcraftCE/Growthcraft-1.7#297]
http://paste.ee/p/LQLU8

**Comment by Sunconure11** [comment]
Clear your old config files.

**Comment by f0kx** [comment]
completly delete it?

**Comment by IceDragon200** [comment]
@SugarDaddii: everything under `config/growthcraft/bees/`, `config/growthcraft/cellar/`, `config/growthcraft/core/`, `config/growthcraft/milk/`,

**Comment by f0kx** [comment]
thx guys you helped me alot
