### ISSUE TITLE
Hopper under fruit press removes input items, not bonemeal

### ISSUE THREAD

**Issue by tehFoxx0rz** [GrowthcraftCE/Growthcraft-1.7#298]
So I was trying to automate the fruit press, which was going mostly well - a hopper put the grapes in through the sides, and an Immersive Engineering pump and pipes extracted the liquid, but when it came to dealing with the waste bonemeal produced, I tried to put a hopper underneath since that would be the intuitive way to remove it (and the only way with vanilla hoppers, at that), but I found it was just removing my grapes.

Using 2.5.0.

Naturally, this is a big hurdle to any automation!

**Comment by IceDragon200** [comment]
@tehFoxx0rz Should be fixed in 2.5.1 or 2.5.2
