### ISSUE TITLE
Disabling milk or honey fluid blocks causes a texture stitching crash

### ISSUE THREAD

**Issue by tehFoxx0rz** [GrowthcraftCE/Growthcraft-1.7#299]
Milk crashlog: https://dl.dropboxusercontent.com/u/66131226/crash-2016-03-31_22.39.34-client.txt
Honey crashlog: https://dl.dropboxusercontent.com/u/66131226/crash-2016-03-31_22.48.41-client.txt

I have Automagy which adds a milk fluid block, and Biomes o' Plenty and The Erebus which both add honey fluid blocks, hence trying to disable GC's versions, since the config option is there!

**Comment by Alatyami** [comment]
Thank you for the logs. We'll look into it.

**Comment by Sunconure11** [comment]
Close if this user reports it has been resolved?
