### ISSUE TITLE
Add interaction for utilizing pipes from other mods.

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#3]
> Add plugin networking with Ender IO, Thermal Dynamics and Mekanism.

**Comment by IceDragon200** [comment]
As of this writing, the following mods where tested:
`Buidrcraft 7.0.17 with Buildcraft-Compat 7.0.9`
`Thermal Dynamics 1.1.0-161`
`Ender IO 2.2.8.381`

Basic pipes, ducts and conduits (whatcha ma calls it) worked fine with the Fermenting Barrel and Fruit Press: in addition I pumped the liquids into the mods respective fluid storage, only ender IO didn't provide a storage block for "other" liquids.
`Ender IO` resvoirs only accept water, and I forgot to test `Ender Storage`...

[Screenshot](https://dl.dropboxusercontent.com/u/72618186/screenshots/Minecraft/2015-07-30_15.10.40.png)

Unless I'm missing something with "plugin networking"

**Comment by Alatyami** [comment]
Well ... then .... that was an easy request to fullfill. We got that from the forums.

**Comment by Ar97x** [comment]
Good to hear it. I'll try to find another mods with pipes/fluiducts to
test. If possible, try with Extra Utilities and Mekanism.

**Comment by IceDragon200** [comment]
@Ar97x @alatyami Mekanism and Extra Utilities also work

I did an isolated test with these, since my main minecraft takes forever to start
`Mekanism 8.1.7.252`
`Extra Utilities 1.2.8`

[Screenshot](https://dl.dropboxusercontent.com/u/72618186/screenshots/Minecraft/2015-07-30_19.49.42.png)

Both also had barrels and tanks generated for the liquids

**Comment by Ar97x** [comment]
Great. I think they have all coded to transport and store any liquids
included on the mods list.

**Comment by IceDragon200** [comment]
@alatyami @Sunconure11 Can't we close this, pipes work from all the mods mentioned

**Comment by Sunconure11** [comment]
Sure
