### ISSUE TITLE
Modpack Request for Swisscrafting.ch

### ISSUE THREAD

**Issue by onekintaro** [GrowthcraftCE/Growthcraft-1.7#309]
Hello,
I am kintaro the Admin of Swisscrafting.ch, we planned to make a Swiss Public Tech Server.
We wanted to ask whether we like to get the permission for the Mod Growthcraft in our Modpack for the Server.
Currently the server is still in ClosedBeta, and we use a Whitelist. But we Plan to make the Server in a few days Public.
But we do not do this without permission for the Mod.

The List of Mods in the Pack can be found on http://www.technicpack.net/modpack/swisscraftingch.823079/mods
(Not Final)

thank you in advance.

greetings from Switzerland
Kintaro

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
