### ISSUE TITLE
Modpack Request

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#310]
Hi,
I am currently making a modpack for a small group of players on a small server and we would love to include growthcraft in the pack, but not without your permission, of course ;)
(The modpack is unlisted, and only people in the group can access it)
Thanks in advance!

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
