### ISSUE TITLE
Allow thistle to be spread by beeboxes

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#311]
I've noticed that while Thistle registers as a valid flower for the beebox, and thus, allows for production of honey and bees, it is incapable of being spread by beeboxes, even if I use forced code to make it spread, like BoP flowers. Could we allow thistle plants to be spread by beeboxes?

Also, I've noticed it barely spreads, at all. It should be a bit faster, like in the old plans, and if it is using code ripped straight from mushrooms, it should spread in light too. It should be fast enough to reflect its weedy nature, but not fast enough to cause lag and such.

**Comment by IceDragon200** [comment]
@Sunconure11 It has a 1/45 chance of spreading (bad logic D;), I've fixed it in development, currently creating the build :)

**Comment by Sunconure11** [comment]
http://pastebin.com/hKYjNCdY

Let me guess, I have to input the chance of it spreading now?

**Comment by IceDragon200** [comment]
@Sunconure11 Nope, that's hard coded, I never did test that...

**Comment by esotericist** [comment]
Anecdotal commentary: On my server, running 2.5.1, I have found entire FIELDS -- plural stacks of thistle per when finally cleaned up -- of unwanted thistle from players failing to clear it out thoroughly when they find it.

I think having the bee box spread thistle is sensible, but increasing the base rate seems possibly unnecessary and prone to consequence.

**Comment by IceDragon200** [comment]
@esotericist It's configurable in development, however, I do not recommend using the builds on your server just yet, it has a few bugs and NEI integration issues
