### ISSUE TITLE
Icarus Evolved Modpack

### ISSUE THREAD

**Issue by professorsawyer** [GrowthcraftCE/Growthcraft-1.7#316]
Hi, I'm here to ask permission to use your addition to the Growthcraft mod in my servers modpack.

A list of the current mods in the pack can be found within the permissions section on our technic page.

[Icarus Evolved](http://www.technicpack.net/modpack/icarus-evolved.835725/permissions)

I plan to make the pack public with your permission to use this mod.

Thanks!

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)

If you've like any changes made to your entry in our wiki, let us know in the irc, or open an issue here.
If you have any problems with Growthcraft, please open an issue here, we'll address it if possible, asap.
