### ISSUE TITLE
Growthcraft is attempting to load NEI integration on the wrong side

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#319]
http://pastebin.com/AQeD7CAm

**Comment by IceDragon200** [comment]
@Sunconure11 Could you test this again using the latest dev build?

**Comment by Sunconure11** [comment]
I'll see about doing it tomorrow, I'm going to go to bed.

**Comment by Sunconure11** [comment]
I think this has been fixed. Sorry about the hold up.
