### ISSUE TITLE
Certain fluid automation blocks reset fermentation barrel progress

### ISSUE THREAD

**Issue by esotericist** [GrowthcraftCE/Growthcraft-1.7#322]
GC 2.5.2, forge 1614.

If you set up an Extra Utilities fluid transfer node with a filter, or a Thermal Dynamics fluiduct+servo with a whitelist, every time they attempt to pull from a fermentation barrel -- even if it fails due to the barrel not having the matching fluid -- progress in fermentation is reset back to zero.

There might be other fluid transfer tools that do similar, but those are the two I encountered it with. I hear reports that EnderIO conduits do not, and I've confirmed thaumcraft decanting golems do not so there's some difference in handling somehow, but it really seems like the barrel should behave consistently regardless.

**Comment by IceDragon200** [comment]
@esotericist 
If I remember clearly, the barrel will refresh it's recipes when the fluid changes, if the fluid is the same, it should just ignore it and carry on, otherwise it would reset the recipe and time...

I'll need to look into it some more, or just go back to the inefficient "search for recipe every tick" method, which worked, but was really cray cray in terms of performance

**Comment by IceDragon200** [comment]
@esotericist Could you give the latest development build a spin (remember to backup your world),
you can find them here https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/307

**Comment by esotericist** [comment]
Currently preparing a push for the mod pack for my server. Will try out the dev build in SSP afterwards. It's more than just me and one other person now, so I have to be all responsible about data integrity and stuff. :D

**Comment by IceDragon200** [comment]
@esotericist Pfft, just break everything, you get bug reports faster that way :P

**Comment by esotericist** [comment]
This is my social life, not my day job. :D

**Comment by esotericist** [comment]
Problem persists in SSP with both extra utilities transfer nodes and thermal dynamics fluiducts with dev build 840bc88.

**Comment by IceDragon200** [comment]
@esotericist What are these mods even doing to break my beloved barrel ;_;

**Comment by esotericist** [comment]
"Do you have it now?" "No, I'm busy." "What about now?" "No, I'm trying to ferment--" "Is it there now?" "NO!" "I'm pulling some of the stuff now." "It still isn't there yet!"

**Comment by IceDragon200** [comment]
@esotericist Sounds ... very accurate...

**Comment by esotericist** [comment]
@IceDragon200  Well, you asked. :D 

More seriously, is something ridiculous happening like them 'changing' the liquid contents by zero when they make the attempt and realize it's not what they want?

Or is it somehow possible for just the query as to contents to cause this effect?

**Comment by IceDragon200** [comment]
@esotericist That was what I was thinking as well, they probably pulled everything out of the barrel for 1 tick, and then put it back

That would cause the barrel to refresh it's recipe within that tick, seeing as no fluid was present right there and then, it could assume "oh, the recipe is inavlid, better null it", a tick later "oh fluid is available, lemme find the recipe"

**Comment by esotericist** [comment]
@IceDragon200 And people wonder why forge 1.8.9 was getting new fluid infrastructure...

**Comment by IceDragon200** [comment]
@esotericist Well there is a new build up, I doubt it would do anything to this bug though, but it's worth a shot

**Comment by IceDragon200** [comment]
@esotericist I've added a config option to fallback to the old barrel behaviour (it looks for the recipe every tick), it can be found in `growthcraft/cellar.conf` under `Fermenting Barrel` as `Use Cached Recipes?`

**Comment by esotericist** [comment]
Sorry, got kinda consumed by a non-minecraft project for a while. How stable are the dev builds at this point? Is it still hazardous to attempt on our server?

**Comment by Sunconure11** [comment]
They are safe to use at this point on a server. I'm running it fine on a server, if anything, I'm having issues with Stellar Sky, which I need to wait for the dev to respond back on.

**Comment by esotericist** [comment]
@IceDragon200 On 42bf692, and i'm still seeing similar behavior with B:"Use Cached Recipes?"=false

When I mouseover the progress arrow on the left, I can see it oscillate between 1 and 2 for the progress (out of 24000)

**Comment by IceDragon200** [comment]
@esotericist D8< These dreaded fluid pipes are wrecking my barrel beyond usage!

Okay, Extra Utilities and Thermal Dynamics right? (goes to pick up a deobjf build for both)

What versions are you running for both?

**Comment by esotericist** [comment]
@IceDragon200 Those are the ones.

Notably, they were both mainly written by the same person (RWTema) so it's not terribly surprising in retrospect that if one of them is doing something pathological, the other might be doing the same.

Sorry about all the trouble. :(  But it seems like since I haven't heard about/encountered any other mods having this grade of trouble with either of those fluid transport options, it logically SHOULD be resolvable. Somehow. 

... I hope?

**Comment by esotericist** [comment]
@IceDragon200  Oh, versions. Didn't see you ask that question earlier. It's: 1.2.12 for Extra Utilities, and 1.2.0B2-169 for thermal dynamics.

**Comment by IceDragon200** [comment]
@esotericist Well sorry it took so long, I derped, and derped real hard, but, everything should be fixed in the new dev build, give it a spin :)

**Comment by esotericist** [comment]
@IceDragon200  Oh dear. Giving it a try soon.

Is the cached recipes setting still pertinent?

**Comment by IceDragon200** [comment]
@esotericist Shouldn't matter anymore 3:

**Comment by esotericist** [comment]
Yeah. Confirmed that everything works just as it should both with and without that setting. I think we can call it good. Thanks for your perseverance!

**Comment by esotericist** [comment]
... I didn't mean to close this. Misclick. Should probably stay open until 2.6.0 releases proper.

**Comment by Sunconure11** [comment]
Uh, if it has been fixed, then it should be closed.

**Comment by IceDragon200** [comment]
@esotericist I'll add it to the bugfixes list on the 2.6.0 release page, so we can close it

**Comment by esotericist** [comment]
@IceDragon200 @Sunconure11 Alright. I'm used to organizations where issues aren't closed until they're resolved, and 'resolved' is generally not considered to be the case until it's user-facing in a stable release. Since that's not how you guys do it, I'll try to remember in the future.
