### ISSUE TITLE
When you left click break the drained ricotta curds turns into cheddar.

### ISSUE THREAD

**Issue by cheesealmighty** [GrowthcraftCE/Growthcraft-1.7#323]
I'm in the 2.5.2 version of Growthcraft, Forge version 10.13.4.1614

When I was trying to figure out how to turn ricotta curds into ricotta proper, I tried breaking them. They just turned into not-drained cheddar curds. Tried it few times, same thing happened. While we're at it, how do I turn them into ricotta bowl exactly, since pressing it doesn't seem to work?

Thanks.

**Comment by IceDragon200** [comment]
@cheesealmighty Don't break it with the left click!
As for the recipe: Craft the ricotta curds with a bowl

Should be fixed in latest development, however you still lose drying progress if you break it using left click, the resistance was raised to discourage breaking the block with the left click
