### ISSUE TITLE
[Sugesstion] add an beer pull,etc

### ISSUE THREAD

**Issue by Dominikzocker141** [GrowthcraftCE/Growthcraft-1.7#324]
can you add this thinks:
tap/beer pull:
http://www.allmystery.de/dateien/70749,1300219992,zapfhahn.png
A beer glass and a wine glass please.
(i will build a public bar.) :)
sorry for my bad english i am from austria

**Comment by IceDragon200** [comment]
@Dominikzocker141 Thank you for the suggestion, the team is currently considering it for a future feature :)

**Comment by Alatyami** [comment]
This is on the Growthcraft 1.10/1.11 Feature List

https://github.com/GrowthcraftCE/Growthcraft-1.11/issues/4
