### ISSUE TITLE
What counts as a magic biome and why The End isn't one?

### ISSUE THREAD

**Issue by cheesealmighty** [GrowthcraftCE/Growthcraft-1.7#325]
I was trying to get some ethereal yeast and I kinda assumed end would be a magic biome, but apparently it's just cold. So, what does exactly count as magic? I'd assume thaumcraft magical forest, rainbow forest (?) from chromaticraft, twilight forest and ominous woods and mystic grove from biomes o plenty. 

But what if I'm in a modpack without these mods, then what am I to do exactly? I can see the balancing issue, but this could be an issue.

**Comment by Sunconure11** [comment]
You are correct with your definitions of magical biomes.

And if you are not using these mods, you can use the user API to define ethereal yeast for different biomes.

https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/User-API-2.5.x

This might also be of use to you, when setting up definitions:

https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/BiomeDictionary.java

**Comment by cheesealmighty** [comment]
Ah, also I found this, for future reference: 
https://www.reddit.com/r/feedthebeast/comments/1qyzbu/list_of_magical_biomes_w_biomes_o_plenty/

**Comment by cheesealmighty** [comment]
Oh, thanks, I actually have BoP so I'll try to find the biomes, but thanks for the answer.

**Comment by Sunconure11** [comment]
NP

**Comment by IceDragon200** [comment]
@cheesealmighty @Sunconure11 I assume we can close this
