### ISSUE TITLE
Salt default settings, and OreDict support

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#338]
Should we change the default from false, to true… so that people don't spend any time figuring out why they can't get saltwater from the Ocean? Probably a good idea, unless there's a reason for defaulting to false that I'm overlooking.

Edit: Also, would it be possible to get oredict support for the cheese recipe on salt, if it isn't in there already?

Thanks!

**Comment by IceDragon200** [comment]
@PitchBright Ocean salt defaults to false to avoid "ZOMG I GOT SALT WATER FROM THE OCEAN INSTEAD OF WATER!" issues, besides people should read their configs.

As for the ore dictionary support, salt is registered as `materialSalt` and `foodSalt`, we use `foodSalt` for butter and cheese recipes

**Comment by b0bst3r** [comment]
Can you make it then that salt water is only available from Deep Ocean? It's unlikely a person looking to fill water buckets etc would head to deep ocean to get it.

**Comment by PitchBright** [comment]
I'm not a proponent of that idea @b0bst3r… saltwater is found in the Ocean, IRL.

**Comment by Sunconure11** [comment]
To add onto this idea, register salt blocks as blockSalt.
