### ISSUE TITLE
Can't flavor cheese curds

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.7#342]
Minecraft 1.7.10 forge 10.13.4.1614
GrowthcraftCE 2.5.2
I reset the Growthcraft Milk configs and did a DIFF with the newly generated config - same file.

I can make "milk curds" (yay!). I have a cheese vat that I made 5 buckets of milk into 5 "milk curds" buckets, which is an odd idea.
From what I understand from the wiki and the design document, I now need to add salt and some other ingredient to create a specific kind of curds. 
I then must do... something unspecified to somehow remove the "milk curds" from the vat, and craft the curds with a cheese cloth. I'm having trouble with this part.

I add salt - it accepts 3 salt at once, but WAILA does not show that there is salt added. I can right click and take the three salt back out again.
With three salt in the vat, along with 5 curds, I try to add another flavoring agent, but nothing is accepted.
I have tried 
- Growthcraft Grapes (to make Gorgonzola)
- Watermelon (confirmed on foodFuit list, to make Gorgonzola)
- pumpkin (to make cheddar)
- Orange dye (to make cheddar)

None are accepted to my salted cheese.

If I remove all the salt, I can add up to three flavoring items (eg - 3 orange dye) but once all three are loaded, I can add no salt. Again, if I right click I can take the dye back out again.

If I put in one salt and one dye, nothing happens when I right click, no progress is shown on WAILA, and WAILA shows that the vat still contains 5 buckets of "milk curds". If I then put in either one salt or one dye, and then right click, I start pulling out the flavoring agents again. And I still can't get the milk curds out.

I have tried waving the sword ritually over the vat with one salt and one orange dye. No change.
I have tried waving a cheesecloth ritually over the vat with one salt and one orange dye. No change.

I have sacrificed a chicken and waved that over the vat. The vat was unimpressed, no change.

I assume I can't get the curds out because I need to put more things in, but it's not clear what.

**Comment by Syndaryl** [comment]
I still have heat under my vat. It is a block of netherrack on fire, if that matters. WAILA shows the heat flickering between 99% and 100%.

**Comment by Syndaryl** [comment]
(I also tried removing the curds with a bucket, and with a bottle. No dice)

**Comment by Sunconure11** [comment]
First, add milk to it.

Make sure it is adequately heated. Then place rennet and starter culture it, and break up the curds with a sword (right click on the vat)

Afterwards, add the flavoring, and wait.

**Comment by Syndaryl** [comment]
As per my report, I already did those things and received the curds. My problem is not making the curds.

It's been an hour since I've added one salt and one orange dye ("flavoring") to "milk curds" in the Cheese vat, it does nothing.

**Comment by Sunconure11** [comment]
You did not mention rennet at all though. Get rennet by killing a baby cow and boiling its stomach, or boiling a thistle plant, and try adding it into the curds.

**Comment by Syndaryl** [comment]
My appologies for not mentioning, but yes, I made the rennet - can't get to the milk curds until you put in rennet. I bucketed off the whey and put it in a BC tank.

**Comment by IceDragon200** [comment]
@Syndaryl You could be experiencing the recipe order bug?

if you placed the dye before the salt, the recipe would not be accepted.
You can try the latest development build which fixes the issue, it's safe for use https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/307

**Comment by Sunconure11** [comment]
What order are you placing the ingredients in? There was a bug where you had to put in a specific order until recently.

https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/307

**Comment by Syndaryl** [comment]
At this point I have lost track of what order, although I thought salt first. Regardless, I'll go try the dev build :)

**Comment by Syndaryl** [comment]
Bingo. I set all the maturation times to 1 tick to speed testing (and turned on debugging in case it barfed so I didn't have to wait another 5 minutes to restart). Launched, logged into my world, and I have a vat full of cheddar cheese curds. 
Right clicking on the vat empty handed does nothing. 
Right clicking with a bucket does nothing. 
Right clicking with a cheese cloth took the cheese curds out of the vat and consumed the cheese cloth. This was a bit unexpected because the design doc (only documentation on these steps I can find) says to strain it via crafting and I expected that to be the use of the cheese cloth.
I'm assuming I'm at the step where I press it in the cheese press, but I can't figure out how to put the cheddar cheese curds in the cheese press.

**Comment by IceDragon200** [comment]
@Syndrayl: Well the cheese press can be a PITA (sorry about that ;P).
But before that, place the curds below a block (optionally above a Pancheon to collect whey for ricotta cheese), allow it to drain, you'll know if its dry if you can right click on it afterwards (usually it stops dripping), if you have WAILA, then you'll get a progress status in the UI.

After the curds have been drained you can place it into the cheese press, then right click the vat **with an item in hand**, if you try to click again with an empty hand, it will remove the cheese.

Sadly, there isn't an indicator if the cheese is pressed without WAILA (suggestions are welcome), so wait a bit while the press is screwed down. 
Do the reverse step to remove the newly pressed cheese (unscrew, right click with empty hand).

Place the freshly pressed cheese block into the world (depending on the kind, you may to wax it), wait for a bit, let it age, finally if all is well you should be able to right click the cheese to extract slices, or just shatter the block to get all the slices.

And now that I've stated all this, I just realized how hard this really is D:

**Comment by Syndaryl** [comment]
Got it. The cheese curds are shaped like a bag hanging from a string! Now that I know the step that's for, it makes a lot more sense.

Every step makes a LOT of sense from the actual cheese making process (except using a sword to cut the curds - making a dedicated curd cutter might be a bit much, or not, but the sword is the step I keep forgetting).

I think a big help would be putting a UI on the cheese vat, and some tooltips on E.G. the curds. "Hang me to dry!" and so forth.

Also would be helpful of course is a full step-by-step writeup of the process from start to end (which is partly why I've been enumerating what I've done so insistantly - so the next person searching isn't left scratching their head). I'll go sit down and write it up while watching some TV. I should have it for you tonight or possibly tomorrow.

**Comment by Syndaryl** [comment]
I know this is a new module. It's awesome, and GC-CE in general is awesome, I'm really loving it. It's just suffering from "new thingy-itis", where there's no documentation and not a lot of chat on forums on how to do it :D

**Comment by Ar97x** [comment]
We'll try to get ingame books as help for all the modules as soon as we
can. But the UI thing for the Cheese Vat and Butter Churn are something to
consider.

**Comment by Syndaryl** [comment]
A draft complete tutorial (and to make it clear, I completely relenquish all rights to this text. Remix, republish, edit, mangle, maul, with or without attribution as you wish)

# From Chump to Cheesery: a step by step tutorial for GrowthcraftCE Milk cheese making, for GrowthcraftCE 2.5.2

## Craft your tools:

Craft 1 sword (you can use an existing sword - I keep a wood one handy because my modded tools don't count)
Craft bottles - It's convenient to have 3. You can get by with one if you have a fluid container for cream, but Growthcraft usually wants for lots of bottles.
Craft buckets - it's convenient to have 6. You can get by with less if you have at least 6 buckets of storage in tanks.
Create two brew kettles
    Create two cauldrons. Craft each cauldron by itself to create two Brew kettles. The kettle requires a hot block underneath it - any block on fire or a block of lava are two vanilla choices. It's recommended to burn netherrack instead of eg wood as you will burn through a lot of wood otherwise.
Create a cheese vat
    Craft one of those brew kettles by itself to create the cheese vat. Keep the other, you need it. The cheese vat requires heating, just like the brew kettle.
Craft a Culture Jar
    This is crafted out of a cauldron shape using panes of glass, with a wood plank in the top center (think a "cork"). It accepts mod added glass panes and mod added planks. Like the kettle and the vat, the culture jar requires heating.
Craft a Pancheon - this is used for separating milk, and collecting drained whey.
    This is crafted out of a boat shape using balls of clay. It does not need heating.
Craft a Cheese cloth
    This is crafted out of a hollow box shape using string. It must have the empty cell in the middle.
Craft a Cheese Press
    You need 3 wood slabs, one chest, and 5 iron ingots. Put a row of wood slabs on the bottom of the grid. Put the chest in the center. Fill the other slots with iron ingots, in an upside-down boat shape. The cheese press does not need heating. It has a nice animation.

## Collect and craft ingredients:

Collect Milk
    You will need five buckets of milk for the cheese, and a sixth bucket of milk for making your starter culture.
Collect either one thistle or one calf's stomach, for making rennet. Rennet is what actually curdles the casien in the Milk to make chesse. Calves stomachs produce an enzyme to do this, as does the thistle plant.
    When you find thistle, don't harvest all the thistle at once, it spreads itself and thus is renewable.
    Alternately breed and kill a calf before it matures into a cow. The calf has a chance to drop some stomachs - the default chances are 25% chance of dropping 2-4 stomachs (cows have four stomachs, animal rennet is made from calf stomachs).
Collect flavoring agents
    You will need at least one salt (2 salt if you want to make Asiago cheese). Salt is made by collecting a bucket of water from an ocean biome, and then boiling it in a furnace. Mod-added salts such as from Pams Harvestcraft or Mechanism may also be used.
    You will also need one other flavor agent - see https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Milk-Cheese-Production#cheese-recipes for the full list of recipes.

## Make Cheese!

Create rennet
    Brew a stomach or a thistle in a Brew kettle with a bucket of water. This produces a bucket of rennet. Remove the bucket of rennet by right clicking on the kettle with an empty bucket.
    Other rennet liquids may also be used instead of Growthcraft rennet if tagged correctly.
Separate Milk into cream and skim milk
    Put a bucket of milk into the Pancheon and wait for it to separate; you can tell when it's done as the milk turns slightly more yellow-cream colored (If you are colour blind, I recommend installing WAILA - it will show a progress indicator). Right-click your three bottles on the Pancheon, and you will get first a bottle of cream, and then two bottles of skim milk. Set the cream aside for other crafting.
Create starter culture.
    Right click  the two bottles of skim milk on the Culture Jar to empty the skim milk into it. Leave the Culture Jar over heat, and the skim milk will be consumed and turned into a Starter Culture. There will be some waste skim milk.
Put rennet, five buckets of milk, and starter culture in the cheese vat by holding them and right clicking on the vat. Make sure there is heat under the cheese vat.
Right click on the vat with a sword. Wait.
Once the mixture separates into whey (darker greenish) and curds, bucket out the whey (you can use that to make another kind of cheese later, or throw it out).
Add your flavoring agents, then right click on the vat with a cheesecloth to remove the cheese curds. 
    The number of each flavoring agent matters, so be careful. Earlier versions had a bug where the order of ingredients mattered - if it's not working, update to the latest development build.
Hang the cheese curds from the underside of a block to drain excess whey. 
    If you hang them over your Pancheon, the Pancheon will collect whey for you. Otherwise the whey is lost.
Place the curds in the press by right clicking on the press.
_Hold Something In Your Hand_ and then right click on the press to make it press the cheese (if you don't hold something, it will take the cheese curds out instead of pressing it). Wait, and the press will produce a young cheese.
Place the young cheese block and wait, and it will age. Some kinds of cheese (EG cheddar, Monterrey Jack) need a waxed rind to age - wax is obtained from beekeeping.

**Comment by Ar97x** [comment]
Well, thank you very much for your time and dedication on it. We can surely
use it on the in-game book for Milk module. We'll make a review and see if
there's anything to be changed or added, but for now it's a great start :D

**Comment by Syndaryl** [comment]
I'm back - how do you wax a cheese? I have an unaged, unwaxed cheddar cheese, and some beeswax, but I can't find any recipes in NEI and if I place the cheese, clicking on it with the wax doesn't do any thing.
And if I try to break the unaged, unwaxed cheddar, it gets destroyed. :(

**Comment by Ar97x** [comment]
You use red wax for Cheddar and black wax for Monterrey. And the wax is
used right clicking the cheese block before aging.

**Comment by Sunconure11** [comment]
@Syndaryl Was this ever solved for you? If so, then close this.

**Comment by Syndaryl** [comment]
Oops, yes. Sorry!
