### ISSUE TITLE
Salt problems

### ISSUE THREAD

**Issue by Darktotaled** [GrowthcraftCE/Growthcraft-1.7#344]
Hey guys. I love you guys for bringing back growthcraft =D

I don't know what it's happening but when i go to the ocean with a bucket, i get normal water only '-'
Also, can you make salt ore dict with magneticraft and mekanism salt?

btw, growthcraft version 2.5.0
Forge latest build atm

Keep the great work

**Comment by Ar97x** [comment]
You must enable it on the configs. Core.conf is the file you should look
for.

**Comment by Sunconure11** [comment]
Salt has already been oredictionaried. Try the preview builds. These SHOULD work with salt from those mods.

https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/307

**Comment by IceDragon200** [comment]
@Darktotaled While both @Ar97x and @Sunconure11 are correct they really didn't mention the option you need to enable:

Under `config/growthcraft/core.conf`

```
salt {
    # Should we enable the bucket of salt water event handler?; Default : false
    B:"Bucket Ocean Salt Water"=false
}
```

Set "Bucket Ocean Salt Water" to true

**Comment by Darktotaled** [comment]
oh i see gonna give it a look. Thanks guys.
