### ISSUE TITLE
A manual of some kind

### ISSUE THREAD

**Issue by Darktotaled** [GrowthcraftCE/Growthcraft-1.7#345]
Hey guys o/
It's not an issue but a suggestion
Can you guys make a in-game manual of some kind or an integration with NEI
Been going back and forth from game to wiki to make cheese as it doesn't have a recipe there.
Keep the good work and i love you all =)

**Comment by Ar97x** [comment]
Both suggestions are on the plans, NEI has all crafting recipes and Waila
is really helpful, also. But we'll work to make the mod as clear as
possible for everyone :)

**Comment by Darktotaled** [comment]
cheese production is something that i really like and i can't make ricotta as i can't find it in the wiki and it doesn't appear on NEI. Once again, thank you for keeping this beautiful mod alive and making it bigger ;)

**Comment by Ar97x** [comment]
Ricotta follows almost the same process, but instead of milk it uses the
whey residue. You should check the design doc:
https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/blob/master/GrowthCraft%20Milk%20Module.pdf
, because I don't remember the entire process ;P

**Comment by Darktotaled** [comment]
like 5 buckets of whey instead of milk?

**Comment by Ar97x** [comment]
Yes. And the ricotta curds after drained must be crafted with a bowl to
create the consumable item.

**Comment by Darktotaled** [comment]
actually with 4 bowls. 5 buckets of whey plus starter culture>take out one whey bucket after done>cheesecloth>drain>press>craft with 4 bowls

**Comment by Ar97x** [comment]
Oh right. I actually haven't made it yet in game, so I don't have it fix on
my mind.

**Comment by Alatyami** [comment]
As an update, we have been investing a lot of time into our GitHub wiki. Check it out for detailed information, here is the [Growthcraft Milk](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Milk) page.

**Comment by vrnRaptor** [comment]
It would be nice to add a tutorial book. Something like this:
![2016-11-16_03 15 26](https://cloud.githubusercontent.com/assets/13599993/20329768/494d29ce-abab-11e6-824f-1cb5cf9b8e74.png)

**Comment by Alatyami** [comment]
We have plans for this .... but it will not come until we release the Growthcraft for 1.10

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.

We are looking at implementing this request in newer versions.
