### ISSUE TITLE
UM... (Bug with thistle settings)

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#346]
So I decided to set thistle to the default growth rates, and uh... (spread rate of 20)

https://www.dropbox.com/s/f478aqr4mn17dje/Screenshot%202016-04-29%2019.55.10.png?dl=0

https://www.dropbox.com/s/atepbm0ou4iblyr/Screenshot%202016-04-29%2019.57.09.png?dl=0

https://www.dropbox.com/s/vyalxq1hzrkl46u/Screenshot%202016-04-29%2019.59.45.png?dl=0

**Comment by Alatyami** [comment]
That's a lot of potential rennet.

**Comment by Sunconure11** [comment]
Presumably fixed, will close for now unless I run into this again.
