### ISSUE TITLE
Eating honey consumes the flowerpot

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.7#348]
Eating honey does not return the flowerpot. I expected the flowerpot to be returned, like a soup bowl, milk bucket, or potion bottle.
_Correction_ - eating honey resulted in the flower pot being placed on the ground. That's odd.

**Comment by IceDragon200** [comment]
@Syndaryl: Probably it returned to your hand after eating and you placed it down (right click to eat, right click to place)
