### ISSUE TITLE
Inventory Tweaks and Growthcraft 2.6.0 are not playing along nicely.

### ISSUE THREAD

**Issue by cheesealmighty** [GrowthcraftCE/Growthcraft-1.7#356]
I just installed 2.6.0 version, all seems well at the moment (Well, other than fierce thistle spread, god that thing is everywhere suddenly, I should decrease that). 

But there's an issue when interacting with the fluid containers, say if you have a bottle in your hot bar and more in your inventory, when you right click to fill it up from the container and the inventory tweaks tries to pull the empty bottle (or bucket) from your inventory into your hot bar, the client suddenly disconnects. Thankfully there's no crash. I pulled the error message from the server logs:
http://paste.ubuntu.com/16213747/

**Comment by cheesealmighty** [comment]
I should probably add that it was working fine in 2.5.2 as well. And that last line is not relevant (Although it keeps saying that same damn thing over and over again in the logs, I'm guessing since I have a pipe connecting to it?)

**Comment by IceDragon200** [comment]
@cheesealmighty Seemed to work fine for me (this was a SSP test though), could be a SMP only issue, is it a recurring? Does it only affect our fluid containers (could have something to do with our funky fluid container code)?

**Comment by cheesealmighty** [comment]
@IceDragon200 Yup, it is recurring. It happens both when I'm putting stuff in and pulling stuff out. Only happens with growthcraft containers, at least the thermal expansion tanks are working fine as far as I'm seeing.

**Comment by IceDragon200** [comment]
@cheesealmighty I dunno what's going on yet, but we haven't changed that much in the fluids department, except a bug fix, also I just spun up a local server and tested it with inventorytweaks 1.58-147 (I think it's a development build, shrug)

**Comment by cheesealmighty** [comment]
@IceDragon200 I apparently have 1.59 dev156 version of it. I mean, no rush on it, maybe it's something on their end? Then again, it was working in 2.5.2. So, dunno either. I could try with another version. (That would be about 20 hours from now)

Hmm, then again It's not _that_ big of a deal at the moment, just gotta watch out for it I guess. Eh, I just appreciate the fact that thistle doesn't make the _thunk_ sound when you break it anymore <3
