### ISSUE TITLE
Ticking world

### ISSUE THREAD

**Issue by notchriss** [GrowthcraftCE/Growthcraft-1.7#357]
http://pastebin.com/dbeRLYQJ

I walked around the newly created world and suddenly server crashes. Now it's a crash every time I try to connect to the server, but it apparently runs fine when nobody is online.

**Comment by IceDragon200** [comment]
@notchriss Are you running AppleCore 1.3.0? If not, please update your AppleCore

**Comment by notchriss** [comment]
Thanks for your quick response

I updated the AppleCore and now I am unable to start minecraft, getting this error:
http://paste.atlauncher.com/view/b625179c

**Comment by notchriss** [comment]
Thank you, that apparently fixed the issue
