### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#361]
http://pastebin.com/rcs6XxSK

**Comment by IceDragon200** [comment]
@Sunconure11 Upload your fermenting recipes json file for testing

**Comment by Sunconure11** [comment]
http://pastebin.com/Q6YZfjCk

Deleting this did not help.

**Comment by IceDragon200** [comment]
@Sunconure11 I just dumped your config into the dev instance, it loaded just fine for me, I'll upload a new build with the minor change made

62db41f

**Comment by Sunconure11** [comment]
Its still puking up the same error for me.

http://pastebin.com/Qr7XLcME

**Comment by Sunconure11** [comment]
It also fails to regenerate the brewing configs, even when I clear all of the configs out.

Edit: It is some kind of compatibility issue, running a game without as many mods seems to let it boot up fine. I'll tell you if I figure out what is causing it.

Edit 2: This is taking too long, but is there any way to put some kind of failsafe or a way to point to possible compatibility issues?

Edit 3: It is a mix between thaumcraft and extended potions by lumien. http://pastebin.com/yq01dXzQ

http://minecraft.curseforge.com/projects/extended-potions

Source code: https://github.com/lumien231/Extended-Potions

Maybe add a config option to turn off your extension of potion IDs?

Edit 4: Error is pointing to automagy too, which also has a milk fluid.

Edit 5: WTF? http://pastebin.com/JmhyC17W

**Comment by Sunconure11** [comment]
Somehow, its Better Storage.

**Comment by IceDragon200** [comment]
@Sunconure11 Nope, it's trying to serialize ItemStack, should now be fixed

**Comment by Sunconure11** [comment]
Fixed.

**Comment by Sunconure11** [comment]
The thrilling saga continues, but this time with a crash that may or may not be related this time.

http://pastebin.com/5NP437iR

**Comment by IceDragon200** [comment]
@Sunconure11 That's a whole new issue, one that was just introduced with the TagParser
