### ISSUE TITLE
[MILK] Can't drink skim, buttermilk, whey...

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.7#362]
I can repro this using 2.5.2, and using dev build growthcraft-1.7.10-2.6.0-complete--db39760.jar

Tested and failed
- Skim milk bucket and bottle
- buttermilk bucket and bottle
- whey bucket and bottle
- milk bottle

Milk bucket cannot be drank unless you look at the sky or a sufficiently distant block that you can't place the milk fluid. Which would be OK, but the milk bottles don't work either.
I have tried the milk bottles against sky or distant block, no luck. 
I tested buckets and bottles of other drinks against ground and sky and distant blocks, also no luck.

I also tried crouching and drinking in case that was a thing, but it didn't help either.

**Comment by IceDragon200** [comment]
@Syndaryl Milk Bucket placing a fluid is not us, MFR does that, we don't mess with the bucket (except registering as a fluid container IF you enabled milk and Forestry's Milk isn't present).

Milk bottles can't be drank either, (I never did implement those...), you shouldn't be drinking Whey... or butter milk, probably skim milk, but eh, what good would drinking them do for you? (only milk bottles make sense, remove debuffs like milk)

**Comment by Syndaryl** [comment]
They're listed as drinks in https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Milk

**Comment by Syndaryl** [comment]
I have a LOT of skim milk and buttermilk kicking around - I definitely am producing more skim than I'm consuming via starter culture for cheese, and there is no other use for it nor a way to dispose of it without destroying glass bottles or buckets. The buttermilk is also not otherwise useful.
I expected them to be very low value food items, like alcohol; not great, but better than nothing and better food value than milk, which currently has none despite the fact that it probably should if alcohol does (not Growthcraft's fault of course, that's a Minecraft weird).
Whey, buttermilk, and skim milk are all drank by folks (they even sell clabbered buttermilk at my grocery store, and "proper" cultured buttermilk at the healthfood store) so I don't see a big plausibility problem. They'd also be useful in baking but that'd be cross compatability with other mods - I'm using Minetweaker to add oredict entries for things to get that, so neh.

I'm still looking for the instructions for making riccotta out of whey, but once I find those there's at least a second use for it

**Comment by IceDragon200** [comment]
@Syndaryl Why is it that no one informs me of these things D8<

I'll go poke the team and let them come up with some values and other uses for these items, sorry you have a surplus of skim and buttermilk lying round. Hey toss them in fermenting barrels for storage :3

**Comment by Syndaryl** [comment]
I'm informing you now...?  ;)
Thanks for looking into it for me.

**Comment by IceDragon200** [comment]
@Syndaryl Okay, gimme some reasonable values for the hunger and saturation :)

We've got something up now, check the latest development build

**Comment by Syndaryl** [comment]
Trying the latest development build (growthcraft-1.7.10-2.6.0-complete--959d5c0), I'm getting the following crash on program start:
http://pastebin.com/Fg86WWRF

I tried deleting the Milk configuration files and the churn JSON but no change in behavior. The Milk conf was regenerated, the milk folder and churn JSON were not.

**Comment by Syndaryl** [comment]
I rolled back to growthcraft-1.7.10-2.6.0-complete--d451bd4 (the build with your changes) and it's loading OK. So it's something about 959d5c0 (the build immediately after yours) that's barfing.

**Comment by IceDragon200** [comment]
@Syndaryl Related to #363 

A new build is up and should fix this

**Comment by Syndaryl** [comment]
Got the new build, it's working great. Milk drinking is working, the small food and saturation values seem appropriate. I've just turned on the fantasy effects and I'll have a look at them out of curiosity - I don't know that I'll play with that turned on usually since I'm bad at even using normal potions, but I think that's a good option. Since the alcohol options have fantasy effects, it's a good parallel design.
