### ISSUE TITLE
Osmium shovel does not work for paddies

### ISSUE THREAD

**Issue by notchriss** [GrowthcraftCE/Growthcraft-1.7#364]
Osmium Shovel from Mekanism mod cannot create rice paddies. A regular iron shovel works just fine. Not sure about shovels using materials from other mods, haven't tested all yet.

I am not sure who's problem is this, Mekanisms or Growthcraft's, so I'll just report it here for now. It's certainly not a big problem, but just letting you know.

**Comment by IceDragon200** [comment]
It probably doesn't inherit from `ItemSpade`, therefore: not a shovel by Growthcraft's standards

**Comment by notchriss** [comment]
I see, thanks.
