### ISSUE TITLE
Can't collect salt water in Growthcraft 2.6.0

### ISSUE THREAD

**Issue by Agentadam99** [GrowthcraftCE/Growthcraft-1.7#365]
I can't collect salt water at all in 2.6.0 build 9f7c31d

All that happens is I get a bucket of water and I do have the config set to true. 2.5.2 is working as expected.

**Comment by Ar97x** [comment]
You can only get salt water from the Ocean biome. Make sure you're on it
right.

**Comment by Agentadam99** [comment]
I tried both Ocean and Deep Ocean biomes confirmed with F3.

**Comment by Ar97x** [comment]
Then this a thing for @IceDragon200, he'll know.

**Comment by IceDragon200** [comment]
@Ar97x, @Agentadam99 Just tested it, it works, but then the bucket is immediately replaced with a water bucket, reason? I have no idea yet, still looking into it

Has this been tested with Growthcraft alone as well?

**Comment by Agentadam99** [comment]
Works fine in a clean install with just Growthcraft and forge. I will test the other mods I am using as soon as I can.

I'm thinking that it could be Realistic Terrain Generation but as far as I know that mod uses the default boimes and blocks and as I mentioned 2.5.2 is working fine with it and all the other mods that I use.

ps I also found a issue with the milk.conf

under thistle/world gen you used commas instead of semicolons this is causing console spam and lag on chunk gen.
    # Separate the IDs with ';' (without the quote marks); Default : +MOUNTAIN,HILLS
    S:"Biome Types"=+MOUNTAIN,HILLS

**Comment by Agentadam99** [comment]
The issue occurs with CoFHCore-[1.7.10]3.1.2-325
All other mods are fine (I can't test the mods the mods that rely on COFHCore.
I am using forge 10.13.4.1566

**Comment by IceDragon200** [comment]
@Agentadam99 There is a new build up, you will need to update your "Biome Types" in `config/growthcraft/bamboo.conf` AND `config/growthcraft/milk.conf`

Also, since you pointed out CoFHCore, I think I found the problem
https://github.com/CoFH/CoFHCore/blob/ec0cd6113f308c2047f1ff39e916c4d609437934/src/main/java/cofh/core/util/fluid/BucketHandler.java#L49

``` java
if (ServerHelper.isClientWorld(event.world) | event.result != null ...
// | is suppose to be ||
```

**Comment by Agentadam99** [comment]
404 error on Dropbox

**Comment by IceDragon200** [comment]
@Agentadam99 Forgot to upload it, give it a few minutes

EDIT:
Should be up now

**Comment by Agentadam99** [comment]
Config changes work well.
Buckets are still having the same issue. and COFHCore is still the apparent trigger.

**Comment by Sunconure11** [comment]
@Agentadam99 Close now that this has been fixed?

**Comment by IceDragon200** [comment]
@Agentadam99 I believe the COFHCore recently updated, could you try this again and see if it's fixed?
If it is, feel free to close the issue
