### ISSUE TITLE
IleegalState Exception Crash.

### ISSUE THREAD

**Issue by Ristellise** [GrowthcraftCE/Growthcraft-1.7#368]
Got a crash when i updated to 2.5.2
Crash log : http://pastebin.com/UBkTXRUC

**Comment by Ristellise** [comment]
fixed by deleting Config file.

**Comment by IceDragon200** [comment]
@Joshwoo69 Hi, this is known issue https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/FAQ---Troubleshooting#illegalstateexception

EDIT:
NINJA'ED BY THE OP D:

**Comment by Ristellise** [comment]
yup but anyways thanks for the help :smile:
