### ISSUE TITLE
Empty entries in NEI

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#369]
https://www.dropbox.com/s/u51cbaet61l4plr/Screenshot%202016-05-13%2016.19.50.png?dl=0

On every page for brewing recipes, I find empty recipes like this one.

Also, if a recipe uses an oredictionary definition, it should be able to switch between all items in the oredictionary it is using in NEI, like how many mods do it with their recipes.

**Comment by darthvader45** [comment]
Can you reupload the screenshot?  The link doesn't work.
