### ISSUE TITLE
Fermentation Progress Resets when looking in GUI

### ISSUE THREAD

**Issue by Jovascript** [GrowthcraftCE/Growthcraft-1.7#377]
When I put a nether wart or dust into the fermentation barrel, it starts counting up on the progress bar(long time).
Whenever I look back in the GUI of the barrel, the progress is reset.

This is very annoying, because I have to calculate how long it will take and then set a timer, instead of just checking every few minutes.

**Comment by IceDragon200** [comment]
@JoetheBellum What version are you using?
