### ISSUE TITLE
Bamboo leaves are not dropping bamboo shoots

### ISSUE THREAD

**Issue by myrmex1** [GrowthcraftCE/Growthcraft-1.7#382]
I am pretty sure in the old version of this mod, chopping down bamboo at the base would cause the leaves to drop bamboo shoots. In 2.5.2, this is no longer the case.

**Comment by IceDragon200** [comment]
@Qohelethh They don't, they shouldn't, if they did, it was a :beetle:.

You obtain a bamboo shoot by waiting until a fully grown stalk spawns one and then digging it up with a hoe (like real bamboo :smile:)

**Player Tip**
If you encounter a bamboo grove, bunch or spot, chop down as many as you want until 1 is left and leave it there, it will regrow eventually so you can repeat the process

**Comment by myrmex1** [comment]
Thanks! I remember in the old Gwafu version the leaves definitely dropped bamboo shoots, but I guess that wasn't supposed to happen.
