### ISSUE TITLE
ModPack - Total Penumbra

### ISSUE THREAD

**Issue by MitchellShapiro** [GrowthcraftCE/Growthcraft-1.7#383]
The pack is still in early development and the mod list may change. The pack will be on Technic soon and I would love to include this mod.

[Here is the mod list on pastebin](http://pastebin.com/X04amVh2)

Thanks for your time!

**Comment by IceDragon200** [comment]
@mandm635 Thank you for your interest in Growthcraft (please use Growthcraft CE, when refering to this version, as Growthcraft by itself is used to refer to the original version :+1:)

[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)

**Comment by MitchellShapiro** [comment]
Thanks, I'll update that now.
