### ISSUE TITLE
Modpack - Magic Theory 2

### ISSUE THREAD

**Issue by Shadows-of-Fire** [GrowthcraftCE/Growthcraft-1.7#384]
As per your licenses, I am opening this issue to notify you of use of GrowthCraft in my modpack.  It is currently hosted on the FTB Launcher, but due to recent complications I am moving to ATLauncher.  

[Current Modlist](http://modlister.com/user/Shadows_of_Fire)

**Comment by IceDragon200** [comment]
@Shadows-of-Fire 2.6.0 is out by the way, also please refer to this Growthcraft as "Growthcraft CE", also you can set the Authors as "Growthcraft CE Team"

Without further ado:
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
