### ISSUE TITLE
Running out of Heap space - NEI item Use lookup [2.6.1]

### ISSUE THREAD

**Issue by draknyte1** [GrowthcraftCE/Growthcraft-1.7#387]
Hi All,
Tried updating Growthcraft to 2.6.1 and I now get this upon looking up item 'uses' in NEI
http://pastebin.com/njp9PCzb

Logging irc history for the sake of myself and others not on IRC at the time.
[SomeGuyInATree] Don't know what's breaking, but it chews through 6gb of memory in [ 1min.
[Gil] SomeGuyInATree: that might be my fault
[Gil] let me have a look
[Gil] yup, it is
[Gil] haven't seen that happen
[SomeGuyInATree] 203 mods in my pack :D It breaks lots of things. 
[Gil] SomeGuyInATree: did you log it on github?
[SomeGuyInATree] No, But I can report it there, no worries.
[Gil] what's happening is that there's probably another mod with with similar recipes and it causes an explosive search for recipes and such
[Gil] I know how to fix it in theory
[Gil] hmm, 6GB of memory sounds like it's an infinite loop of sorts
[Gil] and no one else has reported it, so it's probably rare
[Gil] I'll try to fix it ASAP
[SomeGuyInATree] I haven't looked at the code yet, I'm too short on sleep and due for a game of Golf sometime today. Otherwise I'd offer more insight than a crashlog.
[Gil] the recipe handler in question is super recursive
[Gil] running out of heap space in particular cases is something I had worries about
[Gil] but I didn't want to prematurely optimize unless someone reported this exact error

[Gil] SomeGuyInATree: do you have a mod that adds lots and lots of liquids?
[SomeGuyInATree] Gregtech, minechem.
[SomeGuyInATree] At a minimum
[Gil] pneumaticraft?
[SomeGuyInATree] Yep!
[Gil] yeah, that'll do it
[Gil] seems like it's mostly a liquids problem, I'll try to find a better way to bail out early

**Comment by SimonMeskens** [comment]
I'll look into this, I kinda know where the problem area lies
