### ISSUE TITLE
thistle spread settings too aggressive

### ISSUE THREAD

**Issue by pmytilin1984** [GrowthcraftCE/Growthcraft-1.7#388]
Decided to settle on scrubland bop biome, thistle spread everywhere.

it doesn't not seem to obey max spawn per chunk rule

relevant screenshot
http://i.imgur.com/g2g55t5.jpg

**Comment by IceDragon200** [comment]
@pmytilin1984 The spawn per biome setting only affects the initial worldgen, after that it could care less about the setting and spreads like wildfire in a grass land on a hot summer day.

I suggest reducing the spawn rate, and see if it's any better, but I've added a new config option. 0910dd64a1306bb3c53351904193bf1fea0ff8a5

I've added a new preview build, give it a twirl and tweak the new config option to see if it fixes your issue
https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/386

**Comment by pmytilin1984** [comment]
The problem is that this isn't really sane default behaviour

in my case, this biome is in the spawn chunks and even if I move out, thistle will eventually cover over every available dirt block given enough time.

There should be a way to mitigate its growth at least, and stop it from spreading to nearby biomes I think.

**Comment by cadaverous-eris** [comment]
I'd suggest making it only spread if there aren't many other thistle plants nearby. I believe bamboo does something like this.

**Comment by IceDragon200** [comment]
@frederick-the-nameless They use similar logic, the only difference is thistle spreads over a 4x2x4 range instead of 2x2x2.

As a test I've reduced the spread range so it's exactly like bamboo (1 block in each direction instead of 2)
