### ISSUE TITLE
Crash on right clicking the Brew Kettle with v2.6.1

### ISSUE THREAD

**Issue by xJon** [GrowthcraftCE/Growthcraft-1.7#390]
http://pastebin.com/iLiYxdT4

**Comment by lukjan** [comment]
I have same crash too: https://gist.github.com/lukjan/c5692bb778d365e6cc4ec7b45b2393d7

**Comment by IceDragon200** [comment]
Fixed Earlier: https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/385, we'll release the fix in 2.6.2, after we deal with https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/387

You can pick up the preview builds for 2.6.2 here https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/386

**Comment by lukjan** [comment]
Already done :) Thanks, it's awesome!

**Comment by xJon** [comment]
Thanks! @IceDragon200
