### ISSUE TITLE
Use of Growthcraft in a modpack

### ISSUE THREAD

**Issue by nanonator102** [GrowthcraftCE/Growthcraft-1.7#391]
Hello, just to comply with your policy on modpacks, have a link to the modlist for the pack im working on with a friend called Echo! 
http://modlister.com/user/Dr_Teath

-Nano

**Comment by IceDragon200** [comment]
@nanonator102 [![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
