### ISSUE TITLE
Excessive logging during Growthcraft Milk World Gen

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#392]
This issue was report via a [Minecraft Forum Post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10?comment=426). 

We need to check gcmilk, from the report, it appears that world gen is set for logging at INFO instead debug.

**Comment by IceDragon200** [comment]
@Alatyami _sweats profusely_

**Comment by Alatyami** [comment]
Geez that was difficult to fix :) Thank you!
