### ISSUE TITLE
Minecraft is crashing

### ISSUE THREAD

**Issue by Meriones** [GrowthcraftCE/Growthcraft-1.7#398]
Hi

Maybe you can help me. I play Life in the Woods Renaissance. The Modpack i use is from this guy. http://www.technicpack.net/modpack/life-in-the-woods-extended.814581. It works fine. I realy like to use Growcraft too. So i added it to the mods. But it always crashed. If i read the crash report properly then it has something to do with the AppleCore and BlockHops. In the game  it self  it crash then i find a village that grow Hops or then i will grow it by my self.

CrashReport

http://pastebin.com/VKwGnQ8X

Thanks for your time. Have a nice Day.

Meriones

**Comment by IceDragon200** [comment]
@Meriones Growthcraft only works with AppleCore 1.3 and up, we've moved away from the older version, so try updating the copy of AppleCore (that may break any other mod relying on it however, so be sure to update them as well)

**Comment by Meriones** [comment]
Thanks for the fast answer. It works now with the AppleCore 1.3. Only the right specification of the items ist missing. I will check the other Mods for a update. Thanks again and have a nice evening.

```
Corey Powell <notifications@github.com> schrieb am 17:32 Donnerstag, 14.Juli 2016:
```

 @Meriones Growthcraft only works with AppleCore 1.3 and up, we've moved away from the older version, so try updating the copy of AppleCore (that may break any other mod relying on it however, so be sure to update them as well)—
