### ISSUE TITLE
[Suggestion] Adding Vodka To Growthcraft

### ISSUE THREAD

**Issue by Tearahk** [GrowthcraftCE/Growthcraft-1.7#399]
I posted this on the Minecraft Forums page, but I was wondering, would it be possible to add vodka into Growthcraft? I mean, potatoes need love too, right? Plus, they're already in the game. Just a thought. ^_^

**Comment by Techokami** [comment]
That... that should be real easy to add. Just use a mechanical press with potatoes inside, then ferment the results?

**Comment by Ar97x** [comment]
We have plans for a distillery, but we don't know when it'll come out of
the paper. Vodka will surely come together.

**Comment by Tearahk** [comment]
Okay, that sounds good. ^_^

**Comment by darthvader45** [comment]
This is great, maybe have two distillery blocks?  One that's cheap but distills slowly( should look like the old-fashioned still shown in M.A.S.H.), and a more expensive modern one that's a bit faster.

**Comment by ghost** [comment]
I don't know about Vodka specifically but how about moonshine, spirits , various types of spirits high alcohol content which is distilled from fruits . Unless it exists already :D

**Comment by darthvader45** [comment]
Yeah, working with basic distillables should be good.  Vodka is fermented potato mash run through a distiller then filtered with charcoal.

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.

We are looking at implementing this request in newer versions.
