### ISSUE TITLE
Find a new home for the GrowthCraft wiki

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#4]

**Comment by Sunconure11** [comment]
Wikia might work. We could also set up the wiki on here.

**Comment by Alatyami** [comment]
Let's start it here ... I'd like to find a place that is minecraft friendly so that we can build out the graphical recipes.

**Comment by SynfulChaot** [comment]
I'd recommend either here on GitHub or on http://ftb.gamepedia.com/FTB_Wiki.  Wikia is ... something best avoided if you can due to heavy ads and no control over most things.

**Comment by Sunconure11** [comment]
I am working on the rice page.

**Comment by Ar97x** [comment]
Have you found a good place to do it? Share it so I can start working on it too.

**Comment by Sunconure11** [comment]
https://github.com/alatyami/Growthcraft-1.7/wiki I'm using this. It also has pages for various concepts.

**Comment by Alatyami** [comment]
I'm thinking we are going to go with http://ftb.gamepedia.com/GrowthCraft as they already have the widgets for displaying the different UI's.

**Comment by Ar97x** [comment]
I prefer FTB Wiki too, I think it is more prepared for mod researching and
is aesthetically better. And it's more known too.

**Comment by Alatyami** [comment]
We'll continue to have the conceptionals here but all of the "how to use" the plugins will be stored over there.
