### ISSUE TITLE
1.7.10 automagy milk incompatibility

### ISSUE THREAD

**Issue by bloche1871** [GrowthcraftCE/Growthcraft-1.7#404]
any chance compatibility could be added for the milk fluid from automagy?

**Comment by bloche1871** [comment]
never mind I found out this is configurable

**Comment by bloche1871** [comment]
Actually, this does not seem to be implemented?

**Comment by IceDragon200** [comment]
@JoachimDespland What is the name of the fluid? (not the translated name the actual fluid name)

**Comment by bloche1871** [comment]
@IceDragon200  The unlocalized name of the fluid is "fluidmilk"

**Comment by IceDragon200** [comment]
@JoachimDespland Okay, creating a test build now

EDIT: https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/402
Latest build has the change, give it a test and let me know if it works

**Comment by bloche1871** [comment]
@IceDragon200  It seems to be working perfectly, thanks!
