### ISSUE TITLE
New Modpack coming soon

### ISSUE THREAD

**Issue by PreastoricDragon** [GrowthcraftCE/Growthcraft-1.7#407]
PDYV Modpack:

Witchery by Emoniph
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445248-witchery-0-24-1

Ztones by riciJak
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2221070-ztones-v-2-2-1-decorative-blocks-16x

WAWLA by Darkhax
https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at?gameCategorySlug=mc-mods&projectID=224712

WAILA and Jabba by ProfMobius
https://minecraft.curseforge.com/projects/jabba
https://minecraft.curseforge.com/projects/waila

WAILA Harvestability, TiC Tooltips by squeek502
https://minecraft.curseforge.com/projects/waila-harvestability?gameCategorySlug=mc-mods&projectID=79287
https://minecraft.curseforge.com/projects/tic-tooltips?gameCategorySlug=mc-mods&projectID=76845

DecoCraft by RazzleberryFox
https://minecraft.curseforge.com/projects/decocraft2?gameCategorySlug=mc-mods&projectID=79616

The Twilight Forest by Benimatic
https://minecraft.curseforge.com/projects/the-twilight-forest?gameCategorySlug=mc-mods&projectID=227639

Thermal Foundation, CoFH Core, Thermal Expansion by TeamCoFH
https://minecraft.curseforge.com/projects/thermal-foundation?gameCategorySlug=mc-mods&projectID=222880
https://mods.curse.com/mc-mods/minecraft/cofhcore
https://minecraft.curseforge.com/projects/thermalexpansion?gameCategorySlug=mc-mods&projectID=69163

Thaumic Tinkerer by nekosune
https://minecraft.curseforge.com/projects/thaumic-tinkerer?gameCategorySlug=mc-mods&projectID=75598

Thaumcraft, Baubles by Azanor
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-5-2-4-updated-2016-3-17

Tinkers Construct, Natura, Mantle by mDiyo
https://minecraft.curseforge.com/projects/tinkers-construct?gameCategorySlug=mc-mods&projectID=74072
https://minecraft.curseforge.com/projects/mantle
https://minecraft.curseforge.com/projects/natura?gameCategorySlug=mc-mods&projectID=74120

Railcraft by CovertJaguar
https://minecraft.curseforge.com/projects/railcraft?gameCategorySlug=mc-mods&projectID=51195

Minecraft Comes Alive, RadixCore by WildBamaBoy
https://minecraft.curseforge.com/projects/radixcore?gameCategorySlug=mc-mods&projectID=77286
https://minecraft.curseforge.com/projects/mca

PortalGun, iChunUtil, Morph, Back tools, Hats, Hats Stand by iChun
http://ichun.me/

Pam’s Harvestcraft by MatrexsVigil
https://minecraft.curseforge.com/projects/pams-harvestcraft?gameCategorySlug=mc-mods&projectID=221857

OpenModsLib, OpenBlocks by OpenMods
https://www.openmods.info/

NotEnoughKeys by dmodoomsirius
https://minecraft.curseforge.com/projects/notenoughkeys

NotEnoughItems, CodeChickenCore by chicken_bones
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods

NetherOres, MineFactory Reloaded, by skyboy026
http://www.planetminecraft.com/mod/nether-ores-forge-164/

NEIaddons by bdew
https://minecraft.curseforge.com/projects/nei-addons?gameCategorySlug=mc-mods&projectID=63352

MrCrayfish Furniture Mod by Mr_Crayfish
https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod?gameCategorySlug=mc-mods&projectID=55438

Voxel Map by Mamiya0taru
https://minecraft.curseforge.com/projects/voxelmap?gameCategorySlug=mc-mods&projectID=225179

Metallurgy, Metallurgy Core, Metallurgy Classic Machines, Extra TiC, Metallurgy Chisel by JeanGlassmaker
https://minecraft.curseforge.com/projects/metallurgy?gameCategorySlug=mc-mods&projectID=59641

Mekanism by aidancbrady
https://github.com/aidancbrady/Mekanism

Malisis Core, Malisis Doors, Malisis Advert by Ordinastie
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-9-4-5-0-2-1-9-4-0-2-03-08-2016

JAFFA by Murdy007
https://minecraft.curseforge.com/projects/jaffa-foods-a-harvestcraft-addon?gameCategorySlug=mc-mods&projectID=232717

Inventory Tweaks by Kobata
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288184-inventory-tweaks-1-61-jul-11

Immersive Engineering by BluSunrize
https://minecraft.curseforge.com/projects/immersive-engineering?gameCategorySlug=mc-mods&projectID=231951

Immersive Integration by UnwrittenFun
https://minecraft.curseforge.com/projects/immersive-integration?gameCategorySlug=mc-mods&projectID=232159

Iguana Tinker Tweaks by boni
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks

Garden Stuff by jaquadro
https://minecraft.curseforge.com/projects/garden-stuff?gameCategorySlug=mc-mods&projectID=225903

Fossil Archeology Revival by FossilsRevival
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2398119-fossils-and-archeology-revival-build-7-3-2-the

Forbidden Magic by SpitefulFox
https://minecraft.curseforge.com/projects/forbidden-magic?gameCategorySlug=mc-mods&projectID=224237

Extra Utilities by RWTema
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1443963-extra-utilities-v1-1-0k

Et Futurum by ganymedes01
https://minecraft.curseforge.com/projects/et-futurum?gameCategorySlug=mc-mods&projectID=230114

EnderIO by CrazyPants
http://enderio.com/

Dragon’s Radio Mod by DragonbornSR
https://minecraft.curseforge.com/projects/dragons-radio-mod

CustomNPC’s by Noppes
http://www.kodevelopment.nl/minecraft/

ChocoCraft by clienthax
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2269183-1-8-clienthaxs-chococraft-2-happiness-distilled

ChiselTones by TehNut
https://minecraft.curseforge.com/projects/chiseltones?gameCategorySlug=mc-mods&projectID=228004

Chisel by tterrag11098
https://minecraft.curseforge.com/projects/chisel?gameCategorySlug=mc-mods&projectID=235279

Carpenter’s Blocks by Syntaxial
http://www.carpentersblocks.com/

Buildcraft by CovertJaguar
http://www.mod-buildcraft.com/

Botania by Vazkii
https://minecraft.curseforge.com/projects/botania?gameCategorySlug=mc-mods&projectID=225643

Biomes O’Plenty by Glitchfiend
https://minecraft.curseforge.com/projects/biomes-o-plenty?gameCategorySlug=mc-mods&projectID=220318

Big Reactors by ErogenousBeef
https://minecraft.curseforge.com/projects/big-reactors?gameCategorySlug=mc-mods&projectID=241994

Bibliocraft, Bibliocraft Natura, Bibliocraft Biomes O’Plenty by Nuchaz
http://www.bibliocraftmod.com/

Armourers Workshop by RiskyKen
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2309193-wip-alpha-armourers-workshop-weapon-armour-skins

Applied Energistics 2 by AlgorithmX2
http://ae-mod.info/

Adventure Backpack by Darkona
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2252109-wip-adventure-backpack-mod-beta-0-8c-updated

Grimoire of Gaia 3 by Silentine
https://mods.curse.com/mc-mods/minecraft/228948-grimoire-of-gaia

MicdoodleCore, Galacticraft Core, Galacticraft Planets by micdoodle
https://forum.micdoodle8.com/index.php

Blood Magic by WayofTime
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290532-1-10-2-1-9-4-blood-magic-v2-0-3-53-updated-jun-21

Damage Indicators by rich1051414
http://mod-minecraft.net/damage-indicators-mod/

**Comment by Alatyami** [comment]
Looks like a fun modpack. You're approved. Let us know if you have any mod-compatibility issues.
