### ISSUE TITLE
[BUG] Item duplication bug 1.7.10

### ISSUE THREAD

**Issue by frytek96** [GrowthcraftCE/Growthcraft-1.7#408]
If you put something (in eg. nether wart) into ferment barrel and pick it up using crowbar, item that was inside duplicate itself 

Minecraft ver: 1.7.10
Growthcraft ver: growthcraft-1.7.10-2.6.3-complete

**Comment by IceDragon200** [comment]
@frytek96 Could you try the latest test build in #406?

EDIT: I was a bit hasty on the label, let me know if the issue has been resolved

**Comment by frytek96** [comment]
@IceDragon200 I just downloaded the latest version ("2016-08-17 @ 19:32:33 EST 4b4bdb2 2.6.3") and the bug still occurs. I was hoping that it could be caused by my heavily-loaded modpack but today i tested this on vanilla fresh mc and the bug still occurs.

**Comment by IceDragon200** [comment]
@frytek96 Okay, I think I got it this time, try the newest build and let me know

**Comment by frytek96** [comment]
@IceDragon200 Sorry for not responding for such a long time, I was out of town. I checked the latest build and everything appears to be in order, no more duplicating

**Comment by IceDragon200** [comment]
@frytek96 yay!
