### ISSUE TITLE
Kumis can't Be made!

### ISSUE THREAD

**Issue by Indevious** [GrowthcraftCE/Growthcraft-1.7#410]
I'm fairly certain I'm just doing something wrong, but no matter what craftinf recipe I've tried fermenting item in a barrel in a kettle or even a vat, NOTHING works. NOTHING! Any else know how to brew it?

**Comment by IceDragon200** [comment]
@Indevious Did you check your `$MINECRAFT/config/growthcraft/fermenting.json` for the recipes?

the fluids are called grc.kumis (and are numbered from 0 to about 6), also it uses Growthcraft's builtin Milk, that could be your issue.

You can use the current default for 2.7 now: https://gist.github.com/IceDragon200/b220232f078aa95a2748baa312fe1807
This will use any of the recognized milk fluids we have.
Or anything you tag using the fluid_dictionary as "milk"

You can try the latest test build here https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/406
Please be careful if running this in an existing world, while nothing has changed for users the code has gone some internal changes.

**Comment by Indevious** [comment]
I took a look and it seems to be the exact same stuff no difference I could spot. It also says cannot ferment when I place it in if that helps at all. I also checked and while I can use NEI to get growthcraft milk, I cant find a bucket of it, and using a bucket on it gives me a bucket of water.

**Comment by Alatyami** [comment]
Using the 2.6.2 released build ... I placed a bucket of Milk into the fermentation barrel and added some nether wart and it fermented like a charm. After it fermented I was then able to add the redstone/glowstone.

**Comment by Indevious** [comment]
I downloaded it again and it worked? I...Don't know, regardless Thank you for the help guys!
