### ISSUE TITLE
Modpack request

### ISSUE THREAD

**Issue by Xombie11** [GrowthcraftCE/Growthcraft-1.7#412]
can I include this mod in my pack?

**Comment by IceDragon200** [comment]
@Xombie11 Could we get a bit more information on this modpack?
Name, Modlist, link to mod (if available) etc?

**Comment by Xombie11** [comment]
I'm currently away from my computer at the moment just about to get into bed i can give you most of the info but not the mod list (not for a few hours anyway) but so that i know when you ask for the mod list do you mean the list that appears in the main menu of minecraft or (i'm using multiMC to assemble the pack) the mod list that appears when you select add mods to instance? I only ask because the minecraft main menu option is alot bigger/longer due to to mods like growthcraft for instance where you install the mod and in the MC main menu it as you already know doesnt just appear as growthcraft it appears as multiple entries e.g. growthcraft bees, growthcraft rice etc. Were as in the multiMC list it just appears as one entry. 

I dont have a link to the pack yet as i plan to submit it to FTB which again, as I'm sure you know the pack needs to have permissions for all the mods which I'm in the process of gathering (i need about 5 at most more including yours) before i can submit the pack for FTB Approval i can give a link to you either on here or the minecraft forums (were ever you prefer really) once/if i get FTB approval.

As for the name i hope it doesnt affect your decision but i dont actually have a name yet i'm terrible at coming up with names i do have 3 ideas for names which i can give you if you'd like? Sorry if this has gone a bit rambly i have a habit of rambling sometimes.

**Comment by Xombie11** [comment]
Hi sorry for taking a while to reply I installed a new mod to the pack and was testing it to make sure it was working and in the process discovered a problem with the pack that took me a few days to fix and in the process of fixing that problem I discovered a second problem with the pack and then real life kick up a fuss for a bit but the problems are fixed now just need your permission to include this mod in the pack then I can write a description for the pack, make a display picture for the pack and then submit it to the FTB admins for approval. I've named the modpack H.A.W.R.D (Hardcore Adventuring With Relative Difficulty)  here's the list of mods in the pack: 

1.additional buildcraft objects 
2.advent of ascension  
3.agricraft by infinity raider  
4.animationAPI  
5.applecore  
6.applied energistics 2 
7.aqua tweaks  
8.ars magica2 by mithion  
9.automagy by Tuhjin  
10.backpacks by eydamos 
11.Buildcraft (Builders, energy, factory, silicon, transport,lib)  
12.biblocraft   by Nunchaz  
13.bibliowoods forestry by Nunchaz  
14.bibliowoods natura   by Nunchaz  
15.binniecore  
16.binnie patcher  
17.botania  
18.carpenters blocks  
19.chisel  
20.chocolate quest by chocolatin
21.coroutil library
22.cyanos lootablebodies by Dr. Cyano
24.doomlike dungeons
25.enchanting plus
26.enchiridion 2
27.ender storage by Chickenbones
28.enviromine
29.extra cells 2  
30.extra utilites by RWTema 
31.extraTIC
32.farseek by delvr
33.fast leaf decay  
34.fastcraft
35.forestry
36.forge relocation
37.fossils and archeology revival
38.FTBLib
39.FTBUtilites
40.furnace 3d by spAnser
41.GenDustry
42.Gravestone
43.Growthcraft  
44.hardcore ender expansion
45.hardcore wither by thor12022
46.herdcraft
47.iChunUtil by ichun
48.Iguana Tinker Tweaks 
49.Immersive Engineering
50.Immersive Intergration
51.Invertory Tweaks
52.Iron Chest  
53.JABBA  
54.Journey Map  
55.Kore Sample  
56.LLibary  
57.Lycanites Mobs by lycanite
58.Magic Bees  
59.mantle  
60.Mariculture  
61.Mekanism (generators, tools)
62.Millenaire by Kinniken  
63.Mine & Blade battlegear 2 - bullseye  
64.Minefactory reloaded  
65.Minetweaker 3  
66.Morph by ichun  
67.Morpheus 
68.Natura  
69.NEI addons  
70.NEI Integration  
71.Nether ores  
72.NEI  by chickenbones 
73.Open Modular turrets  
74.Open Blocks  
75.Open Mods  
76.Pam's Harvestcraft  
77.Project Red (core, transmission) 
78.Railcraft  
79.Realistic Terrain Generation by Team RTG 
80.Roguelike Dungeons  
81.Simply Jetpacks  
82.Solar Expansion  
83.Somnia by kingrunes and MALfunction84  
84.Special Mobs by father toast
85.Steve's Workshop  
86.Storage Drawers (Forestry pack, Natura pack)
87.Streams by delvr  
88.Tardis mod  
89.TC Inventory Scanning  
90.TC node tracker  
91.Thaumcraft by Azanor  
92.Thaumcraft mob aspects  
93.Thaumcraft NEI Plugin by DJGiannuzz  
94.Thaumic Energistics  
95.Thaumic Tinkerer 
96.The spice of Life  
97.The twilght forest by Benimatic 
98.Thermal Dynamics 
99.Thermal expansion  
100.Thermal recycling  
101.TiC Tooltips  
102.Tinkers construct  
103.Tinkers Mechworks  
104.Translocator by chickenbones  
105.Traveller's Gear  
106.TreeCapitator by DaftPVF and bspkers  
107.Tropicraft  
108.Waila  
109.Waila Harvestability  
110.what are we looking at  
111.Witchery by Emoniph 
112.Zombie Awareness  
113.bspkerscore by DaftPVF and bspkers  
114.Baubles 
115.Codechicken lib by chickenbones 
116.Forge Multi Part by chickenbones  
117.MrTJPCore  
118.Weather 2 
119.Thermal Foundation  
120.Minecraft comes alive 
121.Draconic evolution  
122.Turkey Utility  
123.Infernal Mobs  
124.Hardcore Darkness 
125.Starting Inventory by DaftPVF and bspkers

still don't have a link to the pack yet but I can post the link to it once/if the FTB admins approve the pack either here or in the Minecraft forum thread for this mod or both places if you'd prefer just let me know. I only need the approval/permission for this mod now

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
