### ISSUE TITLE
BeeBox Item Duplication

### ISSUE THREAD

**Issue by Ghostlyr** [GrowthcraftCE/Growthcraft-1.7#413]
In beebox slot can be placed any item via shif-click. After some time it gives a honey combs and duplicates itself.
Tested on last dev build.
Forge 1614.

![45645645556](https://cloud.githubusercontent.com/assets/8511068/18300572/04ccf1d0-74ec-11e6-89c5-15a79ff2a13b.png)

**Comment by IceDragon200** [comment]
@Ghostlyr And here I was trying to figure out how to get more gold ingots <3

I'll look and fix it shortly

**Comment by IceDragon200** [comment]
@Ghostlyr New test build is up :)

**Comment by Ghostlyr** [comment]
Dupe seem to be fixed, but shift-click still puts any item in slots (now also in honeycomb slots) and honeycombs as before still generated from any item.
Also now appeared visual problems - getting out combs from container with shift-click does not update player inventory (do not see the items received until re-open inventory) and reserves within the container null-stack items (disappear if you try to use).

![4654564565456](https://cloud.githubusercontent.com/assets/8511068/18336273/97b6670e-75a7-11e6-94e1-7306043d7bcf.png)
1. Took with shift-click honaycombs - it seems no result
2. Reopen inventory and see taken items, but they are still visible in the beebox container
3. Tried to get them to put somewhere and they disappeared

In addition, the logs for some reason seen debug messages, but I have been disabled in all configurations.

```
 [Server thread/INFO]: Growthcraft|Bees Trying to Spawn a Bee device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Trying to Spawn a Bee device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Spawning a Bee device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Calculating Honey Comb bias device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Combs are biased device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Trying to flip bias device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Trying to spawn honey comb device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft|Bees Spawning honey comb device=growthcraft.bees.common.tileentity.device.DeviceBeeBox@3504354f x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft writeToStream tile=growthcraft.bees.common.tileentity.TileEntityBeeBox@86be0bd x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft writeToNBT tile=growthcraft.bees.common.tileentity.TileEntityBeeBox@86be0bd x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft writeToNBT tile=growthcraft.bees.common.tileentity.TileEntityBeeBox@86be0bd x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft writeToNBT tile=growthcraft.bees.common.tileentity.TileEntityBeeBox@86be0bd x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft writeToNBT tile=growthcraft.bees.common.tileentity.TileEntityBeeBox@86be0bd x=1419 y=64 z=1219
 [Server thread/INFO]: Growthcraft writeToNBT tile=growthcraft.bees.common.tileentity.TileEntityBeeBox@86be0bd x=1419 y=64 z=1219
```

**Comment by IceDragon200** [comment]
@Ghostlyr Ah, don't worry about the debug messages, those are only present in my dev environment, because I've built it from my copy, the bees logs I'll need to remove those

EDIT:
Could you try the latest build now
