### ISSUE TITLE
Adding Rotten Flesh to Fish Traps Increases Fish Production

### ISSUE THREAD

**Issue by abculatter2** [GrowthcraftCE/Growthcraft-1.7#416]
Pretty much what it says on the tin.

**Comment by IceDragon200** [comment]
@abculatter2 
Seems doable, I'll tackle that tomorrow or some time in the week...
If you don't hear back from me within a week, please ping me

**Comment by IceDragon200** [comment]
@abculatter2 The feature has been added to the latest test build, could you give it a spin and help with balance?
