### ISSUE TITLE
No Mead Bucket Recipe

### ISSUE THREAD

**Issue by nebecanezzar** [GrowthcraftCE/Growthcraft-1.7#417]
Hi,

I'm playing resonant rise 3.3 with Growthcraft 1.7-2.6.3 installed. It seems though, that the recipe to create the mead must bucket (water bucket + bucket + honey) is not there. Has the recipe changed or is there another way to create this?

Thanks!

**Comment by IceDragon200** [comment]
@nebecanezzar Duplicate of #415, already fixed in development :)
