### ISSUE TITLE
Features Request:  Making vinegar from wine, TiCon compat (cheese vat), and white wine?

### ISSUE THREAD

**Issue by darthvader45** [GrowthcraftCE/Growthcraft-1.7#418]
1.  I would like for vinegar to be able to be made from wine.  It all starts with a Mother: a small culture of bacteria and some starting vinegar, made by putting wine into a wine jar (made by putting a culture jar in the crafting table).  The mixture is left to ferment in a special fermentation jar (place a wine jar in a crafting table).  Once that's ready, add the wine and leave to ferment for about 24000 ticks or 1 in-game day.  Then you have vinegar.
2. I would also like compatibility with Tinkers Construct, allowing their broadswords to be used to cut the curds in the cheese vat.  Imagine being down to your last wooden, iron or diamond sword, which you need to make cheese, and you use the last bit of durability fighting a pesky zombie or spider.  Yeesh.
3. Maybe add green grapes for making white wine?  Adds a little variety to the mod.  Maybe even some special grapes for special wines like chardonnay, cabernet sauvignon, etc.

**Comment by IceDragon200** [comment]
@darthvader45 
1 - What use would vinegar be in the mod itself? also I'm not in favour of creating 2 more blocks for a singular function...

2 - I'm never down to my last wooden sword, because wood is just that easy to grab, but tinkers swords probably work, while some don't

3 - The grapes are already present in the mod, the mod idea was pitched in some time ago, we just never got around to implementing it

**Comment by darthvader45** [comment]
Vinegar could be used as an alternative to the Harvestcraft variety, and could also be reduced to a syrup for coating ice cream.  Thanks for adding the green grapes, hope they're implemented someday.  Also, keep up the work on the distillery (though it'd be better to have two kinds, one cheap but slow, and one expensive but faster).  If there will be a cheap version, it could look like the homemade still seen in M.A.S.H., which is iconic and widely used during the Prohibition era.

**Comment by ghost** [comment]
I don't know about vinegar :D seems a bit silly unless you make it more useful for something else. What do people use vinegar for? Maybe you can make fruitfly traps hahaha or attract insects. :DDD

**Comment by darthvader45** [comment]
People use vinegar for ice cream, salad dressing, etc.  Google it, and you'll find it is very versatile.

**Comment by Ar97x** [comment]
Vinegar to make ice cream? That's new to me, if it's true we can adapt it
to the recipes of the ice cream we have.

**Comment by darthvader45** [comment]
It can be reduced to a syrup.

https://www.google.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=vinegar%20syrup%20ice%20cream&oq=vinegar%20syrup%20ice%20cream&rlz=1C1CHBF_enUS708US708&aqs=chrome..69i57.5921j0j7

Balsamic vinegar syrup.

**Comment by ghost** [comment]
I don't know about vinegar ice cream. You can simply make wine or cider go sour and give you nausea or poison effect I don't know for shits and giggles.

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.
