### ISSUE TITLE
Set up a curse page

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#42]
In the future, we should set up a page on curseforge for this mod.

**Comment by Alatyami** [comment]
That's the plan, I wanted to get Travis-CI production ready. Next is to
split the jars out again and then push it all to curse.

Alatyami

**Comment by Alatyami** [comment]
We have a page and the complete jar has been posted.

**Comment by Ar97x** [comment]
Have you posted on the Forum?

**Comment by Alatyami** [comment]
I'll add it to the main post in the morning.
