### ISSUE TITLE
Thistles spreading in wrong Biome

### ISSUE THREAD

**Issue by puchm** [GrowthcraftCE/Growthcraft-1.7#420]
Hey. I have a pretty annoying bug going on. My base is in a Plains biome and I'm chunkloading an area of about 1000x1000 blocks (This needs to be done for some other stuff from the Modpack I'm playing). As you can read [here](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Growthcraft-Milk) the Thistle "spawns naturally on grass blocks in the extreme hills (and variants) biome". I have no Extreme Hills biome in a radius of like 2000 blocks! But now I jusrt removed about 700 Thistles yesterday and they have spread again. Seriously, who even got the idea of them spreading. This is extremely annoying and it would definetely by a reason for me to stop playing this mod.

Sincerely, puchm

**Comment by IceDragon200** [comment]
@puchm 
1 - What version of Growthcraft are you running?
2 - If it's anything less than 2.6.3, please consider upgrading to 2.6.3 as it fixes the thistle world gen
3 - Thistle WILL spread, it's a weed, and weeds are evil
4 - Maybe we should add a "Round Up" item that kills Thistles, dunno
5 - Sorry about the inconvenience, at least you won't have a Thistle Rennet shortage 3:

Also related #388
