### ISSUE TITLE
better  inter-mod compatibility for honey => use ore:bucketHoney instead of honeyJar

### ISSUE THREAD

**Issue by ghost** [GrowthcraftCE/Growthcraft-1.7#421]
Must Mead Bucket = Water Bucket + ore:bucketHoney +  empty bucket.

GC has Growthcraft|Bees:grc.honeyJar added to ore dict as ore:bucketHoney . So this will be same as before except now anything added to ore:bucketHoney  from other mods will also work to make mead. 

Just fixed this via MineTweaker 3 and added biome of plenty and Forestry honey(s) to ore:bucketHoney

Here is the actual script for MT3

```
recipes.remove( <Growthcraft|Bees:grc.honeyMeadBucket.0> );
recipes.addShapeless(<Growthcraft|Bees:grc.honeyMeadBucket.0>, [<minecraft:water_bucket>, <ore:bucketHoney>, <minecraft:bucket>]);
```

Here is the result
![screen shot 2016-09-25 at 6 32 30 pm](https://cloud.githubusercontent.com/assets/6987027/18818703/7c4a6952-834e-11e6-84ae-65303e1a0fe7.png)

As you can see I can now use 3 different types of honey items from 2 other mods in addition to GC

Also one of the Growthcraft|Bees:grc.honeyJar  recipes is using item 0 NULL in a shaped recipe on my computer. Probably a missing mod? Might be Erebus honey not showing up cause I don't have the mod right now.

**Comment by IceDragon200** [comment]
Recipe already exists for all variants of it in 2.7

https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/development/src/java/growthcraft/bees/init/GrcBeesRecipes.java#L173-L177

If you added a new fluid container that contained 333mB or 1000mB of Honey / Water, it would be compatible as well.

**Comment by ghost** [comment]
I was using the latest dev version and did not have this feature. It had GC honey jar  and could not use honey from other mods so directly make must :)

**Comment by IceDragon200** [comment]
Then it's not really our problem, we won't tamper with a mod's item registration, (I even seldom to mess with vanilla items), just know we support multiple variants of the recipe (using the ore dictionary and our fluid dictionary) for the recipe, we've already registered ALL (hopefully) our items under the ore dictionary names

**Comment by ghost** [comment]
Ok . Gotcha :D

**Comment by ghost** [comment]
In that case this issue is no longer relevant and I shall close it
