### ISSUE TITLE
TC4 harvest golem can't react grapes with Botania mod

### ISSUE THREAD

**Issue by Esteria** [GrowthcraftCE/Growthcraft-1.7#422]
looks like same issue with #154, couldnt see "Botania"
Thaumcraft 4.2.3.5+GC 2.7.0 works well.
http://i.imgur.com/bgephpH.png
Thaumcraft 4.2.3.5+GC 2.7.0+Botania r1.8-249
http://i.imgur.com/VYBoYQX.png

**Comment by IceDragon200** [comment]
I'll be honest, I haven't the foggiest what's happening there, I've never really tested it...
