### ISSUE TITLE
[2.7.0] Missing crowbar crash on startup

### ISSUE THREAD

**Issue by KryptonCaptain** [GrowthcraftCE/Growthcraft-1.7#423]
Would anything in the config cause this?

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/10/16 1:44 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: growthcraft/core/common/item/ItemCrowbar
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: growthcraft/core/common/item/ItemCrowbar
    at growthcraft.core.GrowthCraftCore.<clinit>(GrowthCraftCore.java:76)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: growthcraft.core.common.item.ItemCrowbar
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 45 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 49 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_102, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2443229144 bytes (2330 MB) / 3417309184 bytes (3259 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 5 total; -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx4096m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_D1 80 mods loaded, 80 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UC  Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UC  Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UC  BugfixMod{2.5.0} [BugfixMod](minecraft.jar) 
    UC  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UC  PotionExtensionCore{1.0.4-forMC1.7} [PotionExtensionCore](minecraft.jar) 
    UC  OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
    UC  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UC  HxCCore-ASM{1.12.4} [HxCKDMS Core ASM](minecraft.jar) 
    UC  FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
    UC  MCP_Wheel{1.1.2} [MC+ Wheel]([1.7.10][1.2] MC+ Wheel - v1.1.2.jar) 
    UC  MCP_Cart{1.3.0} [MC+ Cart]([1.7.10][1.2] MC+ Cart - v1.3.0.jar) 
    UC  bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UC  ArmorStatusHUD{1.27} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.27.jar) 
    UC  DamageIndicatorsMod{3.2.3} [Damage Indicators]([1.7.10]DamIndMod-3.2.3.jar) 
    UC  StatusEffectHUD{1.26} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.26.jar) 
    UC  aiimprovements{0.0.1.19} [AI Improvements](AI_Improvements-1.7.10-0.0.1b19-dev.jar) 
    UC  antiidconflict{1.3.5} [Anti Id Conflict](AntiIdConflict-1.3.5-1.7.10.jar) 
    UC  AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UC  Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UC  AromaBackup{0.1.0.0} [AromaBackup](AromaBackup-1.7.10-0.1.0.0.jar) 
    UC  AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.1.0.0.jar) 
    UC  ascribe{1.7.10-0.1} [Ascribe](Ascribe-1.7.10-0.1.jar) 
    UC  CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
    UC  boilerplate{6.3.0.81} [Boilerplate](boilerplate-1.7.10-6.3.0.81-universal.jar) 
    UC  CleanView{1.7.10-v2} [CleanView](CleanView-1.7.10-v2.jar) 
    UC  controlling{1.0.0} [Controlling](Controlling-1.7.10-1.0.0.jar) 
    UC  cosmeticarmorreworked{1.7.10-v5d} [CosmeticArmorReworked](CosmeticArmorReworked-1.7.10-v5d.jar) 
    UC  DescriptionTags{1.0} [Description Tags](DescriptionTags-1.0-1.7.10.jar) 
    UC  DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UC  endercore{1.7.10-0.2.0.39_beta} [EnderCore](EnderCore-1.7.10-0.2.0.39_beta.jar) 
    UC  eureka{3.0.2} [Eureka](Eureka-1.7.10-3.0.2.jar) 
    UE  Growthcraft{1.7.10-2.7.0} [Growthcraft](growthcraft-1.7.10-2.7.0-complete-core.jar) 
    UE  Growthcraft|Cellar{1.7.10-2.7.0} [Growthcraft Cellar](growthcraft-1.7.10-2.7.0-complete-cellar.jar) 
    UE  Growthcraft|Apples{1.7.10-2.7.0} [Growthcraft Apples](growthcraft-1.7.10-2.7.0-complete-apples.jar) 
    UE  Growthcraft|Bamboo{1.7.10-2.7.0} [Growthcraft Bamboo](growthcraft-1.7.10-2.7.0-complete-bamboo.jar) 
    UE  Growthcraft|Fishtrap{1.7.10-2.7.0} [Growthcraft Fishtrap](growthcraft-1.7.10-2.7.0-complete-fishtrap.jar) 
    UE  Growthcraft|Grapes{1.7.10-2.7.0} [Growthcraft Grapes](growthcraft-1.7.10-2.7.0-complete-grapes.jar) 
    UE  Growthcraft|Hops{1.7.10-2.7.0} [Growthcraft Hops](growthcraft-1.7.10-2.7.0-complete-hops.jar) 
    UE  Growthcraft|Rice{1.7.10-2.7.0} [Growthcraft Rice](growthcraft-1.7.10-2.7.0-complete-rice.jar) 
    UC  HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) 
    UC  HxCCore{1.12.4} [HxC-Core](HxCCore-1.7.10-1.12.4-universal.jar) 
    UC  IguanaTweaks{1.7.10-Beta-19} [Iguana Tweaks](IguanaTweaks-1.7.10-Beta-19.jar) 
    UC  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UC  ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.5-115.jar) 
    UC  ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
    UC  ImmibisCore{59.1.4} [Immibis Core](immibis-core-59.1.4.jar) 
    UC  Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UC  battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](MB_Battlegear2-Bullseye-1.0.8.2.jar) 
    UC  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UC  TConstruct{1.7.10-1.8.10-K} [Tinkers' Construct](TConstruct-1.7.10-1.8.10-K.jar) 
    UC  InventoryCenterer{1.7.10-0.1.3} [Inventory Centerer](InventoryCenterer-1.7.10-0.1.3.jar) 
    UC  inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UC  MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UC  modtweaker2{0.9.5} [Mod Tweaker 2](ModTweaker2-0.9.5.jar) 
    UC  NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
    UC  neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UC  recipehandler{1.7.10} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.3%281.7.10%29.jar) 
    UC  NoNausea{1.0} [No Nausea](NoNausea-MC1.7.10-1.0.jar) 
    UC  OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
    UC  packchevsky{b5} [Potion Packs](PotionPacks_1.7.10_b5.zip) 
    UC  Squeedometer{1.0.3} [Squeedometer](Squeedometer-mc1.7.x-1.0.3.jar) 
    UC  TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UC  TravellersGear{1.16.4} [Traveller's Gear](TravellersGear-1.7.10-1.16.4.jar) 
    UC  TwoGraves{1710.1.1} [Graves](TwoGraves-1710.1.1.jar) 
    UC  WailaHarvestability{1.1.1} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.1.jar) 
    UC  wawla{1.3.3} [What Are We Looking At](Wawla-1.3.3-1.7.10.jar) 
    UC  zebrastogglesneak{1.2} [Zebra's Toggle Sneak&Sprint](zebrastogglesneak-1.7.10-1.2.8-forge.jar) 
    UC  ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UC  McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UC  IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UC  ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
    Class transformer null safety: found misbehaving transformers: williewillus.BugfixMod.BugfixModClassTransformer(williewillus.BugfixMod.BugfixModClassTransformer@39ec2988) crashed with java.lang.NullPointerException(null),me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@3a22ef09) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@625a21ac) returned non-null result: 0
    CoFHCore: -[1.7.10]3.1.3-327
    ThermalFoundation: -[1.7.10]1.2.5-115
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    OptiFine Version: OptiFine_1.7.10_HD_D1
    Render Distance Chunks: 12
    Mipmaps: 4
    Anisotropic Filtering: 4
    Antialiasing: 0
    Multitexture: false
    OpenGlVersion: 4.0.0 - Build 10.18.10.4358
    OpenGlRenderer: Intel(R) HD Graphics 4000
    OpenGlVendor: Intel
    CpuCount: 8

**Comment by IceDragon200** [comment]
Next time, please consider placing your log dump into a [gist](https://gist.github.com/), otherwise it makes scrolling hard.
My pains aside, where did you get the Growthcraft build (here on github via our releases, or curse, or somewhere else)?

Also, I've just tested it by grabbing a copy of Growthcraft-2.7.0 from curse and threw it into a fresh minecraft instance.
It loaded fine, though in your error log, the error was caused by a missing interface, the `buildcraft.api.tools.IToolWrench` interface, which I HAVE included with Growthcraft, and would be replaced by the Buildcraft one if added.

If I'm correct, you've used the individual modules from github, which ship without parts of the bundled API...

One moment, I'll have @Alatyami do a patch release shortly

**Comment by KryptonCaptain** [comment]
I downloaded the 2.7.0 bundled release off curse, since I don't use the bees or milk modules.
Would this config being off cause this or contribute?

```
# So, I heard you didn't have a wrench, we got you covered; Default : false
    B:"Use Amazing Stick"=false
```

**Comment by IceDragon200** [comment]
That config is no longer available, it was removed a few versions back after crowbars were added

**Comment by Alatyami** [comment]
Just tested with the 2.7.0 release and could repeat the error. I checked the core.conf and still have the obsolete conf entry for the amazing stick, so that isn't a factor. I tested crafting all the different colors of crowbars and they even work in NEI. I upgraded my Forge to 1614 and still couldn't duplicate any error. 

I'll test with the split jars later today.

**Comment by ghost** [comment]
I have the same issue. I'm using GC 2.7.2 and some more mods. 
Crashlog: http://pastebin.com/1ui3UbXn

**Comment by ghost** [comment]
One more thing. 
If i launch it without anything but gregtech and IC2, it's OK. 
If i launch it without GregTech and IC2, but NEI it's OK. 
But if i launch GregTech, IC2 and NEI altogether it crashes. Just these mods plus chickencore, not even crashlog mods.

**Comment by IceDragon200** [comment]
@4000DC I've done a quick test in development using the following:

In development: (WORKS)
```
Growthcraft - 2.7.2 
Industrial Craft 2 - 2.2.827-experimental 
Greg Tech - 6.04.00
NEI - 1.0.5.120
Buildcraft - 7.1.17
```

In release: (ERRORED once NEI was added)
```
Growthcraft - 2.7.2 
Industrial Craft 2 - 2.2.827-experimental 
Greg Tech - 6.04.00
Buildcraft - 7.1.17 (removed when testing bundled Growthcraft's bundled API)
NEI - 1.0.5.111 (Added after the bundle test was done)
```

I've skimmed the logs, FML does detect that Growthcraft ships the `Buildcraft API|Tools`

Sadly I can't seem to figure this out, if anyone else any ideas, please let me know!

**Comment by ghost** [comment]
I know nothing about coding, sadly. The only thing i can help you with, is some sort of brute-force, looking for "crashable" mod combination (that's what i partially did already).

**Comment by Alatyami** [comment]
Still looking into why the buildcraft api isn't loading correctly. Of note, including the buildcraft-7.1.17-api.jar everything works fine.
