### ISSUE TITLE
BeeBox Item Duplication №2: Dropping phantom items after block destruction

### ISSUE THREAD

**Issue by Ghostlyr** [GrowthcraftCE/Growthcraft-1.7#425]
![-1](https://cloud.githubusercontent.com/assets/8511068/19401996/4c4ec2d4-9280-11e6-9290-3a75fe900e7b.gif)

How you can see, after breaking beebox dropping dubbed contents. But these items can not be picked up player, because because they are phantom.

But you can pickup by another way, for example, via hopper:

![-2](https://cloud.githubusercontent.com/assets/8511068/19402265/fa638516-9281-11e6-84b5-75bb833c80b0.gif)

Also, if you use shift-click to put contents into beebox, container does not updating on client-side, which is why item is visually are still in the inventory.
It's very terrible, guys.

MC 1.7.10
Forge 1644
Growthcraft 2.7.0 (dev beea035)

**Comment by IceDragon200** [comment]
Fixed in the latest development, fixing up the PR right now and uploading the build.

Build is up, give it a spin and let me know how it goes

**Comment by Ghostlyr** [comment]
Issue with shift-click completely resolved. 
With double drop seem to be too. ~~Are no longer possible to pick up in hopper, but vusually it still drop twice.~~

// EDIT:
Sorry, it was just a big stack =)
