### ISSUE TITLE
Properly close FishTrap inventory

### ISSUE THREAD

**Issue by Ghostlyr** [GrowthcraftCE/Growthcraft-1.7#426]
Fish trap container is behaving strangely. It does not close visually when I try to do it via Bukkit plugins.
With all other containers from mod it works perfectly.

I found the difference between other TileEntities and TileEntityFishTrap. In the latest missing seems to be necessary events: `updateEntity`, `onInventoryChanged`, `updateBlockTick`.
Could they be the cause of this problem?

Last version of Growthcraft.
Server based on forge 1614 ([Thermos](https://github.com/CyberdyneCC/Thermos/releases))

**Comment by IceDragon200** [comment]
@Ghostlyr The fishtrap is updated via the block, it doesn't have a per-tick update (hence needUpdate returns false), so it wouldn't implement `updateEntity`, or `updateBlockTick`.

It also wouldn't implement or override `onInventoryChanged`, the base class would assume the default behaviour (which is suppose to be markDirty).

**Comment by Ghostlyr** [comment]
Hmm, very strange why this container behaves differently
