### ISSUE TITLE
Problem with Russian localization

### ISSUE THREAD

**Issue by vrnRaptor** [GrowthcraftCE/Growthcraft-1.7#427]
Some objects have no localization. It's only a small part.
Maybe not the translated text is best left to the English?
![2016-11-05_21 35 14](https://cloud.githubusercontent.com/assets/13599993/20032684/00eae7be-a3a1-11e6-9554-5e9e746189b7.png)

**Comment by IceDragon200** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.7/blob/development/src/resources/assets/grcbees/lang/ru_RU.lang#L25-L122

It's all untranslated, feel free to translate them and send us a PR

**Comment by vrnRaptor** [comment]
For myself, I added the English translation on the untranslated words. Maybe later I translate.
[assets.zip](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/573817/assets.zip)

**Comment by vrnRaptor** [comment]
I translated almost all, better than nothing:
[assets.zip](https://github.com/GrowthcraftCE/Growthcraft-1.7/files/591859/assets.zip)

**Comment by IceDragon200** [comment]
@vrnRaptor :D Nice work, I'll double check em once (I don't speak Russian, so it will be me skimming it)

5f4392a20dc3c1be8808effecbbb2d492ec30237

**Comment by vrnRaptor** [comment]
Happy to help)

**Comment by vrnRaptor** [comment]
Happy to help :)
