### ISSUE TITLE
Bring back GrowthCraft Flowers!

### ISSUE THREAD

**Issue by LEWeee** [GrowthcraftCE/Growthcraft-1.7#429]
Hello!
My name is . You probably know me cause I posted here about having permission for modpack. I wanted to ask, would you like to bring back GrowthCraft Flowers? It's dead part of orginal growthcraft and in my opinion it was really neat.

Thanks!

**Comment by Alatyami** [comment]
We might with GC 3.0, but as far as GC 2.7 goes, we're not adding new features.
