### ISSUE TITLE
Modpack Request

### ISSUE THREAD

**Issue by CrazyCowboy557** [GrowthcraftCE/Growthcraft-1.7#433]
I have gathered the other's permission and am looking to upload a modpack to Technic Platform. Here is a list of mods:
Animation API
Ars Magica 2
Baubles
BaublesHUD
BetterBedrockGen
BetterFPS
BloodMagic
Bookshelf API
Botania
Cannibalism
Carpenter's Blocks
Chaotic Karma
ChickenChunks
CodeChickenCore
CoFH Core
CoFH Lib
Creeper Chickens
DecoCraft2
DynamicTransport
E-Mobile
Emotes
Enchanting Plus
FastCraft
FastLeafDecay
FlaxBeard's Steam Power
Gender Mod
Gravestone
GrowthCraft Community
Guide API
Hammerz
Hat Stand
Hats
Hungry Zombies
IChunUtil
Immersive Engineering
Immersive Integration
Inventory Tweaks
Iron Backpacks
Kore Sample
Lovely Robots
Luppii's Ladders
Matter Overdrive
Modular Systems
Modular Armour
More Player Models
MultiMine
Nakranoth's Herdcraft
NEI Integration
NetherPortalFix
NotEnoughItems
NotEnoughResources
PChan3
Placeable Gunpowder
Primitive Mobs
Redstone Aresenal
Ruins
Simply Jetpacks
Slimevoid Library
Starting Inventory
Status Effect HUD
Sync
Thermal Foundation
Tomahawk
Treecapitator
Unidict
Utility Mobs
Waila
Waila Harvestability
Wawla
Witchery
Xaeros Minimap

Also here's a link to the Technic page.
http://www.technicpack.net/modpack/wills-unstable-stuff.895934

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
