### ISSUE TITLE
Yet another Saltwater Bucket/Bottle-issue

### ISSUE THREAD

**Issue by DJMadMax** [GrowthcraftCE/Growthcraft-1.7#434]
First of all:
Thank you so much for such a great mod and for keeping it alive and supporting us users through so many ways. I actually feel a little bad for pointing out this issue but still it is a bit of a downer for me:

I'm having problems with smelting the saltwater bucket and the saltwater bottle. Both give me their ammount of salt after being smelted (6 and 2) but the bucket and the bottle both disappear after doing so. Trading 3 iron for 6 salt isnt what i'm ready to exchange and three blocks of glass are much less worth than iron but still it seems like it's not supposed to consume the saltwater's containers.

I'm using 2.6.2 together with most of the Life in the Woods-mods, latest Forge 1.7.10.

I would be very happy if there's a bugfix/workaround for this.

Thank you in advance and keep up the great work!

Greetings from Germany,
Sven

**Comment by IceDragon200** [comment]
@DJMadMax
Can you reproduce this issue in 2.7.2?

I've been out of the loop for awhile, so I don't recall if I did fix it or not...

**Comment by DJMadMax** [comment]
Thanks for your quick reply. Downloaded 2.7.2 already but will test it tomorrow (it's 10pm in Germany and i have to get up early for work). 

What i can say so far:
2.7.2 worked with my other mods but even if the salt water feature was set to true, there were no such items in the NEI-interface. Maybe it has something to do with me mixing it together with my old (backuped) world from 2.6.2.

Like i said, i will test that tomorrow with a clean, new world.
Have a nice evening :)

**Comment by Paliquin857** [comment]
Sorry for the necro post. Some of are still playing 1.7.10! :) This still seems to be the case in 2.7.2.
