### ISSUE TITLE
"Modpack" Request

### ISSUE THREAD

**Issue by BeansyPup** [GrowthcraftCE/Growthcraft-1.7#435]
Hi! Myself and some friends are starting up a whitelisted modded server and would like to use your mod on it. It has a few other mods included, however, we're planning to keep the modlist private for anyone not accepted and whitelisted onto the server. However, this will not really be a "modpack," it's simply a list of mods, credit to the authors, and links to their pages so people may download the mods themselves. We do not package them in a jar file or otherwise provide a download. It's simply a "modlist," but we're calling it a modpack for convenience. We mainly wanted to make sure this is ok, and wanted to ask permission in case it was needed. If you need the modlist, we are willing to send it privately but would prefer not to post it publicly. Thanks!

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
