### ISSUE TITLE
Modpack request

### ISSUE THREAD

**Issue by Anna131313262** [GrowthcraftCE/Growthcraft-1.7#437]
Hey all! I'm making a modpack over at the Technic site. Can I have your permission to include Growthcraft in it? 

The other mods are:
Bibliowoods
Bibliocraft
Decocraft
Inventory Tweaks
Mantle
Minechem
Natura
NEI/Chickencore
Optifine
Pam’s Harvestcraft
Radix Core
TcNodeTracker
Tinkers Construct
Thaumcraft
Thaumcraft NEI plugin
CoFHCore/Thermal Foundation/Thermal Expansion/Thermal Dynamics
TreeCapitator & bspkrsCore 
Xaeros Minimap
DragonAPI

Let me know if you need any more info. Thanks!

**Comment by Alatyami** [comment]
Approved.
