### ISSUE TITLE
Permission for use in mod pack

### ISSUE THREAD

**Issue by Carbs11** [GrowthcraftCE/Growthcraft-1.7#438]
Please consider the use of this mod in my modpack, TechFarm (https://www.technicpack.net/modpack/techfarm-pack.626213).

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
