### ISSUE TITLE
Permission request for CraftMine pack

### ISSUE THREAD

**Issue by PaintNinja** [GrowthcraftCE/Growthcraft-1.7#439]
Hello,

I'm the author of CraftMine, the oldest still maintained pack on the Technic Platform. I would like to request permission to add Growthcraft Community Edition to the pack.

You can find the pack here: https://craftmine.gadget-guy.com

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
