### ISSUE TITLE
Modpack Request

### ISSUE THREAD

**Issue by Yoogain** [GrowthcraftCE/Growthcraft-1.7#440]
Requesting permission to use the mod on the Frustration modpack, posted to ATLauncher and Technic. May post the newer version to Cursed/Twitch once the COFH version is recognized again.

Mod List:
Advanced Machines
AE2Stuff
AOBD
AppleCore
Applied Energistics 2
Archimedes' Ships
Aroma1997Core
Aroma1997Dimension
AsieLib
Backpack
Baubles
BDLib
Better Questing
Better Questing: Standard Expansion
BetterAchievements
Bibliocraft
Bibliowoods
BinniePatcher
BinniesMods
Biomes O' Plenty
BloodMagic
Botania
Buildcraft
BuildcraftCompat
CarpentersBlocks
CaveControl
ChickenChunks
Chisel
Chromaticraft
ClimateControl
CodeChickenCore
CoFH Core
Computronics
Condensed Ores
Convenient Recipes
CoroUtil
CritterPet
Damage Indicators
DenseOres
DragonAPI
ElectricalAge
Electricraft
Enchanting Plus
EnderCompass
EnderCore
EnderIO
EnderIOAddons
EnderStorage
EnderTech
EnderZoo
EndlessDragons
Expanded Redstone
Extra Utilities
ExtraCells2
ExtraTiC
Farseek
FastCraft
Forbidden Magic
Forestry
Forge
FoxLib
FrustrationEdits
Gendustry
Geostrata
Hardcore Wither
IC2 Nuclear Control
iChun Utils
Iguanas Tinker Tweaks
Immersive Engineering
Immersive Integration
In-Game Wiki Mod
IndustrialCraft 2
InGameInfoXML
Inventory Tweaks
IronChests
ItemPhysic (Lite)
IvToolkit
Jabba
JourneyMap
LegacyCraft
LunatriusCore
Magic Bees
Mantle
MeteorCraft
MineTweaker3
MineTweakerRecipeMaker
ModTweaker2
Morph
Morpheus
MouseTweaks
Natura
NEI Addons
NEI Integration
NoMoreRecipeConflicts
NotEnoughItems
Open Computers
OpenBlocks
OpenModsLib
OpenPeripherals
Pams Harvestcraft
Pneumaticcraft
Project Red Base
Project Red Compat
Project Red Fabrication
Project Red Integration
Project Red Lighting
Project Red Mechanical
Project Red World
ProjectBLUE
ProjectE
Railcraft
ReactorCraft
Recurrent Complex (As a utility)
Redstone Arsenal
RotaryCraft
SolarFlux
Sound Filters
Steves Addons
Steves Factory Manager
Steves Workshop
Streams
Tails
Technomancy
TerriroryZone
Thaumcraft
Thaumcraft Inventory Scanning
Thaumcraft NEI Plugin
Thaumic Energistics
Thaumic Exploration
Thaumic Tinkerer
Thermal Dynamics
Thermal Expansion
Thermal Foundation
TiC Tooltips
Tinkers Construct
Tinkers Mechworks
Translocators
Twilight Forest
Useful TNT
Void Monster
WAILA
WAILA Harvestability
WAILA Plugins
WAWLA
Weather2
Wireless Redstone (WR-CBE)
ZTones

Links:
ATLauncher: https://www.atlauncher.com/pack/Frustration
Technic: https://www.technicpack.net/modpack/fustration
Cursed (Should it be updated): https://mods.curse.com/modpacks/minecraft/259722-frustration

**Comment by IceDragon200** [comment]
[![Modpack Approved](https://raw.githubusercontent.com/GrowthcraftCE/Growthcraft-DesignDocs/master/imgs/GC_Modpack_Approved_128.png)](https://github.com/GrowthcraftCE/Growthcraft-1.7/wiki/Modpacks-with-Growthcraft#your-modpack-has-been-approved)
