### ISSUE TITLE
Fish trap ignores stack limits and merges NBT data

### ISSUE THREAD

**Issue by Ghostlyr** [GrowthcraftCE/Growthcraft-1.7#442]
![2017-07-04_18 51 22](https://user-images.githubusercontent.com/8511068/27830804-e08d2304-60e9-11e7-960a-7c4173bdfc08.png)
![2017-07-04_18 54 19](https://user-images.githubusercontent.com/8511068/27830885-31a54974-60ea-11e7-9335-5961c6e21963.png)
![2017-07-04_18 54 10](https://user-images.githubusercontent.com/8511068/27830884-31a38d00-60ea-11e7-9844-5b5b9639ec44.png)

Forge 1614 1.7.10
Growthcraft 2.7.2

**Comment by Alatyami** [comment]
This is something that will be fixed in future releases. For GC 2.7 we do not have immediate plans to fix this.

**Comment by Alatyami** [comment]
Growtcraft 3.0.0-alpha has fixed this issue.

https://github.com/GrowthcraftCE/Growthcraft-1.11/issues/3
