### ISSUE TITLE
Fishtrap catching fish when there is not water [1.11]

### ISSUE THREAD

**Issue by Kisutora** [GrowthcraftCE/Growthcraft-1.7#444]
So apparently fish can fly nowadays. Fishtrap started filling up while I was editing the GUI textures. :D
![fishtrap_airfish](https://user-images.githubusercontent.com/22685232/28438959-a549c29a-6da8-11e7-9005-78c5d7daf82a.png)
![fishtrap_nowater](https://user-images.githubusercontent.com/22685232/28438958-a54680a8-6da8-11e7-80ee-3bc2b73a9908.png)
Seems a bit broken.

**Comment by Alatyami** [comment]
Crap ... busted ... got us on this one ... 

Can you report this over here: https://github.com/GrowthcraftCE/Growthcraft-1.11/issues so that you get credit for finding the bug?

Maybe if you place in the air ... it becomes a bat trap :D

**Comment by Kisutora** [comment]
Hahahahahahaha ok I will. ;P
