### ISSUE TITLE
About the pasteurised milk

### ISSUE THREAD

**Issue by ChiangTseMin** [GrowthcraftCE/Growthcraft-1.7#445]
Just one question:
How can I produce the Pasterurised Milk?

**Comment by ChiangTseMin** [comment]
I am not a native English speaker so my English is poor :)
could you answer it in a simple way?
Appreciate it.

**Comment by IceDragon200** [comment]
@ChiangTseMin Brew 250mB of Skim Milk (Fluid) and Sugar in a Brew Kettle
```
Tools / Blocks:
  1x Brew Kettle

Ingredients:
  1x Sugar
  250mB Skim Milk  

Produces:
  250mB Pasteurized Milk

Residue:
  100% - 1x Starter Culture 

Procedure:
  * Place Brew Kettle above heat source
  * Heat to maximum
  * Add 250mB of Skim Milk (or 1 bucket will require 4 sugar)
  * Add 1 Sugar for every 250mB of Skim Milk
  * Wait
  * Wait some more
  * You should have 250mB of Pasteurized Milk
```

**Comment by ChiangTseMin** [comment]
Thanks!

**Comment by ChiangTseMin** [comment]
One more question :)
What can I do with the Pasteurized Milk?Only producing the starter culture?

**Comment by IceDragon200** [comment]
@ChiangTseMin Sorry about the late reply, work and all.

I've been going over the code base, and I believe pasteurized milk is only used for creating starter culture.

**Comment by ChiangTseMin** [comment]
我已经收到您的邮件，感谢您的来信。Mi ricevis vian retposton kaj dankon pro via letero.Thanks for e-mailing me，I've received your e-mail.Recebi seu email, obrigado pela Carta.He recibido su correo electrónico, gracias por tu carta.Ich habe ihre e-mail, vielen dank für den brief.メールをいただきました、お手紙ありがとうございました。Я получил ваше письмо, спасибо за письмо.
