### ISSUE TITLE
Something off with buckets in creative

### ISSUE THREAD

**Issue by Tycja** [GrowthcraftCE/Growthcraft-1.7#449]
I stumbled upon that one very annoying problem. Can't collect saltwater, yes it is turned on in config and I tried it in Ocean biome. Even better things is that when I tested it I couldn't fill bucket or bottle with any water. Block of water did disappeared but bucket was empty. I turned salt water off and decided that it's a shame but would love to be able to gather water, and still empty buckets.

I was in creative mode when testing, mentioning it in case it could cause any problem. Tested it in survival mode too, stronge things happened in version 2.7.0.

Edit: Made few quick tests, both in single player and server. Apparently whatever caused issue with bucket acting all strange got fixed after instaling 2.7.3 release. Creative still doesn't work but survival mode is all working now.

**Comment by Alatyami** [comment]
Interesting ... while we are actaully porting over to MC 1.11.2 right now, this probably will not be fixed for 1.7.10. We'll keep it open though.
