### ISSUE TITLE
Curse Forge Project

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#45]
I was about to start a new project registration on Curse and as Gwafu is unresponsive I was thinking of making the project titled as "Growthcraft Community Edition"? But it sounded, well not cool. What are some ideas for our project name?  

After we establish the Curse project then I'll create the minecraft forums post so that we can restart the thread and get away from the old one that Gwafu started.

**Comment by spannerman79** [comment]
How about Growthcraft CE?

**Comment by Ar97x** [comment]
I liked Community Edition, but as an option we could use GrowthCraft Revival

**Comment by spannerman79** [comment]
That's good too. But "technically" Growthcraft hasn't died - so there isn't
a revival per say.

**Comment by Ar97x** [comment]
Metaphorically

**Comment by Oxosorrel** [comment]
There are lots of puns that would work. 

Growthcraft: Replanted
Growthcraft: Reseeded
Growthcraft: Transplanted
Growthcraft: Regrowth

**Comment by Ar97x** [comment]
ReGrowthCraft?

**Comment by Oxosorrel** [comment]
Growthcraft: Community Garden
Growthcraft: Second Harvest
Growthcraft: Regrown

(I should stop now)

**Comment by labpaw** [comment]
Growthcraft: Regrowth sounds cool or maybe Growthcraft: Reborn.

**Comment by Alatyami** [comment]
I'm thinking "Growthcraft CE" and the we can name the major releases for fun.

**Comment by Alatyami** [comment]
Ended up going with the CE. Project is currently being reviewed, then I'll post a link when it is live.

**Comment by spannerman79** [comment]
http://minecraft.curseforge.com/mc-mods/235092-growthcraft-community-edition
