### ISSUE TITLE
I am having an issue when I add all mods together

### ISSUE THREAD

**Issue by lShanghaiMoonl** [GrowthcraftCE/Growthcraft-1.7#451]
I am having an issue when I add all mods together, is there a version that someone can send me with all growthcraft addons (apples, bamboo, bees, cellar, fishtrap, grapes, hops, milk, rice) that actually works together for 1.11.2??? 
<img width="741" alt="screen shot 2017-12-29 at 5 13 48 pm" src="https://user-images.githubusercontent.com/21119425/34450404-970fb6f6-ecbc-11e7-902e-6ad475221166.png">

**Comment by Alatyami** [comment]
You only need one file for Growthcraft 1.11.2. You should only have one "growthcraft-1.11.2-3.0.0.5.jar" file. You have multiple copies in your mods folder.

**Comment by Alatyami** [comment]
Side note ... go[ here](https://github.com/GrowthcraftCE/Growthcraft-1.11) for Growthcraft 3 (Minecraft 1.11.2) ... this is the repo for Growthcraft 2 (Minecraft 1.7.10).

**Comment by lShanghaiMoonl** [comment]
okay I only added the 3.0.0.5 and it worked! But now I don't have growthcraft cellar or bees now. The download area is very confusing and hard to navigate sorry to sound difficult but I can't seem to find it.

**Comment by Alatyami** [comment]
Growthcraft 3 is in pre-alpha ... it will take time to port everything over.
