### ISSUE TITLE
3.0.0.5 is working but no bees or brewing

### ISSUE THREAD

**Issue by lShanghaiMoonl** [GrowthcraftCE/Growthcraft-1.7#452]
Okay I only added the 3.0.0.5 and it worked! But now I don't have growthcraft cellar or bees now. The download area is very confusing and hard to navigate sorry to sound difficult but I can't seem to find it. 🤔

**Comment by IceDragon200** [comment]
@lShanghaiMoonl This is for Growthcraft 2.x development (for minecraft 1.7.x), I think you wanted to post this issue in https://github.com/GrowthcraftCE/Growthcraft-1.11 (for 3.x development)

As for your issue, bees has not been added to GC 3 yet, cellar should be available, you'll need to take up that issue on the 1.11 repo.

Please close this issue once you've moved/posted your issue over there :)
