### ISSUE TITLE
How to download Growthcraft Milk?

### ISSUE THREAD

**Issue by kuvpukg** [GrowthcraftCE/Growthcraft-1.7#453]
Please give me download link to download GrowthcraftMilk-1.7.10

**Comment by IceDragon200** [comment]
You can grab from the bundle I think:

https://github.com/GrowthcraftCE/Growthcraft-1.7/releases/download/2.7.2/growthcraft-1.7.10-2.7.2-bundle.zip

**Comment by kuvpukg** [comment]
thx
