### ISSUE TITLE
Growthcraft Celar machines only work when player in chunk

### ISSUE THREAD

**Issue by Meibisu** [GrowthcraftCE/Growthcraft-1.7#456]
Sooo...Growthcraft Celar machines only work when player in chunk. When he leave that chunk, all progress is resets to zero. Thermos 1.7.10 - 1614.58

**Comment by IceDragon200** [comment]
@Kundello Is this an observed issue with just Growthcraft loaded?

I'm not sure that should happen, if the tile was unloaded it would save it's progress and reload the next time it's reloaded, which is good old minecraft behaviour.

Let me know when and if you've tested Growthcraft alone about this issue

**Comment by Meibisu** [comment]
I tested it alone about this issue. When player leave this chunk, progress is just resetting to zero, not saving :C
growthcraft-1.7.10-2.7.2-complete
