### ISSUE TITLE
Modpack Request - ConvergenceCraft

### ISSUE THREAD

**Issue by vediis** [GrowthcraftCE/Growthcraft-1.7#460]
Hello,
I'd love to use Growthcraft in our 1.7.10 small fantasy modpack. 
https://www.technicpack.net/modpack/convergence-craft.1042983
Mod list:
* Antique Atlas 1.7.10 4.4.4
* Aquaculture 1.7.10 1.2.6.21
* Backpacks
* Baubles 1.7.10 1.0.1.10
* BetterFoliage 1.7.10 2.0.17
* Bibliocraft 1.7.10 1.11.7
* Bibliowoods 1.7.10 1.9
* Biomes O' Plenty 1.7.10 2.1.0.2308
* Botania 1.7.10 R1.8 249
* CodeChickenCore 1.7.10 1.0.7.47
* Crash Logs Additions 1.7.10 1.1
* CustomNPCs 1.7.10  Oct.29, 2017 version
* Ding 1.7.10 v.2
* Et Futurum 1.5.5
* Fairy Lights 1.7.10
* Growthcraft 1.7.10 2.7.2
* InventoryTweaks 1.59 dev 152
* IVtoolkit 1.2.1
* MineFantasy2 2.8.14.6
* MineTweaker3 1.7.10  3.0.10B
* ModTweaker 2-0.9.6
* NotEnoughItems .7.10 1.0.5.120 (supported by CodeChicken)
* Primitive Mobs 1.7.10
* Tainted Magic 7.6
* Thaumcraft 1.7.10 4.2.3.5
* Thaumic Horizons 1.7.10 1.1.9.7
* Thaumcraft NEI plugin 1.7.10 1.7a
* Twilight Forest 1.7.10 2.3.8
* Witchery 1.7.10 0.24.1
* Ye Gamol Chattels 1.1.2

**Comment by Alatyami** [comment]
Sounds like a fun pack ... 

Approved.
