### ISSUE TITLE
All players hear fish trap

### ISSUE THREAD

**Issue by viveleroi** [GrowthcraftCE/Growthcraft-1.7#461]
growthcraft-1.12.2-4.1.2

Fish traps play an inventory click sound and that noise can be heard by all players when a player is close to the trap (either close enough to hear it, or close enough for it to be loaded, I'm not sure).

**Comment by Alatyami** [comment]
That is by design. Any player within 6 blocks here's the click and knows that the fishtrap was updated.

**Comment by viveleroi** [comment]
But I could hear it and was over 500 blocks away.

**Comment by Alatyami** [comment]
Ah, yah, that's a bug.

**Comment by viveleroi** [comment]
Sorry I should have been clearer - all players, regardless of distance, can hear the click.

Also I guess I opened this in the wrong repo - my mistake.

**Comment by Alatyami** [comment]
Can you open a new issue in the 1.12 repo?

https://github.com/GrowthcraftCE/Growthcraft-1.12/issues
