### ISSUE TITLE
Restore compatibility with Thaumcraft and Forestry

### ISSUE THREAD

**Issue by labpaw** [GrowthcraftCE/Growthcraft-1.7#48]
I've noticed that some compat already in but it's commented out (probably outdated and never was touched since 1.6.4). Perhaps, it will be better to remove Forestry compat and move it into Forestry itself since Forestry have built-in support for many mods. @Nirek-K wrote many compatibility modules for Forestry, so I'm ping him and he can take a look.

**Comment by Nirek-K** [comment]
I've actually been meaning to do something with growthcraft for a while, but everytime I looked I couldn't find a version that was still supported.

**Comment by Nirek-K** [comment]
If you have a list of all the things commented out/in need of restore, as well as any other things you think might fit as integration, that would be great.

**Comment by labpaw** [comment]
List of commented out stuff:
1) [GrowthCraftGrapes](https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/grapes/GrowthCraftGrapes.java#L236)
2) [GrowthCraftApples](https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/apples/GrowthCraftApples.java#L209)
3) [GrowthCraftRice](https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/rice/GrowthCraftRice.java#L193)
4) [GrowthCraftHops](https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/hops/GrowthCraftHops.java#L212)
5) [GrowthCraftBees](https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/bees/GrowthCraftBees.java#L220)
6) [GrowthCraftBamboo](https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/bamboo/GrowthCraftBamboo.java#L332)

**Comment by Ar97x** [comment]
What kind of compat are you thinking with Forestry?

**Comment by Nirek-K** [comment]
Most of that should be quite straightforward, only bit that should/needs to be in growthcraft is the beeregistry/booze stuff in GrowthCraftBees.
I wasn't thinking anything in particular, why I asked for a list, I have only cursory knowledge of what all growthcraft does from forum post/pictures. Multifarm 'should' in theory be possible with all the spadework I've done with the orchard logic, have to sit down and look.

**Comment by Ar97x** [comment]
Do you think even different crops, like grapes and hops should work with the autofarms (or that you can make it work)? I don't play with forestry so much, but I have a lot of admiration for it, in my opinion is one of the most complete mods of Minecraft. Maybe with the improvements I might start putting it in my modpacks again.

**Comment by Nirek-K** [comment]
I think so, unless it stores maturity in some completely strange way. Won't know definitively until I load it up and give it a poke.

**Comment by Ar97x** [comment]
I don't think so, Waila showed up maturity just like regular crops, if it matters anything.

**Comment by Nirek-K** [comment]
Give unstable 686+ a try, I think I got everything, cursory testing on the multifarm part.
https://github.com/ForestryMC/ForestryMC/commit/bcd97662b273e775ff6dac6985b34979b5e5892e

**Comment by labpaw** [comment]
Nice work @Nirek-K! Maybe you can make a PR to fix Forestry integration on Growthcraft? For bees and booze stuff.

**Comment by Nirek-K** [comment]
It looks like that bit could just be uncommented, none of those names have changed as far as I can see.

By that bit, I mean these: https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/bees/GrowthCraftBees.java#L225-L243  
You can remove these lines
https://github.com/Gwafu/Growthcraft-1.7/blob/e1fa09b12eec6b78269c1e4a3db35b82ae5ff7d1/src/java/growthcraft/bees/GrowthCraftBees.java#L244-L257
and uncomment that section (assuming those calls haven't changed in Growthcraft internal, no idea what that actually does)

**Comment by labpaw** [comment]
@IceDragon200 once your PRs merged, can you do what @Nirek-K suggested here? This would be cool.

**Comment by IceDragon200** [comment]
@Adaptivity @Nirek-K So, I started restoring Thaumcraft, there are quite a few changes to the api, also Aspect.SEED is no longer available, I'm working on a rather messy branch at the moment, also do you know if there is a thaumcraft gradle dependency?

**Comment by spannerman79** [comment]
Not sure about grade but the Thaumcraft API is on github https://github.com/Azanor/thaumcraft-api

**Comment by IceDragon200** [comment]
@spannerman79 Yeah, I resorted to copying the api into the growthcraft code base, which is why I asked about a gradle dep :(

**Comment by spannerman79** [comment]
I have no idea how gradle works or even if this will work for you but I came across this https://github.com/bat-cha/gradle-plugin-git-dependencies

Warning: I don't know java or how gradle works. Take this comment as a grain of salt

**Comment by IceDragon200** [comment]
@spannerman79 @Adaptivity @Nirek-K https://github.com/alatyami/Growthcraft-1.7/pull/105
Could someone, anyone please test this

I'm a Thaumcraft noob...

**Comment by IceDragon200** [comment]
@Sunconure11 @Alatyami @Adaptivity Both integrations have been done and merged into development, so I guess you can close this issue unless there is any other mods you'd like

**Comment by labpaw** [comment]
This should be closed. There are another issue exist for other mod support.
