### ISSUE TITLE
Agave Syrup

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#5]

**Comment by Sunconure11** [comment]
I started writing on the wiki, and wrote down a concept for Agave.

https://github.com/alatyami/Growthcraft-1.7/wiki/Growthcraft-Agave-(Concept)

**Comment by Alatyami** [comment]
Awesome, I am thinking that we are going to need to create a new (sub)plugin to handle items like this one that do not fit into the currently named plugins. 

After reading your description, this is going to be a fun mod addition, I haven't worked with plants before.
