### ISSUE TITLE
Fluids needs rewriting

### ISSUE THREAD

**Issue by labpaw** [GrowthcraftCE/Growthcraft-1.7#52]
Here's some issues which I've noticed during testing fluids:

1) You can't pour Growthcraft fluids in world.

2) ~~Custom buckets (like [wooden buckets](http://minecraft.curseforge.com/mc-mods/233189-sbm-wooden-buckets)) can't pickup Growthcraft fluids. However, other custom fluid containers can hold GC fluids without problems (like OpenBlocks tank, Mekanism portable tank etc) so I'm ping @DarkGuardsman maybe he can point to the problem.~~ forget about this, support for bucket filling from tanks was removed in Wooden Buckets 0.0.1b3 due to glitches with some mods.

**Comment by DarkGuardsman** [comment]
As far as i can tell the mod doesn't have blocks for it's fluids. Which is not a problem as not all fluids have blocks. As for the wooden buckets they are only coded to pickup water, lava, and IFluidBlocks. Support for tanks is also not removed but rather I removed support for forge's fill bucket event. Which was constantly failing across several mods. What might actually be going on is most tanks are only coded to detect for iron buckets. I will fix this in later versions of wood buckets.

https://github.com/BuiltBrokenModding/SingleBlockMods/issues/3

**Comment by Alatyami** [comment]
@Adaptivity  whcih fluids do you want to be able to be poured into the world?  All of them, e.g. have a swimming pool filled with Booz or Wine?

**Comment by labpaw** [comment]
Yes, all of them should be placeable in the world. There are no reason to not.

**Comment by Alatyami** [comment]
Simple enough, I'll get to it this week.

**Comment by Alatyami** [comment]
Just some notes ... Sake | Ale | Grape Wine | Mead | Apple Cider need to be made into real fluids.

**Comment by Alatyami** [comment]
Pushing to 2.2.4, just didnt have enough time to complete. The Ale Fluid is done but still need to make it bucketable.

**Comment by IceDragon200** [comment]
@alatyami I've started a different branch for tackling this, the main difference is the use of a general  base classes for all the booze and BREAKING the current bucket item, I've left it in for now, but it should be removed in later versions (its hard to miss that ugly DEPRECATED)

https://github.com/alatyami/Growthcraft-1.7/tree/fluid-blocks

**Comment by Alatyami** [comment]
Yah, my plan was build out the fluids in parrallel and then rewrite the FluidTanks to be rightclick-able to draw the ale/wine out. Next would be to add a tap to the barrels.
