### ISSUE TITLE
Fix fuel handler issues

### ISSUE THREAD

**Issue by labpaw** [GrowthcraftCE/Growthcraft-1.7#55]
There are 2 issues with fuel handler:

1) Apple sapling have missing fuel value. It's should have 100 ticks burn time.

2) Bamboo slab have incorrect fuel value (300 but should have 150). It's happens due to bug in FML/Forge but you still can workaround this. Check how [Forestry fixed it](https://github.com/ForestryMC/ForestryMC/commit/6870dafe020e25dfe16ee6467b1660638671fd1a).

**Comment by Alatyami** [comment]
@Adaptivity Bamboo is at 300 or 800?

**Comment by labpaw** [comment]
Bamboo _slab_ have 300 but should have 150.

**Comment by Alatyami** [comment]
@Adaptivity I have fixed bamboo, now for Apple sapling.
