### ISSUE TITLE
Modpack Request

### ISSUE THREAD

**Issue by spannerman79** [GrowthcraftCE/Growthcraft-1.7#57]
As per Terms regarding addition to modpacks I am requesting permission to add GrowthCraft CE to my pack.

Pack Name: Unknown yet - still talking with mates over the name to be honest 
Pack Status:  Private/hidden with possible future public release
Pack Deployment method: via Technic Launcher self hosted Solder setup (http://solder.io/)
Mod list:  See this is where it gets tricky - unless you already know how solder actually works I cannot give an actual mod list until **all** intended mods are added and the pack published and pushed into technic.  Before I can add mods I need to get the required permissions before I will spend the time needed to enter the mod details into my solder setup (view screenshot)

![capture](https://cloud.githubusercontent.com/assets/7542384/9319553/29f21078-4593-11e5-9067-8aac732696d0.PNG)

Catch 22

**Comment by Alatyami** [comment]
That is a catch ...

You can use Growthcraft CE in your mod pack. Let us now if you need anything extra for submitting your modpack to the launcher.

**Comment by Alatyami** [comment]
Side note, if your pack goes public, let us know and we'll list it in our Readme file.
