### ISSUE TITLE
Find artists for the logos of future modules

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#58]
We need an artist to aid with the logos of future modules. Does anyone know of anyone that can aid with this? I am contacting one of my friends to see if she can aid with this, but, the answer will likely be no.

**Comment by Sunconure11** [comment]
I also set up the issues page on Curse, which should connect it to this github issues page.

**Comment by PitchBright** [comment]
I should be able to do this for ya, but I'm always tight for time. That said, I'll be upfront and honest... I hate "design by committee". I'd want the authority to implement what I decide on. That doesn't mean I'm not open to feedback. But it also means, while I'm open to feedback, I won't necessarily bend to it. LOL.

My approach with it would be to honour the existing style and identity that Gwafu has established. I think he did a great job there, and there's no sense in me trying to reinvent it. I've sourced out some of the artwork and materials he used, and I'm pretty sure I can replicate the look that he's created, when it comes to creating new stuff. 

When it comes to preparing artwork, if something needs to be created (a web banner for example)… I would really like to have all the information I need to execute the design and live-ready files… meaning specs and format you require. So it'd be a "Tell me what you need, how you need it, and how I can get it to you" thing. The idea being that I can pump out what you need, quickly.

**Comment by Ar97x** [comment]
@PitchBright I think we should keep Gwafu's art style too. I can always give some attention and eventual feedbacks. Like you said, you don't need to follow precisely my commentaries.

**Comment by IceDragon200** [comment]
I think we can close this, @PitchBright does a pretty good job for us :)
