### ISSUE TITLE
IRC channel for Growthcraft

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#59]
Sorry, I know this isn't an issue… but didn't know where else to get a message through to the devs, since I don't know how to PM on git.

I've started an IRC channel #growthcraft on espernet, with the hopes that the devs and community will enjoy/use it. Already had a couple people pop by in the first 24hrs. So there must be a little bit of a need for it. If the devs join, we'll hand over the keys to the channel to them so they can own it.

**Comment by Alatyami** [comment]
Sounds like a great idea ... we'll take it on. I should be in there later
tonight. GitHub unfortunately doesn't have messages :(

~Alataymi

**Comment by spannerman79** [comment]
There is [Gitter](https://gitter.im/)

**Comment by Alatyami** [comment]
We now have a persistent IRC chat room on espernet. 

Gitter has a max 20 or 25 in the room.

**Comment by spannerman79** [comment]
Perhaps my suggestion for Gitter was wrong.  There is [discord](https://discordapp.com/)
