### ISSUE TITLE
Modpack Request: Compitum Magia

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#62]
Within a couple of days, I will be updating this modpack to use the new version of Growthcraft, along with several other mods.

http://www.technicpack.net/modpack/compitum-magia.647447

I will be removing ESM, and adding Custom NPCs and Et Futurum.

This modpack was originally created as a collaboration between me and another user, but, he seems to have lost interest in minecraft.

**Comment by Alatyami** [comment]
Lost interest in minecraft ... that just isn't right. 

Inclusion of Growthcraft CE in your modpack is automatically approved.
