### ISSUE TITLE
Requesting modpack permission

### ISSUE THREAD

**Issue by TokenSlot** [GrowthcraftCE/Growthcraft-1.7#63]
I would like to add GrowthCraft for my modpack (already had Gwafu's GrowthCraft added to the modpack but I want an updated version)

Ultimate HarvestCraft
Link: http://www.technicpack.net/modpack/ultimate-harvestcraft.566785

Mods:
Calendar Mod
Doors O' Plenty
Doors by iChun
Lattice Mod
Garden Stuff
SmartCursor
DoggyStyle
BrewCraft
AquaCulture
bspkrsCore
Backpack mod by Eydamos
Code Chicken Core
Dynamic Lights
Inventory Tweaks
Item Physics Mod
Furniture Mod
Not Enough Items
Pam's HarvestCraft
Pam's Get All The Seeds
Pam's WeeeFlowers
Tree Ores mod
TreeCapitator mod
Extended Farming
Extended Villages
LotsOMobs
iChunUtil
Backtools
Hats mod
Quick Hotbar
BuildCraft 
NotEnoughKeys
Magical Crops
Storage Drawers Mod
CreativeCore
Enchiridion
Biomes O' Plenty
EasyCrafting Mod
Carpenter's Blocks
Enchanting Plus
Ztones mod
Baubles
Botania
TConstruct Mod
Pam's Harvest The Nether
Better Sleeping
EnderCore
JourneyMap

**Comment by Alatyami** [comment]
Inclusion of Growthcraft CE in your modpack is automatically approved.
