### ISSUE TITLE
Modpack Request - Mechanical Haven

### ISSUE THREAD

**Issue by Spydog123** [GrowthcraftCE/Growthcraft-1.7#64]
Hello,

I am requesting to use your Growthcraft Community Ediition mod in my modpack,

You can find the modpack using this link - http://forum.feed-the-beast.com/threads/1-7-10-mechanical-haven-tech-300-mods.83487/

And as for the mod list, you can find it using this link - https://github.com/Spydog123/Mechanical-Haven/blob/master/Mod%20List

I will soon make a google spreadsheet for the mod list.

Thanks and good luck with this mod!

**Comment by Alatyami** [comment]
Thank you for letting us know your mod-list. If you have any issues, you know where to find us. Of note, I'd switch the Growthcraft by Gwafu to "Growthcraft by Growthcraft Community Team".

Inclusion of Growthcraft CE in your modpack is automatically approved.
