### ISSUE TITLE
Prickly pear textures

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#65]
A user has made textures for the prickly pear plants. Should we implement them now, or make our own?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2505072-growthcraft-community-edition-proper-1-7-10?comment=32

**Comment by Alatyami** [comment]
We can create a branch and then put it in as a pull request for them.

**Comment by Alatyami** [comment]
I'll pick this one up unless someone else already has?

**Comment by Alatyami** [comment]
Didn't realize that this was actually for a new Item. Which mod do we want to add this too?

**Comment by Yulife** [comment]
It's a cactus fruit iirc so desert module? :)

**Comment by dandudek7** [comment]
Yeah you remember correctly, it's a cactus fruit. You use the fruit press to make it into colonche.

**Comment by Sunconure11** [comment]
Hm, how should we have the plant grow to use these textures?

**Comment by dandudek7** [comment]
It grows like a cocoa bean but on cactus instead of wood.

**Comment by Sunconure11** [comment]
That's what I'm interpreting from the textures.

**Comment by Yulife** [comment]
If you want to make it grow on cactus won't it have a gap between the cactus and its fruit? A cactus isn't a full block. You guys might need to add some offset or something depending on where it's facing the cactus.

**Comment by Ar97x** [comment]
Or maybe add some other kind of cactus that is adapted to the texture, or making it grow on top of the cactus.

**Comment by Yulife** [comment]
Actually, cactus fruits usually grow on top of a cactus. Perhaps you could add it ontop :) Yeah, a Prickly Pear Cactus would fit. haha

**Comment by Sunconure11** [comment]
Yeah, they do.

**Comment by Sunconure11** [comment]
http://www.pricklypearjuice.org/resources/BusinessPricklyPearLabelPicture.Extended.Agreement-1.jpeg.opt425x283o0,0s425x283.jpeg

Also, does anyone have any suggestions for future desert crops aside from Agave, Prickly Pears, and Ocotillo? I think it could be a bit more fleshed out.

**Comment by Ar97x** [comment]
I don't have any, but I think we should work on new kinds of cactus, maybe one that stores water, one that flourish and give the prickly pears, it's something I would like to see on a desert module.

-------- Mensagem Original --------
De:Joseph Caleb Jones notifications@github.com
Enviado em:Thu, 27 Aug 2015 16:16:21 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Cc:Ar97x vdiehl97@gmail.com
Assunto:Re: [Growthcraft-1.7] Prickly pear textures (#65)

**Comment by EnderCreeper15** [comment]
[url=https://33.media.tumblr.com/576636de65faa183876034153a2d95b7/tumblr_nsp66cIGGw1tzoqq7o1_500.gif]Cactus juice, anyone? [/url]

**Comment by dandudek7** [comment]
Cactus juice!! https://33.media.tumblr.com/576636de65faa183876034153a2d95b7/tumblr_nsp66cIGGw1tzoqq7o1_500.gif

**Comment by dandudek7** [comment]
Cactus juice could be crafted with a cactus and a bottle, it gives you a hallucinogenic effect but if the Thirst mod is installed it could restore a lot of thirst.

**Comment by Ar97x** [comment]
Yeah, that's good, I thought of water from cactus because I play a lot with Thirst mod

-------- Mensagem Original --------
De:Daniel Dudek notifications@github.com
Enviado em:Thu, 27 Aug 2015 17:25:47 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Cc:Ar97x vdiehl97@gmail.com
Assunto:Re: [Growthcraft-1.7] Prickly pear textures (#65)

**Comment by Sunconure11** [comment]
I have create textures for prickly pear juice.

**Comment by Sunconure11** [comment]
Sorry about the request spam, I'm trying to get texture commits pushed, but, for some reason they won't load unless I submit another pull request. WTF am I doing wrong?

**Comment by Alatyami** [comment]
@Sunconure11 Unless you are editing Development directly you have to do a pull request to merge your branch with the snapshot release.

**Comment by IceDragon200** [comment]
@Sunconure11 What exactly was this issue open for? If its just a texture we could drop it into development and just close this, I'm going around cleaning up issues

**Comment by Sunconure11** [comment]
I think we already did do so, but, feel free to close it anyways, and see if it isn't in development.
