### ISSUE TITLE
Nether module

### ISSUE THREAD

**Issue by dandudek7** [GrowthcraftCE/Growthcraft-1.7#66]
Pretty much every idea we have for Growthcraft so far has been in the Overworld only (well except for the magic vines). We should probably add some content to the Nether as well, especially since right now in vanilla, the Nether has literally only one crop. 

Ideas:
- Soul squash: a pumpkin-like plant that grows on soul sand. The stalk grows upside down and the block spawns under it. Soul squashes are found under soul sand. Possible uses: unknown, probably food related. 
- Cinderrot: a fungus that grows on netherrack and can spread on the sides, top, or bottom of a block. Lights you on fire if you touch it. Spreads slowly. Can be used to brew firebrandy (in a kettle), which gives you fire resistance but also lights you on fire.
- Firelily: lily pads that grow on the lava. Somewhat rare, and cannot be farmed. Craft a boat with 3 firelilies on the bottom, and 2 obsidian on the sides, to make a lava raft.

Anyone have any other ideas? Or amendments to my ideas?

**Comment by Ar97x** [comment]
Damn, I was thinking about Nether stuff whrn I saw it, what about Nether
Peppers, that grows on soul farmland (plotted soul sand with lava nearby),
that can be used on a fruit press (perhaps a Nether version?) and make
pepper sauce, that gives haste and hunger, or crafted with sugar to make
peppermint (ba dum tss). We can think on some drink to put you out of fire,
maybe made of some kind of crop that can't be farmed, growing above the
glowstone chunks? I got a lot ideas for it, but I don't wanna write a giant
text (I think I already have)

**Comment by Sunconure11** [comment]
I shall write a bunch of ideas, and include these.

**Comment by Sunconure11** [comment]
https://github.com/alatyami/Growthcraft-1.7/wiki/Growthcraft-Nether-(Concept)

**Comment by dandudek7** [comment]
Nether peppers? Sounds cool. Perhaps call them ghost peppers as a reference to the real life ghost pepper, which is one of the spiciest peppers in the world (I tried it once, -666/10 would not eat again).

I could try to have some textures up soon.

**Comment by dandudek7** [comment]
Also, sunconure, I just read through the wiki and your ideas are awesome. ... And now I have like 3x more work to do. It's cool though, not like I was planning on starting my summer reading anyway :)

**Comment by Ar97x** [comment]
I liked ghost peppers, but I think  that having fire resistance for more than one plant is redundant. The ectoplasm idea is good too, specially if we have a way to farm it. Perhaps we can make it a secondary output for the drinks (just like bone meal, but for nether stuff, and more rare). I would like to have the terrain to plant like rice paddys, but using lava and soul sand. I think the peppers spawning in nether fortress is nice too. Maybe we can make add some building blocks to add new structure(s), a kind of wood that doesn't burn sounds cool?

**Comment by Sunconure11** [comment]
I am considering some kind of tree for the nether. I'm writing stuff for the end, and have atleast one tree for the end.

**Comment by Sunconure11** [comment]
I added some of the changes in this thread to the nether concept page.

**Comment by dandudek7** [comment]
Yeah having fire resistance for more than one plant is pretty redundant. Maybe instead of brewing, make ghost peppers a potion ingredient for a new Incendiary Potion (hot sauce lol) which lights the target on fire.

**Comment by dandudek7** [comment]
Ok I'm gonna go to bed but here's what I got done so far: https://www.dropbox.com/s/kny2wlsr7meil85/Growthcraft%20Nether.zip?dl=0

**Comment by Sunconure11** [comment]
I will send these in a pull request.

**Comment by Ar97x** [comment]
Incendiary splash potion, that's really cool. 

-------- Mensagem Original --------
De:Joseph Caleb Jones notifications@github.com
Enviado em:Thu, 27 Aug 2015 21:25:21 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Cc:Ar97x vdiehl97@gmail.com
Assunto:Re: [Growthcraft-1.7] Nether module (#66)

**Comment by Sunconure11** [comment]
Why is it that every time I send a pull request, it screws up in my face?

**Comment by Sunconure11** [comment]
I am considering netherrash infected variants of all vanilla mobs, plus the few mobs I will create models for when/if the butcher module is made. I can probably do them in the mean time while I try to figure out an idea for the still properly.

**Comment by Sunconure11** [comment]
I will also probably tweak the concepts so ghost peppers can be used for incendiary splash potions.

**Comment by Sunconure11** [comment]
But I'll go to bed, I'm feeling a bit under the weather.

**Comment by Yulife** [comment]
Wouldn't that be a bit overkill? Hehe. And I agree to the name ghost peppers.

**Comment by Sunconure11** [comment]
I submitted the muertecap textures.

**Comment by Ar97x** [comment]
The GC Nether concept page is amazing, I read it all and I'm so excited for it, can't wait to see all of it in game!

**Comment by ghost** [comment]
can this feature be optional? i don't like plants in the nether and i don't like lava or obsidian boats. silly.

but if i had to pick some things here is my only 1 choice

ghost vines = kinda like a semi transparent ghostly grass that grows 1-4 blocks high and can grow anywhere even inside blocks. you plant it then place blocks on top of it . these blocks will eventually become possessed by these vines and will become sentient. you will notice a bunch of eyes appearing when this happens. these eyes blink once in a while like an animated texture.  these possessed blocks will output a signal whenever they spot a hostile mob moving around them. if you destroy a possessed block they become normal blocks and the ghost vines cannot be recovered. they have no seeds and cannot be bred but only found. you have to punch their base block to to take them. 

depending on what block is possessed  they will also move or do certain actions like a note block will output sound, a door will open and close randomly, jukebox will play strange sounds, glowing blocks will turn on and off quickly. 

ghostly vines grow downward up to 4 blocks but only if not inside blocks..if blocks have been placed then will simply go in possession mode . 

they grow   downward so if you plant it on the ground you will lose them as they simply go inside the ground you can't let them touch the ground that's what they want. spirits that want to go to the world of the dead trapped in between.

**Comment by IceDragon200** [comment]
@trollworkout The Nether module is standalone, planned for the 2.4.x release, all modules will be available as seperate jars, or you can grab the complete jar, your choice, as for you suggestions, I'll let the others comment on that

**Comment by IceDragon200** [comment]
If you've been watching the commit feed, I've been working on the nether module you can see the [screenshots](https://www.dropbox.com/sh/3qccjuwo295uep1/AACEt-VU2uDzXeQSZo2S_tCva?dl=0) and watch the [grcnether branch](https://github.com/Alatyami/Growthcraft-1.7/tree/grcnether) for changes

@Ar97x @Sunconure11 @EnderCreeper15 @trollworkout

**Comment by Ar97x** [comment]
Amazing work as always @IceDragon200, I think the textures will be on
@Sunconure11 right? And the lava paddy looks awesome, just need to change
the name on Waila :D

**Comment by Sunconure11** [comment]
I guess I'll create a few new textures.

**Comment by Sunconure11** [comment]
I'm working on the lotus at the moment. I'll create a separate block for the flower, and possibly a variant that has gone to seed.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/pl8taonilk037qb/maralotus.png?dl=0

One new texture created. I should not be up this early.

**Comment by Sunconure11** [comment]
I'll probably create the textures for the new tree later today.

**Comment by Sunconure11** [comment]
Also, does anyone have the models of the vanilla mobs in a format that can be used in Techne?

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/igb4qg7u45ac7hp/malicesapling.png?dl=0

**Comment by IceDragon200** [comment]
@Sunconure11 https://github.com/Alatyami/Growthcraft-1.7/commit/a3deba884eb7e316c46b72e2f60ea7d3b2e2c674

**Comment by Sunconure11** [comment]
I'll work on the ghost model when my sleep is back on track. I don't feel I'm functional enough for that at the moment.

**Comment by Sunconure11** [comment]
I might create a few simple textures though

**Comment by IceDragon200** [comment]
@Sunconure11 Could you do these textures:
- Knife Bush
- Baal's Rot
- Malice \* (pretty much all the malice related stuff, my placeholder textures would make endermen steer clear of the blocks)
- Soul Squash (its just the pumpkin hue shifted and inverted currently)

Also, what are the official colors for the `Fire Brandy` and `Malice Cider` (I use a kind of washy red for the Fire Brandy and an expired looking white color the Malice Cider currently)

May I suggest formatting the items/points/ideas

> ### Cinderrot
> 
> **Preparation Method**: Brewing

etc..

And now.. I must rest, so exhausted

**Comment by Sunconure11** [comment]
Working on the Baal's Rot texture. Also, I think your ideas for colors are good, though I think Fire Brandy could use a scarlet color.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/ajws5acg6zuks9d/baalrot.png?dl=0

**Comment by Sunconure11** [comment]
For the color of Fire Brandy, why not this?

https://en.wikipedia.org/wiki/Scarlet_(color)#Fire_brick

**Comment by IceDragon200** [comment]
@Sunconure11 I've changed the color now, also your recent textures have been missing the alpha channels

**Comment by Sunconure11** [comment]
How would I fix the alpha channel? I use paint.net to make textures.

**Comment by Sunconure11** [comment]
I'll do Soul Squash textures soon, I think I have fixed my sleeping habits.

**Comment by Sunconure11** [comment]
Also, I think I found out what is going on with the images. They are indeed transparent, I think there must be a different way of downloading them.

**Comment by Sunconure11** [comment]
Try downloading the images through this:

https://www.dropbox.com/s/ajws5acg6zuks9d/baalrot.png?dl=1

Change dl=0 to dl=1. This will give you the proper image.

**Comment by IceDragon200** [comment]
@Sunconure11 so in short, dropbox stripped the alpha channels for the previews...

**Comment by Sunconure11** [comment]
Basically.

**Comment by Yulife** [comment]
That looks really flat. I suggest you use the vanilla mushroom as a base and then extend.

**Comment by Sunconure11** [comment]
Yeah, it does. I made it when I was half awake. I want to change it.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/94ctsj97lx47d8x/baalsrot2.png?dl=0

What about this?

**Comment by Yulife** [comment]
It doesn't look like it has any gradient (shading).

**Comment by Sunconure11** [comment]
I always put some noise in. What about this?

https://www.dropbox.com/s/gg7l01b0yshf9vl/noiselessbaal.png?dl=0 It lacks noise.

**Comment by Yulife** [comment]
Like I said, it doesn't have any shading. I suggest you look up some texturing tutorials or pixel art tutorials to get the basics :)

**Comment by Sunconure11** [comment]
I'll see about redoing it later then.

**Comment by Sunconure11** [comment]
Do you have any good resources for this? Because I tried to shade it like the brown mushroom.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/zkz2vvjw2lxt8cy/Screenshot%202015-10-19%2015.28.28.png?dl=0

What about this?

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/6ua494szubik9z5/Screenshot%202015-10-19%2015.34.35.png?dl=0

A more tweaked version. If this is satisfactory, I will release the file.

**Comment by Yulife** [comment]
Yeah thats much better. Give it a subtle dark border and it's great!

**Comment by Sunconure11** [comment]
I'll push it out tomorrow.

**Comment by Sunconure11** [comment]
I think a border would look weird on it, but, I'll submit it now. Though I'm not sure when I'll make my new textures, though I do have ideas for the malice tree that are a bit macabre. For one thing, I have an idea to make the interior of the wood look like a spinal cord.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/031rg44g1brzyq0/baalsrot3.png?dl=0

Current texture for Baal's Rot.

**Comment by Sunconure11** [comment]
Your malice wood textures are fairly good BTW.

**Comment by Sunconure11** [comment]
The ghost model and textures are next. I'll start work on it tomorrow. Humanoids are fairly easy to do. I'll make it translucent too. Then I'll think of ideas for the soul squash. Why not make it similar to Chayote Squash, and you can grow them using the fruit? https://en.wikipedia.org/wiki/Chayote

**Comment by Sunconure11** [comment]
Regarding knife bushes, the idea came from reading into various mythologies. (https://en.wikipedia.org/wiki/Diyu#Eighteen_Levels_of_Hell based off of the mountain of knives)

So likely, I will make it a collection of sharp rocks. Not sure how the crude knives made from them would look yet.

Also, I thought of a death message for dying via netherrash infection.

[PLAYERNAME] Scratched himself to death

**Comment by Sunconure11** [comment]
Also, I guess I can create some miscellaneous textures to go along with the ghost model. The ghost vine could work somewhere, though it would be very difficult to pull off. Maybe one day.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/xmpvnyixda90anj/Screenshot%202015-10-26%2012.58.57.png?dl=0

Working on it. However, it looks a little too much like vanilla zombies. Are there any other traits I should add to it?

**Comment by Ar97x** [comment]
Fluctuation, for sure. Maybe a scary face and no arms, and chains around
the body would be really cool

**Comment by Sunconure11** [comment]
Chains could be done via texturing, as well as the face. Flight would have to be done via the code.

**Comment by Ar97x** [comment]
You could make the bottom transparent, to just look like it's flying, but I
guess that would be in texturing too.

**Comment by ghost** [comment]
hey guys i got this idea for nether plant. 

chain vines. 

this plant that grows like long chains hanging from the ceiling of nether and they grow down a lot. quite rare. when you break them they break into chain links which you can use to craft chainmail armor. but you can also use to climb on them  . i dunno. what do you think?

**Comment by Sunconure11** [comment]
I don't think chainmail should be handled by this mod. If it is, it should be crafted from mundane materials.

Also, speaking of the ghost, I think I know how to implement the ideas for it mentioned. I'll texture it this weekend, since with your ideas, the model might as well be finished.

**Comment by Sunconure11** [comment]
Also, transparency CAN be handled by the textures, not just the code.

**Comment by Sunconure11** [comment]
Also, I'm pretty sure it is possible to code the mob to fly without texturing it to look like it. I will see if Ice or someone else can pull that off when I finish the texture. The model is pretty much finished, I'll just remove the arms. Chains will probably be done via the texture. To be fair, I have been toying with desert module ideas a bit.

I don't have any ideas for the texture of the soul squash yet, but, I suppose I can deal with that during the weekend as well. The stem could be made red.

**Comment by Sunconure11** [comment]
While I wait for a friend who is potentially suicidal to come back on, I'm going to try to replicate this texture:

http://www.minecraftforum.net/forums/minecraft-discussion/suggestions/72791-ghast-powder

As for the ghost, I have a design idea in mind that might be easier for me to pull off.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/jiceovn74lfetfw/Screenshot%202015-11-03%2022.32.43.png?dl=0

I tried to rip the texture for the image instead.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/j9sztcvl7k4005a/ghastpowder.png?dl=1

See if this is good enough.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/i4c6wjkdpof3kch/Screenshot%202015-11-07%2018.43.09.png?dl=0

Working on the ghost. I plan on doing the soul squash after I finish these textures.

I'll conjure up malice leaf textures quickly.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/nb2lfvf2o4m9aek/leaves_malice.png?dl=0

Squanched this up in a few minutes

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/kh1f7w9otxue458/leaves_malice_opaque.png?dl=0

We should also create blocks for apple leaves, so they will drop apple saplings and such.

**Comment by Sunconure11** [comment]
I'll be uploading textures for the soul squash stem in a few minutes.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/cnin0yjnccofz2c/soulsquashstems1.zip?dl=0

They have been tweaked to have a new color scheme, and to make them a little more distinct from vanilla vines.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/8lty3cmkfc8ngpq/Screenshot%202015-11-14%2008.20.36.png?dl=0

Working on new soul squash textures.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/gms7ujzokit6b6u/soulsquash_side.png?dl=0

https://www.dropbox.com/s/lilyq657uvr0yae/soulsquash_top.png?dl=0

**Comment by Sunconure11** [comment]
I also have a few textures from an un-used mod idea of mine that had a bunch of nether content, and various miscellaneous items that might be of use. Would anyone be interested in the following?

Soulbricks (Based off the usage of souls as building materials in Wayne Barlowe's depictions of hell)

Reptile Scales (If any reptilian mob is added, this could be a possible drop, the plan was to have them be usable as a crude form of armor between leather and iron)

And probably some others I forgot. I'll dig them up later.

Also, I am tempted to just use my preta for the ghost instead. Here is the model with the texture: https://www.dropbox.com/s/b0bsxph6tx8t1i2/Screenshot%202015-11-16%2009.08.33.png?dl=0

Should this be used for the ghost instead, or should I continue with my other ghost model?

https://en.wikipedia.org/wiki/Preta

**Comment by Sunconure11** [comment]
I'll just send over the Preta model and use that for the ghost for now.

Also, I decided against giving Soul Squash a pumpkin-like face. Textures for them as of now are complete.

https://www.dropbox.com/s/0r5khc7qgrga3od/preta.zip?dl=0

**Comment by Sunconure11** [comment]
I'll work on knifebushes next. Though I don't have a concrete plan in mind for their appearance as of yet.

**Comment by Sunconure11** [comment]
I feel like doing some progress towards the Desert Module. I have at least one idea for a neutral mob (goats are too conventional, and will be saved for the butcher module). https://en.wikipedia.org/wiki/Nothrotheriops

Not sure when I'll start modeling this, but, I might wait until after I think of an appearance for the knife bush in general.

**Comment by IceDragon200** [comment]
@Sunconure11 Added the new nether textures and booze

Sorry its taking so long, I'm trying to get the booze system sensible, but its making me pull my hair out orz

[Screenshot](https://dl.dropboxusercontent.com/u/72618186/screenshots/minecraft/growthcraft/nether/2015-11-22_16.50.49.png)
- top left, Malice Cider
- top right, Gelid Booze
- bottom left - Vile Slop
- bottom right - Amrita

**Comment by ghost** [comment]
@IceDragon200 @Sunconure11  I got a simple idea for a crop

some crop that can be harvested and is used as furnace fuel . you can work the details later. like maybe only grows in nether with lava instead of water? i don't know.

**Comment by Alatyami** [comment]
Do you mean like the Magic Crops Coal Plant?

**Comment by Sunconure11** [comment]
A fuel crop could work, the closest I have to this is in my plans for the desert module (Jojoba).

**Comment by ghost** [comment]
@Alatyami  I don't know Magic Crops Coal plant. Is that from a different mod? Either way sounds about right a coal fuel type plant sortof fits well in the nether.  
@Sunconure11

**Comment by Sunconure11** [comment]
Added a concept for a fuel crop.

**Comment by Sunconure11** [comment]
Leaving this one open, as some legwork was done on it, and it should be recoded in the future.

**Comment by Sunconure11** [comment]
Closed due to lack of progress. Maybe one day. Though it might be better to create a new page for it if it is revisited.
