### ISSUE TITLE
GrowthcraftDistillery Mod

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#7]
All things to do with a still.

**Comment by SynfulChaot** [comment]
As distilling is part of the overall brewing process for many drinks, wouldn't this fit in with the Cellar module itself?  Why separate it out further?

**Comment by Alatyami** [comment]
I can see that.

**Comment by Alatyami** [comment]
Going to move to the Cellar mod as it already has the Booz in it.

**Comment by Sunconure11** [comment]
When we set up the page for the cellar fully, should I merge the distillery concept page into it?

**Comment by Alatyami** [comment]
Yes, please do.
