### ISSUE TITLE
Mod Pathing Over Bamboo Fences

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#73]
Another thing, can someone come up with a fix for mobs attempting to path over bamboo fences? Every world, I try making pastures with bamboo fences, and then hurriedly replace them when I see the animals pressed up against the fence and jumping up and down like somebody tripped with an armload of superballs.

**Comment by Ar97x** [comment]
I've seen this on Forum but I couldn't reply because I was on the smartphone, and Idk how to end a quote on it. Isn't it some minecraft pathfinding problem? I experienced almost the same thing, but with carpenters' fences, cause zombies AI looks like made on a calculator. So I don't think this is our business, it's Mojang's

**Comment by Yulife** [comment]
This is a vague guess but did you try to make BambooFence extend BlockFence and see if that works?

**Comment by IceDragon200** [comment]
BambooFence extends Block, and has custom logic for interacting with other Bamboo blocks, animals seem to trip out with custom fence blocks all the time. (Natura I'm looking at you...)

**Comment by Alatyami** [comment]
So then I'm hearing we should make the fence a fence and not a block? I was actually just about to make a branch to address this item.

**Comment by Yulife** [comment]
I ain't a good coder and it was just a guess but it's worth a try haha

**Comment by spannerman79** [comment]
For pathfinding I use the mod Special AI.  Helps/fixes Mojangs fubar AI/pathfinding

**Comment by IceDragon200** [comment]
@Alatyami  Oh yeah, I changed bamboo fences to actual fences some time back in development, so I guess we can close this
