### ISSUE TITLE
Move to bitbucket?

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#74]
I have been giving this a lot of thought ... BitBucket gives us alot more functionality than GitHub does. The biggest feature is being able to Vote up issues. It also gives us better control over permissions on branching. BitBucket uses Git the same as GitHub so development will be the same. 

What are your thoughts?

**Comment by Alatyami** [comment]
A thought on this is that I do not think Travis-CI will build from BitBucket.

**Comment by Yulife** [comment]
Well would this repo update as well? I would then need another account for BitBucket which is kinda tedious.

**Comment by labpaw** [comment]
Please no. Just NO. Please. Not a bitbucket... please... I tried it few times and just hate it. It's very slow and uncomfortable. Github MUCH better. People should move FROM bitbucket (and some of them doing so). Not TO bitbucket.

**Comment by Alatyami** [comment]
Hehe ... The more I think of it .... I agree. I like the functionality of
bitbucket but it is still lacking the integration features that we need.

James E. Hunt

**Comment by Ar97x** [comment]
I don't even know how to use GitHub completely, so my vote is no.

**Comment by IceDragon200** [comment]
I used bitbucket in the past, I've had random freezes while pulling and pushing, somehow managing to obtain admin rights just by being a contributor (this has been fixed, but it was fun to play around with), confusion with whether the repo was git based or mercurial based, downloading latest HEAD as a zip being horribly broken on some repos.

May I say more?
My vote sits on a no.

**Comment by Alatyami** [comment]
Not going to bitbucket.
