### ISSUE TITLE
Add another block layer below structures...

### ISSUE THREAD

**Issue by Geijoh** [GrowthcraftCE/Growthcraft-1.7#78]
...to prevent flooding when structures using water source blocks spawn on a slope, or any other form of odd generation.

**Comment by Alatyami** [comment]
This will be addressed in #79 and be in our next release.

**Comment by IceDragon200** [comment]
@stardustrider  We fixed this a few prs back, so I'll be closing this, if the problem still exists, please do not hesitate to report it
