### ISSUE TITLE
Add DEBUG logging to all config files

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#80]
In order to support, plugin support, we need to be able to tell users to increase the logging of the mod. To do this I recommend that we add a logLevel parameter to the conf files for the different sub-modules or create a global growthcraft.conf that will set the log level for all the sub-modules.

**Comment by IceDragon200** [comment]
Config in general needs an overhaul, we just throw everything unto the mod classes currently as static variables

**Comment by IceDragon200** [comment]
Debugging for all modules is available by setting "Enable Debugging" to true under the "Debug" catergory in config files
