### ISSUE TITLE
Add IceDragon200 as a contributor

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#81]
IceDragon200 has been a major contributor to Growthcraft CE and is a knowledgeable developer. If he agrees, I recommend that we add him as a contributor to the GitHub project. Thoughts?

**Comment by Ar97x** [comment]
Sure, he will be a great addition to the team.

-------- Mensagem Original --------
De:Alatyami notifications@github.com
Enviado em:Wed, 09 Sep 2015 17:45:41 -0400
Para:"alatyami/Growthcraft-1.7" Growthcraft-1.7@noreply.github.com
Assunto:[Growthcraft-1.7] Add IceDragon200 as a contributor (#81)

**Comment by IceDragon200** [comment]
O: How did I miss this?

Sure, I'm all up for it :3

**Comment by Alatyami** [comment]
It was a test :D
