### ISSUE TITLE
Modpack Request

### ISSUE THREAD

**Issue by Cealian** [GrowthcraftCE/Growthcraft-1.7#83]
Hi i want to include this growtcraft in my private modpack on the FTB Launcher
i already have the old growthcraft by Gwafu and want to update to the community edition.

mods: http://pastebin.com/N2Jw70gw

**Comment by Alatyami** [comment]
Thank you for letting us know your mod-list. If you have any issues, you know where to find us. Inclusion of Growthcraft CE in your modpack is automatically approved.
