### ISSUE TITLE
Still Model Progress

### ISSUE THREAD

**Issue by Sunconure11** [GrowthcraftCE/Growthcraft-1.7#85]
I will start progress on the still model. I will post all images of it here. Since I am not used to texturing metal objects, I might see if someone else wants to texture it when it is finished.

I also need a few good references to base it off of, since some of the images I'm finding suck. If you want to, post some possible references for the still model in this issue.

**Comment by Ar97x** [comment]
I would love to see a small version, but a multiblock version of it too, like those big distilleries, but what I wish is far more difficult, since it would need a lot more programming and texture work. There's a nice pic of the small version 
![copper_distillation_equipment_whisky_distillery_brandy_distiller jpg_220x220](https://cloud.githubusercontent.com/assets/10781341/9976927/b1b96806-5ec2-11e5-9e9b-ad7f8fc35e7c.jpg)

**Comment by Sunconure11** [comment]
Do you have a bigger version of that image?

**Comment by Ar97x** [comment]
I'm afraid not. Use it just as a base, the resolution is not quite good.

**Comment by Sunconure11** [comment]
Alright, I'll see what I can do. However, to keep with the style, it would likely have to be cubical, spheres are not possible in Techne, and it would not mesh well with the other machines.

**Comment by Ar97x** [comment]
If you're taking that image as a base, try to make it as two cylinders, one tall and thick on the top, with an output to a small condenser. Don't need to make it that complex. If you want one more simple, try this one 
![d200](https://cloud.githubusercontent.com/assets/10781341/9981459/9596f57a-5f8b-11e5-9847-d8dc0521f090.jpg)

**Comment by Sunconure11** [comment]
I think I can make that. However, I managed to screw up my sleep schedule for the 248928509238590235th time, but, I can definitely get done.

**Comment by Sunconure11** [comment]
Also, after I finish the Still, would anyone be interested in me making an Electric Eel? There are some concepts for a marine module floating around here. Plus I have not really modeled fish before, mainly just mammals and archosaurs (the clade of animals that includes dinosaurs, birds, crocodiles, pterosaurs, and an assortment of other reptiles)

**Comment by Sunconure11** [comment]
I will begin some progress on the base of the still today. I still need to fix up a modpack an incompetent dev decided to screw up on me.

**Comment by Sunconure11** [comment]
I'll take a small break before starting it fully, I'm always tired lately. Plus Lfja-ag decided to revive their totemic branch so I need to finish the texture for the bison.

**Comment by PitchBright** [comment]
Make it happen or shut it down.

**Comment by Sunconure11** [comment]
Closed until I can find a suitable design. It will be re-opened when I can do that.

Edit: Found a design that would fit and I like. However, don't expect it for 2.5.0

**Comment by Ar97x** [comment]
I know this has already been closed, but I found a model that seems really
nice, and it's not that detailed, which should be easier to make.
https://www.dropbox.com/s/jqaz2iu1ynyudto/images.jpg?dl=0

**Comment by Sunconure11** [comment]
That could work. The design I was thinking of was something I found when researching into stills from colonial america, however, the still you are about to see is huge, and would be a multi-block structure if done.

http://images.fineartamerica.com/images-medium-large-5/1-distillery-18th-century-granger.jpg

However, I will keep yours in mind as it might be easier to pull off.

**Comment by Ar97x** [comment]
I was going to suggest a multiblock structure, but I thought it would be
more difficult, for coding and for textures. But that model you sent is
really nice, and I would love to make one of these.

**Comment by Sunconure11** [comment]
I don't think a multiblock structure would be hard to model, though I have no clue if the only coder can even code such a model. Either way, I'm holding this off for the backlog for now.

**Comment by Ar97x** [comment]
I just thought of something that might be included within the still module.
We should think of a custom heat source, something that fits nicely with
the brew kettle and the still, that are the only equipment that need heat
currently. On the picture I sent two coments above there's a idea of how it
could be, I don't know how you call it there, also will the still be
included on cellar or a separate module?
