### ISSUE TITLE
Mod-pack request

### ISSUE THREAD

**Issue by bookerthegeek** [GrowthcraftCE/Growthcraft-1.7#86]
Since all that you ask is for I to post a request here at the GitHub to receive permission for the inclusion in my modpack, so here is my request.

> I humble request your divine permission to include this amazing mod in my humble collection of mods I dare to call a modpack.
> - BTG

As also requested, [HERE](https://github.com/MyM-ModpackTeam/B2B/blob/master/Credits.rst) is my mod index along with permissions so you may gauge future compatibility with other mod's. 

I look forward to your replies.

**Comment by Alatyami** [comment]
Have fun and enjoy our mod! 

By default you have permission to use the growthcraft community edition in your mod pack.

**Comment by bookerthegeek** [comment]
Thank you good gentleman and ladies! I shall work hard to produce a pack worthy of the inclusion of your mod.
