### ISSUE TITLE
Contributing discussion

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#87]
We can discuss this: https://github.com/alatyami/Growthcraft-1.7/wiki/Contributing-to-Growthcraft here instead of sidelining it in the #34

**Comment by IceDragon200** [comment]
`Setup forge`
You can pull the git repo or download the latest zip and do `./gradlew` (*nix) or `gradlew.bat` (windows), no need to grab forge, gradle does all that.

As for the PR process:

```
Work from latest commit on `development` branch
Implement your feature
Open a PR and add a simple description of your change
Wait for a contributor to review your code
We may ask you to squash your commits so be sure to read up on that

Extra:
Try your out most hardest to keep your PR focused on one feature/bugfix, this will make reviewing much easier :P
If you added a core/util/helper class, add some documentation and usage.
If you aren't sure about something, comment on it
If you aren't finished with your PR, but you'd like feedback on it, add WIP: to the title
```

@alatyami Or something along those lines, WDYT?

**Comment by Alatyami** [comment]
Ah, good feedback ... I really like the WIP flag.

**Comment by IceDragon200** [comment]
Well, the Wiki has details on this, so I'll close this now :3
