### ISSUE TITLE
Adding a Warf structure

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#90]
Originally discussed in #79, the idea of adding a randomly placed warf structure, near beaches and other large bodies of water.

Discussion is open, It won't be added to the referenced PR, but will be done later once the idea cements

CC @Ar97x, @Sunconure11, @alatyami

**Comment by Ar97x** [comment]
Ok, can you do it spawn on random beaches? If you can, I'll work on the
model tomorrow, so we can have it for the next update. Do you think we can
fit it in @alatyami?

**Comment by IceDragon200** [comment]
@Ar97x Possibly, but don't expect any villagers in it, I still haven't figured out structure spawning fully yet ;(

**Comment by Ar97x** [comment]
I think it won't be needed. Just making it spawn randomly is nice.

**Comment by Ar97x** [comment]
I don't know if it's open source, but Millenaire has random generated
buildings even with villagers (Millenaires), you could check the coding if
you find it useful.

**Comment by Ar97x** [comment]
I think we can settle this to 2.4, what do you think @IceDragon200? I can work on this at next weekend, the only thing lasting would be the coding to make it spawn on water bodies.

**Comment by IceDragon200** [comment]
@Ar97x I should be free over the weekend, so yup, lets make the warf!

**Comment by Sunconure11** [comment]
There appear to be plans to continue this as mentioned in another pull. Leaving this open for now.

**Comment by Sunconure11** [comment]
@Ar97x Are you still going to do this? If you want to get it into this build, I suggest starting progress now. You still have the schematics and such, I assume. If you are going to do this, I will deadline you for a month. If you fail to get it done within a month, I will hold this off into the backlog, and close it until you can actually do this.

You have until 3/21/2016 to finish this for either 2.5.0 or 2.6.0, depending on what gets released/worked on first by the time you release it.

**Comment by Ar97x** [comment]
Sure. Unfortunately tomorrow will be a really busy day. I'll start it by
tuesday and it should be done in the same day, since I already have the
build in mind and I can make it kinda fast.

**Comment by Sunconure11** [comment]
Moving this to 2.5.0 if you really do plan to do this.

**Comment by PitchBright** [comment]
@Ar97x Sounds good, buddy. Looking forward to seeing what you've got on Tuesday/Wednesday. We're counting on you to gett'er done.

**Comment by Sunconure11** [comment]
2.6.0 is getting closer, so, if you end up finishing this after 2.5.0 comes out but within the deadline, I will change the milestone to 2.6.0.

**Comment by Ar97x** [comment]
I got free time tomorrow (tuesday), so it will be done and uploaded until
wednesday dawn. BTW, have we decided where it should spawn (And if it is
possible for @IceDragon200 to make it this way)?

**Comment by Ar97x** [comment]
I expect your feedback guys. Don't want another fail build like the old
apiary.

**Comment by Sunconure11** [comment]
I remember we decided on beaches.

**Comment by Ar97x** [comment]
It'll probably need some several tests and fixes then, since the beaches
have irregular terrain and are mostly made out of sand, that is gravity
susceptible. How much time do we have til 2.5.0 release?

**Comment by Sunconure11** [comment]
There is no specified date

**Comment by Alatyami** [comment]
The target for 2.5.0 is the 29th, but we haven't actually set a hard date yet.

**Comment by PitchBright** [comment]
@Alatyami jump on GC irc

**Comment by Ar97x** [comment]
By day 29 it should be completely done, tested and functional.

**Comment by Alatyami** [comment]
if not then we can easily move the date ... no date is ever set in stone.

**Comment by Ar97x** [comment]
Ok, I got late because I spent most of my time searching for an usable beach and my game kept crashing (steam powered notebook, what you gotta do?). I uploaded some screenshots of the structure, to show what I've done. On the screenshots, there are two options for the hut, should it have the bed and the furnace or just the chest? And for the warf itself, fences or no fences? Any suggestions and comments are welcome. https://www.dropbox.com/sh/r3028e9bm0i0eln/AAAoUwJCpm4MxGwFwuBiwvAIa?dl=0

**Comment by Sunconure11** [comment]
Why not variants that have either one, the other, or both?

**Comment by PitchBright** [comment]
Wharf looks good with fences.

**Comment by PitchBright** [comment]
I'd be inclined to do that building in Wood. And maybe 3x3 instead of 3x2 so you have room for the bed, chest and furnace.

**Comment by Sunconure11** [comment]
I managed to dredge up your old wharf. It appears to have the schematic file, too.

https://www.dropbox.com/sh/ckjyafxohbciilc/AACiotip26XL3Exe_MDLp8Jla?dl=0

**Comment by Ar97x** [comment]
Yeah my dropbox is always clear, so I don't mind deleting anything, are you
thinking on anything about it?
I've made the hut on wood first, but It looked too much like a village
thing. Also, I like the stone brick variants, that give a nice random
aspect to the build. Looking at it now I can see the logs are kinda out of
place, I'll see tomorrow if I can get a good replacement.
3x3 would be good, I started it on 2x2 but made 3x2 to fit the bed.
And about the variants for the hut setup, it's with @IceDragon200, if he
can make it variable I can up both the schematics. I'll work on everything
tomorrow though, I'm really tired right now.

**Comment by Ar97x** [comment]
New Screenshots added: https://www.dropbox.com/sh/m437i51ui600f53/AADM4FJFmOWKLe66FECC7DAja?dl=0
Opinions and suggestions are ALWAYS welcome.

**Comment by IceDragon200** [comment]
@Ar97x "This Folder is Empty"
I'll add the structure, just need to figure out the world gen afterwards

**Comment by Ar97x** [comment]
It must have been still uploading when you looked. Check it again please.

**Comment by IceDragon200** [comment]
@Ar97x Still empty :(

**Comment by Alatyami** [comment]
Same here ..... "This folder is empty"

**Comment by Sunconure11** [comment]
The structure should include a few fish traps as well.

**Comment by Ar97x** [comment]
Sorry for the delay, I closed my pc before leaving, so it didn't upload.
It's ready now.
Em 26/02/2016 16:39, "Alatyami" notifications@github.com escreveu:

**Comment by Ar97x** [comment]
Thoughts?

**Comment by Ar97x** [comment]
BTW @IceDragon200, do you still have that problem with stairs metadata?
I've made the new versions with lots of details, so if you say it'll be
harder for you to code it I'll make it simpler.

**Comment by IceDragon200** [comment]
@Ar97x I think I figured them out, so go wild

**Comment by Ar97x** [comment]
I would like @Sunconure11 and @PitchBright to give opinions so I can move
forward and give it the ending touches.

**Comment by Alatyami** [comment]
Looks good. I like the wood and cobble structure.

**Comment by PitchBright** [comment]
The building looks much better in wood. Good job.

Dock looks good with fencing now too.

Can you use a vanilla boat, instead of the boat you made?

**Comment by Ar97x** [comment]
As you liked the wood and cobble one, I will keep that one for the schematic. I'm not sure of the vanilla boat, as it is an entity, not a block, so IceD is who you should ask. But if the boat doesn't look nice I can delete it.

**Comment by PitchBright** [comment]
@IceDragon200 is the vanilla boat do-able?

**Comment by Sunconure11** [comment]
Depending on the biome, how feasible is it to make it so the wood takes on the same wood used in the villages in the area? I know some mods have villages which have different kinds of wood.

Or would that have to be handled via the code?

**Comment by IceDragon200** [comment]
@PitchBright @Sunconure11 @Ar97x I should be able to spawn a boat in

**Comment by Ar97x** [comment]
I've spent half of my sunday hitting my head hard to figure out what's wrong with my MCEdit. I've tried everything I think that should work and nothing. It keeps crashing when I try to select the blocks and export them. I uploaded my map and a coordinate screenshot (coord) so you @IceDragon200 can export it. Sorry if it is too late. Have you figured out how you are going to make it spawn? 
EDIT: Please insert the boat near the wharf, I forgot :/

**Comment by IceDragon200** [comment]
@Ar97x Nope, dunno where I'll spawn it in, but I have someone I can bother about world spawning now :smiling_imp:

**Comment by Ar97x** [comment]
Good. Has 2.5 been released? If it has we should change the milestone 2.6
(or perhaps we can think on a 2.51, with bugfixes for the new additions and
so).

**Comment by Alatyami** [comment]
We have not tagged 2.5 release yet.

**Comment by IceDragon200** [comment]
@Ar97x 2.5 hasn't even entered staging yet ;O

**Comment by Ar97x** [comment]
So, any progress on this one?

**Comment by IceDragon200** [comment]
How about we move this to 2.6.0, along with some more fishtrap module improvements, we've been sitting on the 2.5 for a bit too long now.

**Comment by Ar97x** [comment]
Well, what about this? Will it be done for 2.6.0?
Also, I thought that since we have structure integration for all the modules we should consider one for milk module, and maybe a remake for the old cellar build, adding a place for yeast, changing only the interior, and bring it all to 2.6.0, what do you guys think?

**Comment by Sunconure11** [comment]
For yeast, some kind of crude lab would be better. Maybe it could have a chest with a custom loot string, and some of the other loot could be various alchemical ingredients, yeast, a legitimate source of poisoned booze, and some other stuff.

The cellar could be remade into a tavern, or we could have a seperate tavern. I suggest looking at the village taverns mod. It has a whole plethora of structures that might interest you. In addition, an actual cellar with underground parts would be nice.

For milk, perhaps a pasture or a dairy farm of sorts? Maybe a cheese cellar/cheese cave too, since some cheeses are aged underground.

However, maybe you want to figure out how to code it yourself? I suggest looking at the old pulls regarding the structures, and their resultant fixes. This is assuming you have enough time, of course. It can't hurt to try, though considering the size of the files for the structures, it's going to be very... difficult. Just put your best into it, and hope Travis compiles it.

https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/31/files

https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/32/files

https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/33/files

https://github.com/GrowthcraftCE/Growthcraft-1.7/pull/79/files

**Comment by Ar97x** [comment]
For milk I was thinking about modifying one of those village houses with
fences, making it look like a little farm and spawning a couple of cows
inside, but I can figure out something new too.
My first thought for cellar was to create a tavern too, and make some kind
of yeast room at the side or underneath it.
Now that I'm thinking, we could somehow (that's on you @IceDragon200)
replace the witch hut on the swamps by the Yeast Lab. This would make it
harder for players to find and could have more rewarding loot.
I'll buy a new mouse tomorrow and see what I can do.

**Comment by Sunconure11** [comment]
I don't think replacing the witch hut is a good idea IMHO. Instead, it should be a similar structure to the hut, with a similar spawning mechanism, but does not replace the hut entirely. That is, assuming you go that route. Plus if they are similar enough, players would have to look even harder to find something more rewarding, and if it uses the exact same spawning mechanism, there would be a chance the witch hut you would find would either be a witch hut, or a yeast lab, but you would only find out as soon as you go inside. Plus, we should refrain from modifying existing vanilla structures like that unless there is some need for it.

Maybe instead of a witch, there could be a mad alchemist (which would basically be a buffed up witch)? The alchemist could drop various ingredients, yeast, poisoned booze, and so on.

**Comment by Ar97x** [comment]
It's just a thought, I don't even know if it's possible. It could be a
village thing too, but with more common loot, maybe booze bottles and
common types yeast, like brewers, bayanus and lager, since origin and
ethereal are kinda hard to get.

**Comment by Sunconure11** [comment]
Considering the amount of generation mods out there, it is probably possible. Ice would literally just need to find an open source mod that alters the witch hut, and base the code off of that.

I was thinking it would be more suited for a village when I told you this in the first place.

This is the village taverns mod, BTW. I suggest looking at some of the structures for possible ideas.

http://mods.curse.com/mc-mods/minecraft/village-taverns-updated

**Comment by Ar97x** [comment]
I've played with village taverns before on 1.6.4, but I still took a few looks at the screenshots to get some inspiration. 
I've made a model for the dairy and started working on the tavern. I tried something for a village model for the Yeast Lab but didn't take any screenshots. If any of you wish to take a look, open my world and check the strange building in front of the dairy farm. 
Dropbox link to screenshots and world: https://www.dropbox.com/sh/q9mlubxebf3s82l/AAACMG5SwWAm0zBra_vhiSeRa?dl=0

**Comment by Ar97x** [comment]
@Sunconure11 I haven't seen your edited comment about coding it myself. I think that if I invest enough time on it I could manage it. But seeing the codes for the most basic schemas, like the rice field, I think would be almost impossible to make what I planned for the tavern. I simply don't have the time and patience to do it, at least the tavern. It would be a huge and beautiful thing, but if @IceDragon200 doesn't want to board on it, I can do something smaller. I'll see if I can put some time on it later. Which programming language is it? Java?

**Comment by Sunconure11** [comment]
Yes, all MC mods are in Java, or use it to a large degree.

**Comment by Ar97x** [comment]
Have you checked the builds and screenshots? FEEDBACK ALWAYS PEOPLE.

**Comment by Sunconure11** [comment]
Tavern looks good, though it could stand to have an interior, and have pictures of it. A facade isn't enough.

**Comment by Alatyami** [comment]
We are no longer developing Growthcraft for Minecraft Forge 1.7.10. If we have time or someone in the community wants to work on this feature/bug, we are more than happy to reopen this.

We are looking at implementing this request in newer versions.
