### ISSUE TITLE
Release Version 2.3.0

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.7#91]
**Milestone Management**
- [x] Shift Issues the next Milestone if needed.

**Create Release Notes Wiki Page**
- [X] [Growthcraft CE 2.2.3 Release Notes](https://github.com/alatyami/Growthcraft-1.7/wiki/Growthcraft-CE-2.2.3-Release-Notes)

**Comment by Ar97x** [comment]
What will be our major updates for this version?

**Comment by Alatyami** [comment]
Working on it ... this ticket will be our first "organized" release. We need to go through all issues labeled with the Milestone 2.2.3 and determine which ones need to be closed and which ones need to be pushed to 2.2.4. I have already pushed the Fluid rewrite to 2.2.4.

**Comment by Ar97x** [comment]
When do you plan to release it?

**Comment by Alatyami** [comment]
Wanted to do it yesterday ... should be this weekend.

**Comment by Alatyami** [comment]
All pull requests have been settled. Starting the release process on Friday morning unless someone posts to this ticket.

**Comment by Alatyami** [comment]
Ugh, got delayed. Going to cut 2.3.0 now and then if we want to add the latest PR's we can cut another one.

**Comment by Alatyami** [comment]
Incremented the version number in development and tested the jar to make sure this time that the version showed up everywhere.

**Comment by Alatyami** [comment]
The next release will all of the release process notes and messages in the PR. No need to clutter it up with another Issue.
