### ISSUE TITLE
Strange crash on breaking Vines

### ISSUE THREAD

**Issue by PitchBright** [GrowthcraftCE/Growthcraft-1.7#93]
I wonder if it's related to the Drop Rarity on Grapes.

http://pastebin.com/mWfSNfL8

**Comment by IceDragon200** [comment]
@PitchBright I'll take a look right now, can I get a bit more info though, does it happen randomly when breaking them, or does it ALWAYS crash when breaking vines?

**Comment by PitchBright** [comment]
It's random. Not every vine break causes it. Sometimes the server will full-on crash. Other times, the client just gets kicked from the server back to the menu.

This is all I was able to grab from the client console last time I was kicked as client: http://pastebin.com/pemi5Ghv

**Comment by IceDragon200** [comment]
@PitchBright What are your `rarity` settings, so I can test locally, (or just throw all your growthcraft configs at me)

**Comment by spannerman79** [comment]
I had a quick look at the pastebin - it could be a Forge Essentials Protection issue..

I know from previous experience (before i moved to kcauldron) the protection system within Forge Essentials wasn't 100% effective and did cause issues.

**Comment by PitchBright** [comment]
@IceDragon200 I had the rarity set to 0 on the server. I then tried it at 1, and it still crashed.

@spannerman79 I wondered the same thing at first. I can bounce the crashlog off those guys over there if IceDragon thinks it's a good idea'r.

**Comment by IceDragon200** [comment]
@PitchBright Bounce it off them, I'll try my hardest to crash it here, so we'll see whose successful first (or fails first? I have no idea)

**Comment by spannerman79** [comment]
@PitchBright when you were kicked were you in a Forge Essentials protected area when you tried to break a vine?  Do you have MyTown2 also on the server?  This is where it becomes complicated as both use ASM

**Comment by PitchBright** [comment]
@spannerman I'm not using protected areas. I also just looked at the perm debug, and permission is granted to break vines. No MyTown2 present.

**Comment by IceDragon200** [comment]
@PitchBright, @spannerman79: Fear not, for I have crashed the game with the same error

**Comment by PitchBright** [comment]
@IceDragon200 Okay cool. I hadn't hit those guys up yet. I won't, unless you tell me to.

**Comment by IceDragon200** [comment]
Rarity must not be 0, well that was an easy lookup...

``` java
    public static WeightedRandom.Item getRandomItem(Random p_76269_0_, WeightedRandom.Item[] p_76269_1_, int p_76269_2_)
    {
        if (p_76269_2_ <= 0) // that is rarity
        {
            throw new IllegalArgumentException();
        }
```

**Comment by PitchBright** [comment]
I've got it set to 1. We're definitely gettin' the Client Kick. I'll see if I can get it to crash the server too.

**Comment by IceDragon200** [comment]
I'll add a LESS OBSCURE ~~error~~ warning in growthcraft to prevent this from happening again.

Check your console for an angry rant `"RARITY WAS SET TO 0, THE WORLD IS CRUMBLING, WHAT HAVE YOU DONE ~ IceDragon"`

**Comment by spannerman79** [comment]
LOL @ angry rant.  Wished more mod devs would do that.  Easier to point out to people next time when they submit crash logs

**Comment by PitchBright** [comment]
Okay… this is all I get from the server console now when a client gets kicked. http://pastebin.com/1QUKdw94

Not sure if that's helpful at all, or not.

**Comment by PitchBright** [comment]
Sorry for the extra post here. So the server just went down  http://pastebin.com/FarwnCYF  I actually wasn't breaking any vines at the time, I had just hopped back on after my last post, jumped in a minecart near where I was breaking vines prior… and then the server went down. It's entirely possible that it was a delayed vine break from before, though.

**Comment by IceDragon200** [comment]
@PitchBright 
https://github.com/alatyami/Growthcraft-1.7/pull/95
I have a test build inside, give it a twirl and see if it solves anything

ALSO:
I think this will do for now, prevents you from shooting yourself in the foot, and it amuses me:

```
[01:02:30] [Client thread/WARN] [Growthcraft]: RARITY/WEIGHT WAS SET TO 0 FOR ITEM: item.grc.grapes, THE WORLD IS CRUMBLING, WHAT HAVE YOU DONE ~ IceDragon. Go set it to 1 or something.
```

ALSO.2:
I'm hitting the hay, I'll be of no use to anyone in my current state

**Comment by PitchBright** [comment]
@IceDragon200 Okay cool. Do I need to make sure all my other GC Crop drops are set to at least 1 as well?

Also, I am still suspicious of ForgeEssentials at least for the Client Kicking, because we weren't experiencing the issue before I updated FE today. Mind you, I'm not sure if anybody was breaking vines before that FE update… it wasn't until tonight that we needed to do a lot of work in a Swamp biome.

**Comment by IceDragon200** [comment]
@PitchBright Yeah, that would be best, set all the weight/rarity values to 1

**Comment by PitchBright** [comment]
I just popped the update onto my server, and it crashes on boot.

http://pastebin.com/dmxNEFj4

**Comment by IceDragon200** [comment]
@PitchBright Oh gawd not again, gimme a sec need to play around with gradle.

Okay, check the PR again I added a new build (Build 1)

**Comment by PitchBright** [comment]
Thanks! Server started up fine. I'll run with that for awhile and report any future errors to ya here, or if you've closed it, I'll hit you up on on the GC IRC.

**Comment by IceDragon200** [comment]
Closing, if the issue arises again, we'll reopen

**Comment by PitchBright** [comment]
We had a vine-breaking test-session, and by all reports, there were no crashes, either client or serverside.

**Comment by IceDragon200** [comment]
![Hell Yeah](http://thetrendguys.com/wp-content/uploads/2013/11/Hell-Yeah-Baby.jpg)
