### ISSUE TITLE
Inconsitent behaviour when right clicking hops or grapes

### ISSUE THREAD

**Issue by IceDragon200** [GrowthcraftCE/Growthcraft-1.7#97]
Right clicking a hop bush will pop the hops right off as an item, right clicking grapes? does nothing.
And apples are probably the same...

**Comment by labpaw** [comment]
I think grapes and apples should follow hops behaviour.

**Comment by Ar97x** [comment]
This is a good idea, we could implement it even in 2.2.3, if you can make
it until @alatyami releases.

**Comment by Alatyami** [comment]
Think we can resolve this one this week?
